#	GNUmakefile for the ecas module
#	Developed by Raj Srinivasan
#	$Id: GNUmakefile,v 1.1.4.1 2001/03/16 22:12:01 sbajaj Exp $
#

ECAS_HOME=../../../../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


SUBDIRS = dynamic

include $(ECAS_RULES_DIR)/directory.cfg
