#	GNUmakefile 
#       Developed by Abhay Ranade
#	$Id: GNUmakefile,v 1.6.690.2 2006/11/18 09:38:58 schenna Exp $
#

ECAS_HOME = ../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg

SUBDIRS = Apps Apps/PTAv2 Enrollment Global Renewal


include $(ECAS_RULES_DIR)/directory.cfg
