#	GNUmakefile 
#       Developed by Siddharth Bajaj
#	$Id: GNUmakefile,v 1.1.2.2 2000/05/02 07:05:01 sbajaj Exp $
#

ECAS_HOME = ../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


ifeq ($(CISCO), 1)
SPECIAL_sparc_DIRS = cisco
endif

SUBDIRS = activex plugins


include $(ECAS_RULES_DIR)/directory.cfg

