#define get_CertSerNum get_CertPref_CertSerNum
#define put_CertSerNum put_CertPref_CertSerNum
#define get_CertIssDN get_CertPref_CertIssDN
#define put_CertIssDN put_CertPref_CertIssDN
#define get_CertFrndlyName get_CertPref_CertFrndlyName
#define put_CertFrndlyName put_CertPref_CertFrndlyName
#define get_CertLogoUrl get_CertPref_CertLogoUrl
#define put_CertLogoUrl put_CertPref_CertLogoUrl
#define get_CertDispString get_CertPref_CertDispString
#define put_CertDispString put_CertPref_CertDispString
#define get_CertTextureUrl get_CertPref_CertTextureUrl
#define put_CertTextureUrl put_CertPref_CertTextureUrl
#define get_MarkAsRenewed get_CertPref_MarkAsRenewed
#define put_MarkAsRenewed put_CertPref_MarkAsRenewed
#define SetPreference CertPref_SetPreference
#define GetPreference CertPref_GetPreference

#include "certprefs.h"

#undef get_CertSerNum
#undef put_CertSerNum
#undef get_CertIssDN
#undef put_CertIssDN
#undef get_CertFrndlyName
#undef put_CertFrndlyName
#undef get_CertLogoUrl
#undef put_CertLogoUrl
#undef get_CertDispString
#undef put_CertDispString
#undef get_CertTextureUrl
#undef put_CertTextureUrl
#undef get_MarkAsRenewed
#undef put_MarkAsRenewed
#undef SetPreference
#undef GetPreference

