#define get_ReadOKDomains get_ProfMgmt_ReadOKDomains
#define put_ReadOKDomains put_ProfMgmt_ReadOKDomains
#define get_WriteOKDomains get_ProfMgmt_WriteOKDomains
#define put_WriteOKDomains put_ProfMgmt_WriteOKDomains
#define get_PasswdQuality get_ProfMgmt_PasswdQuality
#define put_PasswdQuality put_ProfMgmt_PasswdQuality
#define get_PasswdLength get_ProfMgmt_PasswdLength
#define put_PasswdLength put_ProfMgmt_PasswdLength
#define get_PasswdTimeOut get_ProfMgmt_PasswdTimeOut
#define put_PasswdTimeOut put_ProfMgmt_PasswdTimeOut
#define get_PasswdLockOutTries get_ProfMgmt_PasswdLockOutTries
#define put_PasswdLockOutTries put_ProfMgmt_PasswdLockOutTries
#define get_PasswdUnLockPeriod get_ProfMgmt_PasswdUnLockPeriod
#define put_PasswdUnLockPeriod put_ProfMgmt_PasswdUnLockPeriod
#define get_ProfileName get_ProfMgmt_ProfileName
#define put_ProfileName put_ProfMgmt_ProfileName
#define put_Password put_ProfMgmt_Password
#define get_SaveLocal get_ProfMgmt_SaveLocal
#define put_SaveLocal put_ProfMgmt_SaveLocal 
#define get_RoamProfile get_ProfMgmt_RoamProfile
#define put_RoamProfile put_ProfMgmt_RoamProfile
#define get_OpenProfFlags get_ProfMgmt_OpenProfFlags
#define put_OpenProfFlags put_ProfMgmt_OpenProfFlags
#define OpenProfile ProfMgmt_OpenProfile
#define CloseProfile ProfMgmt_CloseProfile
#define SaveProfile ProfMgmt_SaveProfile
#define ChangePassword ProfMgmt_ChangePassword
#define put_ProfileOpenHostWildCard put_ProfMgmt_ProfileOpenHostWildCard
#define get_AddApplicationIfItDoesNotExistFlag get_ProfMgmt_AddApplicationIfItDoesNotExistFlag
#define put_AddApplicationIfItDoesNotExistFlag put_ProfMgmt_AddApplicationIfItDoesNotExistFlag
#define get_IsUsernameEditable get_ProfMgmt_IsUsernameEditable
#define put_IsUsernameEditable put_ProfMgmt_IsUsernameEditable
#define ResetPassword ProfMgmt_ResetPassword
#define RemoveCertificates ProfMgmt_RemoveCertificates
#define get_FirstName get_ProfMgmt_FirstName
#define put_FirstName put_ProfMgmt_FirstName
#define get_LastName get_ProfMgmt_LastName
#define put_LastName put_ProfMgmt_LastName
#define get_Email get_ProfMgmt_Email
#define put_Email put_ProfMgmt_Email

#include "profmgmt.h"

#undef get_ReadOKDomains
#undef put_ReadOKDomains
#undef get_WriteOKDomains
#undef put_WriteOKDomains
#undef get_PasswdQuality
#undef put_PasswdQuality
#undef get_PasswdLength
#undef put_PasswdLength
#undef get_PasswdTimeOut
#undef put_PasswdTimeOut
#undef get_PasswdLockOutTries
#undef put_PasswdLockOutTries
#undef get_PasswdUnLockPeriod
#undef put_PasswdUnLockPeriod
#undef get_ProfileName
#undef put_ProfileName
#undef put_Password
#undef get_SaveLocal
#undef put_SaveLocal
#undef get_RoamProfile
#undef put_RoamProfile
#undef get_OpenProfFlags
#undef put_OpenProfFlags
#undef OpenProfile
#undef CloseProfile
#undef SaveProfile
#undef ChangePassword
#undef put_ProfileOpenHostWildCard
#undef get_AddApplicationIfItDoesNotExistFlag
#undef put_AddApplicationIfItDoesNotExistFlag
#undef get_IsUsernameEditable
#undef put_IsUsernameEditable
#undef ResetPassword
#undef RemoveCertificates
#undef get_FirstName
#undef put_FirstName
#undef get_LastName
#undef put_LastName
#undef get_Email
#undef put_Email
