#ifndef _VS_PTA_DEFINES_
#define _VS_PTA_DEFINES_


/******** DATASTRUCTURE IDS *******/
#define ID_SRCHCRIT				0x1000
#define ID_UIPREF				0x1001
#define ID_CERTIDENTIFIER		0x1002

/****** MAXIMUM SIZES ***/
#define MAX_ERR_DESC_SIZE		1024
#define MAX_RES_STRING_SIZE		1024

/****** ENVIRONMENT CHECK CODES ****/
#define CHECK_INIT	0x0001 //First bit set
#define CHECK_PROF	0x0002 //Second bit set
#define CHECK_SELID	0x0004 //Third bit set
#define CHECK_CAPI_MODE 0x0008 //Fourth bit set
#define CHECK_NONCAPI_MODE 0x00010 //Fifth bit set

/****** CONSTANT STRINGS ********/
#define PTA_PROF_PATH "Program Files\\VeriSign\\PTA\\"
#define PTA_PROF_EXT ".pta"

/******	TPM MODE **********/
#define	PTA_NO_TPM_MOEE			0
#define	PTA_TPM_MODE			1


/***** WIZARD AND UI CONSTANTS ****/ 
//Masks
	// Sasi 05/02/2003
	// Increased number of bits used for operations from 12 to 16. Bits 9 to 24 will be
	// used for operations and bits 25 to 28 will be used for wizards
#define WIZARD_BITS 0x0F000000
#define OPERATION_BITS 0x00FFFF00
#define FLAG_BITS 0x000000FF

//Operations
#define INTRO_BASE 0x00000100
#define OPENPROF_BASE 0x00000200
#define SELID_BASE	0x00000400
#define SIGNMSG_BASE 0x00000800

	// Sasi 05/02/2003
	// Modified operation bit for CREATECERTREQ_BASE to accomodate new operations. 
	// The final operation should always have the value greater than the values of 
	// other intermediate/dependent operations performed. For example CREATECERTREQ_BASE 
	// should always be greater than OPENPROF_BASE or CREATESECRET_BASE. The checks that 
	// we do to find out the operation some how depend on this.
#define CREATECERTREQ_BASE 0x00400000  
#define INSTALLCERT_BASE 0x00002000
#define SETCERTPREF_BASE 0x00004000
#define GETCERTPREF_BASE 0x00008000
#define CHANGEPASSWD_BASE 0x00010000
#define IMPORTP12_BASE 0x00020000
#define EXPORTP12_BASE 0x00040000
#define EXPORTPROFILE_BASE 0x00080000
#define IMPORTPROFILE_BASE 0x00081000
#define CREATEPASSWD_BASE 0x00082000
#define ENTERPASSWD_BASE 0x00084000
#define CREATESECRET_BASE 0x00001000
#define GETSECRETQUESTION_BASE 0x00100000
#define RESETPASSWD_BASE 0x00200000
#define REMOVECERTIFICATES_BASE 0x00800000

//Wizards
	// Sasi 05/02/2003
	// Moved values for all wizard bases to 4 bits left since we are using
	// bits 21 to 24 also for operations
#define SIGN_WIZARD_BASE 0x01000000
#define LOGIN_WIZARD_BASE 0x02000000
#define CREATE_WIZARD_BASE 0x03000000
#define IMPORTP12_WIZARD_BASE 0x04000000
#define EXPORTP12_WIZARD_BASE 0x05000000
#define EXPORTPROFILE_WIZARD_BASE 0x06000000
#define IMPORTPROFILE_WIZARD_BASE 0x07000000
#define NO_WIZARD_BASE 0x00000000

//Operation Flags
#define OPEN_BASE	0x0010
#define CREATE_BASE 0x0020
#define DELETE_BASE 0x0040

#define ONLY_BASE 0x0001
#define ALWAYS_BASE 0x0002
#define TRUNC_BASE 0x0003
#define OR_BASE	0x0003
#define RECREATE_BASE 0x0001

#define OPENPROF_OPEN_BASE (OPENPROF_BASE | OPEN_BASE)
#define OPENPROF_CREATE_BASE (OPENPROF_BASE | CREATE_BASE)
#define OPENPROF_DELETE_BASE (OPENPROF_BASE | DELETE_BASE)

#define OPENPROF_CREATE_ONLY (OPENPROF_BASE | CREATE_BASE | ONLY_BASE)
#define OPENPROF_CREATE_ALWAYS (OPENPROF_BASE | CREATE_BASE | ALWAYS_BASE)
#define OPENPROF_CREATE_OR_OPEN (OPENPROF_BASE | CREATE_BASE | OR_BASE)

#define OPENPROF_OPEN_ONLY (OPENPROF_BASE | OPEN_BASE| ONLY_BASE)
#define OPENPROF_OPEN_ALWAYS  (OPENPROF_BASE | OPEN_BASE | ALWAYS_BASE )
#define OPENPROF_OPEN_TRUNC	  (OPENPROF_BASE | OPEN_BASE | TRUNC_BASE )

#define OPENPROF_DELETE_RECREATE (OPENPROF_BASE | DELETE_BASE | RECREATE_BASE)

#define	CREATE_APP_IF_NOT_EXIST	0x0008

/****** UI Messages ***/
#define OPEN_PROF_DOES_NOT_EXIST 0x00000103
#define OPEN_PROF_CREATE 0x00000104

#define CREATE_PROF_DELETE 0x00000202
#define CREATE_PROF_OPEN 0x00000203
#define CREATE_PROF_EXISTS 0x00000204

#define INSTALLCERT_PROFILE_NOT_CORRECT 0x00000301

#define SHOW_SET_MSG 0x00000401

#define PATH_DOESNOT_EXIST 0x00000501
#define FILE_EXISTS 0x00000502
#define	INVALID_PATH 0x00000503

#define PASSWORD_NOPASSWDREQD 0x00002001
#define PASSWORD_LESSTHANMINLENGTH 0x00002002
#define PASSWORD_NOTNUMERICONLY 0x00002003
#define PASSWORD_INVALIDCHARS 0x00002004
#define PASSWORD_LESSTHANMINNOOFNUM 0x00002005
#define PASSWORD_NONUMATBEGIN 0x00002006
#define PASSWORD_NONUMATEND 0x00002007
#define PASSWORD_PASSWDREQD 0x00002008
#define PASSWORD_CONFIRM_NO_MATCH 0x00001068
#define PASSWORD_INVALIDPASSWD 0x00002000		

/****** POSITION OF UI IN WIZARD ***/
#define POS_FIRST 1
#define POS_MIDDLE 2
#define POS_LAST_PREV_SEL 3
#define POS_SOLO 4
#define POS_MIDDLE_PREV_OPEN 5
#define POS_MIDDLE_PREV_CREATE 6
#define POS_LAST_PREV_OPEN 7
#define POS_LAST_PREV_CREATE 8
#define POS_LAST_PREV_INTRO 9
#define POS_MIDDLE_PREV_INTRO 10
#define	POS_LAST_PREV_GETSECRETQUESTION 11	// new UI position to go back to Get Profile dialog from Reset Password dialog - Sasi 05/02/2003
#define POS_UNKNOWN 16

/***** PASSWORD USAGE FLAGS ****/
#define DONOT_USE_PASSWORD 0x10
#define NO_PASSWORD 0x00

/***** PASSWORD QUALITY CONSTANTS ***/
#define PASSWDQUAL_PASSWDTYPE_BASE 0xF000
#define PASSWDQUAL_NOOFNUM_BASE 0x0F00
#define PASSWDQUAL_POSOFNUM_BASE 0x00F0

#define PASSWDQUAL_REQUIRENOPASS 0x0000
#define PASSWDQUAL_OPTIONALPASS 0x1000 //Same as any password with minimum length 0
#define PASSWDQUAL_ANYPASSWDOK 0x2000
#define PASSWDQUAL_NUMERICONLY 0x3000
#define PASSWDQUAL_ALPHANUMERIC 0x4000

#define PASSWDQUAL_ALPHANUMERIC_NOPOSREQS 0x0000
#define PASSWDQUAL_ALPHANUMERIC_NUMNOTATBEGIN 0x0010
#define PASSWDQUAL_ALPHANUMERIC_NUMNOTATEND 0x0020
#define PASSWDQUAL_ALPHANUMERIC_NUMNOTATBEGINEND 0x0030

#define PASSWDLENGTH_DEF_MIN 6
#define PASSWDTIMEOUT_DEF 32767
#define PASSWDLOCKOUTTRIES_DEF 3
#define PASSWDUNLOCKPERIOD_DEF 15

/***** FONTS IDENTIFIER ****/
#define FONTS_CUSTOM 0x01
#define FONTS_DEFAULT 0x02


/****** DIALOG BOX DEFINES ****/
#define DLGSIZE_CX ((int)(400.0*lXMult))
#define DLGSIZE_SMALL_CX ((int)(400.0*lXMult))
#define DLGSIZE_SMALL_CY ((int)(330.0*lYMult))
#define DLGSIZE_LARGE_CX ((int)(400.0*lXMult))
#define DLGSIZE_LARGE_CY ((int)(420.0*lYMult))
#define DLGSIZE_CREATEPROF_CY ((int)(275.0*lYMult))
#define DLG_HEADER_SIZE ((int)(34.0*lYMult))
#define DLG_FOOTER_SIZE ((int)(52.0*lYMult))

#define WIZARD_TITLE_FONT_SIZE 20
#define UI_TITLE_FONT_SIZE 13
#define UI_TEXT_FONT_SIZE 13
#define UI_BTN_FONT_SIZE 14
#define CERT_INFO_FONT_SIZE 16
#define CERT_VALIDITYLBL_FONT_SIZE 10
#define CERT_INFO_FONT_NAME "Courier"
#define CERT_VALIDITYLBL_FONT_NAME "Arial"

#define HEADER_RIGHT_MARGIN ((int)(10.0*lXMult))
#define HEADER_LEFT_MARGIN ((int)(10.0*lXMult))
#define HEADER_TOPBTM_MARGIN ((int)(2.0*lXMult))
#define BITMAP_MAX_CX ((int)(200.0*lXMult))
#define BITMAP_MAX_CY ((int)(42.0*lXMult))

#define MAX_CLASSNAME 16

#define BTN_RIGHT_MARGIN ((int)(3.0*lXMult))
#define BTN_LEFT_MARGIN ((int)(2.0*lXMult))
#define BTN1_RGN_X ((int)(120.0*lXMult))
#define BTN_MIN_CX ((int)(65.0*lXMult))
#define BTN_MIN_CY ((int)(22.0*lYMult))
#define BTN_MAX_CX ((int)(100.0*lXMult))
#define BTN_MAX_CY ((int)(32.0*lYMult))
#define BTN_LEFTRIGHTMARGINS ((int)(10.0*lXMult))
#define BTN_TOPBTMMARGINS ((int)(6.0*lYMult))

#define UITITLE_LEFT_MARGIN (HEADER_LEFT_MARGIN + ((int)(5.0*lXMult)))
#define UITITLE_RIGHT_MARGIN HEADER_RIGHT_MARGIN
#define UITITLE_MAX_X (DLGSIZE_CX-UITITLE_LEFT_MARGIN-UITITLE_RIGHT_MARGIN)
#define UILABEL_SPACE ((int)(110.0*lXMult))
#define EDIT_SPACE ((int)(10.0*lXMult))

#define UITEXT_LEFT_MARGIN UITITLE_LEFT_MARGIN
#define UITEXT_RIGHT_MARGIN UITITLE_RIGHT_MARGIN
#define UITEXT_MAX_X (DLGSIZE_CX-UITEXT_LEFT_MARGIN-UITEXT_RIGHT_MARGIN)

#define CREATESECRET_SECQUES_EDIT_SIZE ((int)(150.0*lXMult))
#define CREATESECRET_SECANSWER_EDIT_SIZE ((int)(150.0*lXMult))
#define CREATEPROF_PROFNAME_EDIT_SIZE ((int)(150.0*lXMult))
#define CREATEPASSWD_NEWPASSWORD_EDIT_SIZE ((int)(150.0*lXMult))
#define CREATEPASSWD_CNFRMPASSWORD_EDIT_SIZE ((int)(150.0*lXMult))
#define ENTERPASSWD_THEPASSWORD_EDIT_SIZE ((int)(150.0*lXMult))
#define CHNGPASSWD_OLDPASSWD_EDIT_SIZE ((int)(150.0*lXMult))
#define EDIT_TOPBTM_MARGINS ((int)(9.0*lYMult))
#define EDIT_MIN_CY ((int)(22.0*lYMult))
#define EDIT_MAX_CY ((int)(32.0*lYMult))
#define CREATEPROF_PASSWORD_EDIT_SIZE ((int)(150.0*lXMult))
#define CREATEPROF_CNFRMPASSWORD_EDIT_SIZE ((int)(150.0*lXMult))
#define UI_LEFT_MARGIN ((int)(35.0*lXMult))
#define DLGSIZE_OPENPROF_CY ((int)(250.0*lYMult))
#define EDIT_RDONLY_MAX_CY ((int)(355.0*lYMult))
#define EDIT_RDONLY_TOPBTM_MARGINS ((int)(13.0*lYMult))
#define CERT_WIDTH ((int)(310.0*lXMult))
#define CERT_HEIGHT ((int)(180.0*lYMult))
#define CERT_LEFT_MARGIN ((int)(20.0*lXMult))
#define CERT_ARC_SIZE ((int)(30.0*lXMult))
#define CERT_INFO_SPACE ((int)(60.0*lYMult))
#define CERT_LOGO_LEFT_MARGIN ((int)(9.0*lXMult))
#define CERT_LOGO_TOP_MARGIN ((int)(9.0*lYMult))

#define CERT_FRNDLYNAME_MAX_X (CERT_WIDTH/((2.0*lXMult)))
#define CERT_FRNDLYNAME_RIGHT_MARGIN ((int)(15.0*lXMult))
#define CERT_FRNDLYNAME_TOP_MARGIN ((int)(15.0*lYMult))

#define CERT_COMMONNAME_LEFT_MARGIN (CERT_LEFT_MARGIN + ((int)(15.0*lXMult)))
#define CERT_COMMONNAME_RIGHT_MARGIN CERT_FRNDLYNAME_RIGHT_MARGIN
#define CERT_COMMONNAME_MAX_X (CERT_WIDTH - CERT_COMMONNAME_LEFT_MARGIN - CERT_COMMONNAME_RIGHT_MARGIN)
#define CERT_COMMONNAME_INTERCHARSPACE ((int)(3.0*lXMult))

#define CERT_VALIDITYLBL_MAX_X ((int)(70.0*lXMult))
#define CERT_VALIDITYLBL_MAX_Y ((int)(12.0*lYMult))
#define CERT_VALIDITYLBL_LEFT_MARGIN (CERT_LEFT_MARGIN+((int)(30.0*lXMult)))
#define CERT_VALIDITYLBL_INTERCHARSPACE ((int)(1.0*lXMult))

#define CERT_VALIDITY_LEFT_MARGIN (CERT_LEFT_MARGIN + ((int)(15.0*lXMult)))
#define CERT_VALIDITY_RIGHT_MARGIN CERT_FRNDLYNAME_RIGHT_MARGIN
#define CERT_VALIDITY_MAX_X (CERT_WIDTH - CERT_VALIDITY_LEFT_MARGIN - CERT_VALIDITY_RIGHT_MARGIN)

#define CERTLIST_RIGHT_MARGIN ((int)(15.0*lXMult))
#define CERTLIST_LEFT_MARGIN ((int)(15.0*lXMult))
#define CERTLIST_WIDTH (DLGSIZE_CX-CERTLIST_LEFT_MARGIN-CERTLIST_RIGHT_MARGIN)

#define CERTLIST_COMMONNAME_COL_WIDTH ((int)(115.0*lXMult))
#define CERTLIST_FRNDLYNAME_COL_WIDTH ((int)(115.0*lXMult))
#define CERTLIST_EXPIRES_COL_WIDTH ((int)(75.0*lXMult))

#define CHKBOX_LEFT_MARGIN ((int)(15.0*lXMult))
#define CHKBOX_RIGHT_MARGIN ((int)(15.0*lXMult))
#define CHKBOX_MAX_X (DLGSIZE_CX-CHKBOX_LEFT_MARGIN-CHKBOX_RIGHT_MARGIN )
#define CHKBOX_LEFTRIGHTMARGINS ((int)(15.0*lXMult))

#define VRSNLOGO_X ((int)(90.0*lXMult))
#define VRSNLOGO_Y ((int)(38.0*lYMult))
#define VRSNLOGO_RGN_X ((int)(5.0*lXMult))

#define OTHER_PROFNAME_STRING "Other..enter user name."

/***** ANCHOR DEFINES ***/
#define RGN_ANCH_TOPLEFT 1
#define RGN_ANCH_TOPRIGHT 2
#define RGN_ANCH_BOTTOMLEFT 3
#define RGN_ANCH_BOTTOMRIGHT 4
#define FLD_XANCH_LEFT 5
#define FLD_XANCH_RIGHT 6
#define FLD_XANCH_MIDDLE 7
#define FLD_YANCH_TOP 8
#define FLD_YANCH_BOTTOM 9
#define FLD_YANCH_MIDDLE 10

/*** VIRTUAL SMART CARD DEFINES ***/
#define DUMMY_HOSTNAME "VeriSign, Inc."
#define PTA_APPCTXT_NAME "VeriSign Personal Trust Agent"
#define PTA_ENC_APPCTXT_NAME "VeriSign Encrypted Personal Trust Agent"
#define MAX_LOCKOUT_TRIES_NAME "Max_LockOut_Tries"
#define UNLOCK_PERIOD_NAME "Unlock_Period"
#define BEGINWRITE_BLOCK_PERIOD 10
#define BEGINREAD_BLOCK_PERIOD 10
#define INVALID_TRIES_NAME "Invalid_Tries"
#define LAST_INVALIDTRY_NAME "Last_Invalid_Try"
#define TIMEOUT_PERIOD_NAME "Timeout_Period"

/*** Key Attribs ***/
#define KEYSIZE_BASE 0xFFFF0000
#define EXPORTABLE_BASE 0x0000FF00
#define KEYTYPE_BASE 0x000000FF

#define KEY_EXPORTABLE 0x00000000
#define KEY_NOTEXPORTABLE 0x00000100
#define KEY_SIGNATURE 0x00000002
#define KEY_ENCRYPTION 0x00000001


/*** Key States ***/
#define KEY_PENDING 0x00000000
#define KEY_PRESENT 0x00000001
#define KEY_ABSENT	0x00000002
#define KEY_INVALID	0x00000004

/*** Hash Algorithms ***/
#define SCRIPT_HASH_MD2 2
#define  SCRIPT_HASH_MD5 3
#define SCRIPT_HASH_SHA1 4
#define SCRIPT_HASH_MD2_WITHAUTHATTR 5
#define SCRIPT_HASH_MD5_WITHAUTHATTR 6
#define SCRIPT_HASH_SHA1_WITHAUTHATTR 7

/**** REGISTRY KEYS ***/
#define PENDING_CERTS_REG_KEY "SOFTWARE\\VeriSign, Inc.\\Pta3\\PendingCerts\\"
#define VS_CRYPTO_REG_KEY "SOFTWARE\\VeriSign, Inc.\\Pta3\\Cryptography\\"
#define PROFILE_NAME "Profile"
#define PROFILE_TYPE "ProfileType"
#define CLIENT_INFO	"ClientInfo"
#define	CLIENT_INFO_LEN	8192
#define CLIENT_INFO_SIG "ClientInfoSig"
#define SMARTCARD_NAME "SmartCard"
#define KEYTYPE_NAME "KeyType"
#define CERTPREF_REG_KEY "SOFTWARE\\Verisign, Inc.\\Pta3\\CertPrefs\\"
#define APPREF_REG_KEY "SOFTWARE\\Verisign, Inc.\\Pta3\\AppPrefs\\"

/*** CSP Related Defines ***/
#define CSP_NAME "VeriSign Personal Trust Agent (PTA)"
#define CSP_INSTALL_TYPE 1
#define CSP_SIGNATURE_FILE "vscspsign"

/*** EQUALITY DEFINES ***/
#define VS_LESS 0
#define VS_EQ 1
#define VS_GREATER 2

/*** CERTIFICATE PREFERENCES NAMES ***/
#define CERTPREF_FRNDLYNAME "FrndlyName"
#define CERTPREF_DISPSTRING "DispString"
#define CERTPREF_LOGOURL "LogoUrl"
#define CERTPREF_TEXTUREURL "TextureUrl"
#define CERTPREF_RENEWED "Renewed"
#define CERTPREF_STORE "CertStore"
#define CERTPREF_CONTAINER_NAME "ContainerName"

/*** APPLICATION PREFERENCE NAMES ***/
#define APPPREF_DEFCERTISSDN "DefCertIssDN"
#define APPPREF_DEFCERTSERNUM "DefCertSerNum"

/*** SIGNATURE DEFINES ***/
#define PRECANNED_HEADER "The following data is for authentication purpose only."

/*** Authentication dll defines ***/
#define AUTHDLL_OPENPROF 0x0001
#define AUTHDLL_CREATEPROF 0x0002
#define AUTHDLL_CHANGEPASSWD 0x0003
// XXX need defines for createpasswd and enterpasswd
#define AUTHDLL_UNLOCK 0x0004

//
//	Anand		Apr 13, 2000	Start
//
#define		USER_NAME_ENDING								"'s "
#define		PROFILE_NAME_ENDING								" Profile.pta"
#define		HOMEDRIVEATH_ENV								"%HOMEDRIVE%%HOMEPATH%"
#define		VERISIGN_PTA_PROFILE_PATH						"Program Files\\VeriSign\\PTA\\"

//#define		PROFILE_EXTENSON								"pta"
//
//	Anand		Apr 13, 2000	End
//


//#define		OS_VER_WIN_2000						2000
//#define		WIN_2000_VERISIGN_PTA_PROFILE_PATH				"VeriSign\\PTA\\"
#define		WIN_NT_OR_WIN_2000_VERISIGN_PTA_PROFILE_PATH		"VeriSign\\PTA\\"
#define		PATH_UPGRADE						"SOFTWARE\\Verisign, Inc.\\Pta3\\ProfilePath"



#define MY_ENCODING_TYPE (PKCS_7_ASN_ENCODING | X509_ASN_ENCODING)


//
//	Anand	Dec 13, 2000		Start
//
#define		NO_DECRYPT_UI						0
#define		DECRYPT_NOTIFICATION				1
#define		DECRYPT_FULL_DISCLOSURE				2	//	NOT SUPPORTED
//
//	Anand	Dec 13, 2000		End
//


// Wasim	Apr 24, 2002, flags for export profile
#define		EXPORT_CERTS	0x1
#define		EXPORT_KEYS		0x2
#define		EXPORT_APP_PREF	0x4

#define		CERTIFICATE_STRING	"Certificates"
#define		PRIVATEKEY_STRING	"PrivateKeys"
#define		INFORMATION_BLOB	"InformationBlobs"


/***** LANGUAGE IDENTIFIERS *****/
#define VS_LANG_LANGUAGE_NEUTRAL 0x0000 
#define VS_LANG_PROCESS_DEFAULT_LANGUAGE 0x0400 
#define VS_LANG_AFRIKAANS 0x0436 
#define VS_LANG_ALBANIAN 0x041c 
#define VS_LANG_ARABIC_SAUDI ARABIA 0x0401 
#define VS_LANG_ARABIC_IRAQ 0x0801 
#define VS_LANG_ARABIC_EGYPT 0x0c01 
#define VS_LANG_ARABIC_LIBYA 0x1001 
#define VS_LANG_ARABIC_ALGERIA 0x1401 
#define VS_LANG_ARABIC_MOROCCO 0x1801 
#define VS_LANG_ARABIC_TUNISIA 0x1c01 
#define VS_LANG_ARABIC_OMAN 0x2001 
#define VS_LANG_ARABIC_YEMEN 0x2401 
#define VS_LANG_ARABIC_SYRIA 0x2801 
#define VS_LANG_ARABIC_JORDAN 0x2c01 
#define VS_LANG_ARABIC_LEBANON 0x3001 
#define VS_LANG_ARABIC_KUWAIT 0x3401 
#define VS_LANG_ARABIC_UAE 0x3801 
#define VS_LANG_ARABIC_BAHRAIN 0x3c01 
#define VS_LANG_ARABIC_QATAR 0x4001 
#define VS_LANG_AZERI_LATIN 0x042c 
#define VS_LANG_AZERI_CYRILLIC 0x082c 
#define VS_LANG_BASQUE 0x042d  
#define VS_LANG_BELARUSSIAN 0x0423  
#define VS_LANG_BENGALI 0x0445 
#define VS_LANG_BULGARIAN 0x0402  
#define VS_LANG_BURMESE 0x0455  
#define VS_LANG_CATALAN 0x0403  
#define VS_LANG_CHINESE_TRADITIONAL 0x0404 
#define VS_LANG_CHINESE_SIMPLIFIED 0x0804 
#define VS_LANG_CHINESE_HONGKONG 0x0c04 
#define VS_LANG_CHINESE_SINGAPORE 0x1004 
#define VS_LANG_CHINESE_MACAU 0x1404 
#define VS_LANG_CROATIAN 0x041a  
#define VS_LANG_CZECH 0x0405  
#define VS_LANG_DANISH 0x0406  
#define VS_LANG_DUTCH_NETHERLANDS 0x0413 
#define VS_LANG_DUTCH_BELGIUM 0x0813 
#define VS_LANG_ENGLISH_US 0x0409 
#define VS_LANG_ENGLISH_UK 0x0809 
#define VS_LANG_ENGLISH_AUSTRALIAN 0x0c09 
#define VS_LANG_ENGLISH_CANADIAN 0x1009 
#define VS_LANG_ENGLISH_NEW_ENGLAND 0x1409 
#define VS_LANG_ENGLISH_IRELAND 0x1809 
#define VS_LANG_ENGLISH_SOUTH AFRICA 0x1c09 
#define VS_LANG_ENGLISH_JAMAICA 0x2009 
#define VS_LANG_ENGLISH_CARIBBEAN 0x2409 
#define VS_LANG_ENGLISH_BELIZE 0x2809 
#define VS_LANG_ENGLISH_TRINIDAD 0x2c09 
#define VS_LANG_ENGLISH_ZIMBABWE 0x3009 
#define VS_LANG_ENGLISH_PHILIPPINES 0x3409 
#define VS_LANG_ESTONIAN 0x0425 
#define VS_LANG_FAEROESE 0x0438 
#define VS_LANG_FARSI 0x0429 
#define VS_LANG_FINNISH 0x040b 
#define VS_LANG_FRENCH_STANDARD 0x040c 
#define VS_LANG_FRENCH_BELGIAN 0x080c 
#define VS_LANG_FRENCH_CANADIAN 0x0c0c 
#define VS_LANG_FRENCH_SWITZERLAND 0x100c 
#define VS_LANG_FRENCH_LUXEMBOURG 0x140c 
#define VS_LANG_FRENCH_MONACO 0x180c 
#define VS_LANG_GEORGIAN 0x0437 
#define VS_LANG_GERMAN_STANDARD 0x0407 
#define VS_LANG_GERMAN_SWITZERLAND 0x0807 
#define VS_LANG_GERMAN_AUSTRIA 0x0c07 
#define VS_LANG_GERMAN_LUXEMBOURG 0x1007 
#define VS_LANG_GERMAN_LIECHTENSTEIN 0x1407 
#define VS_LANG_GREEK 0x0408  
#define VS_LANG_GUJARATI 0x0447 
#define VS_LANG_HEBREW 0x040d  
#define VS_LANG_HINDI 0x0439 
#define VS_LANG_HUNGARIAN 0x040e  
#define VS_LANG_ICELANDIC 0x040f  
#define VS_LANG_INDONESIAN 0x0421  
#define VS_LANG_ITALIAN_STANDARD 0x0410 
#define VS_LANG_ITALIAN_SWITZERLAND 0x0810 
#define VS_LANG_JAPANESE 0x0411  
#define VS_LANG_KANNADA 0x044b 
#define VS_LANG_KASHMIRI_INDIA 0x0860 
#define VS_LANG_KAZAKH 0x043f  
#define VS_LANG_KONKANI 0x0457 
#define VS_LANG_KOREAN 0x0412  
#define VS_LANG_KOREAN_JOHAB 0x0812 
#define VS_LANG_LATVIAN 0x0426  
#define VS_LANG_LITHUANIAN 0x0427  
#define VS_LANG_LITHUANIAN_CLASSIC 0x0827 
#define VS_LANG_MACEDONIAN 0x042f  
#define VS_LANG_MALAY_MALAYSIAN 0x043e 
#define VS_LANG_MALAY_BD 0x083e 
#define VS_LANG_MALAYALAM 0x044c 
#define VS_LANG_MANIPURI 0x0458  
#define VS_LANG_MARATHI 0x044e 
#define VS_LANG_NEPALI  0x0861 
#define VS_LANG_NORWEGIAN_BOKMAL 0x0414 
#define VS_LANG_NORWEGIAN_NYNORSK 0x0814 
#define VS_LANG_ORIYA 0x0448 
#define VS_LANG_POLISH 0x0415  
#define VS_LANG_PORTUGUESE_BRAZIL 0x0416 
#define VS_LANG_PORTUGUESE_STANDARD 0x0816 
#define VS_LANG_PUNJABI 0x0446 
#define VS_LANG_ROMANIAN 0x0418  
#define VS_LANG_RUSSIAN 0x0419  
#define VS_LANG_SANSKRIT 0x044f 
#define VS_LANG_SERBIAN_CYRILLIC 0x0c1a 
#define VS_LANG_SERBIAN_LATIN 0x081a 
#define VS_LANG_SINDHI 0x0459  
#define VS_LANG_SLOVAK 0x041b  
#define VS_LANG_SLOVENIAN 0x0424  
#define VS_LANG_SPANISH_TRADITIONAL 0x040a 
#define VS_LANG_SPANISH_MEXICAN 0x080a 
#define VS_LANG_SPANISH_MODERNPORT 0x0c0a 
#define VS_LANG_SPANISH_GUATEMALA 0x100a 
#define VS_LANG_SPANISH_COSTA_RICA 0x140a 
#define VS_LANG_SPANISH_PANAMA 0x180a 
#define VS_LANG_SPANISH_DOMINICAN_REPUBLIC 0x1c0a 
#define VS_LANG_SPANISH_VENEZUELA 0x200a 
#define VS_LANG_SPANISH_COLOMBIA 0x240a 
#define VS_LANG_SPANISH_PERU 0x280a 
#define VS_LANG_SPANISH_ARGENTINA 0x2c0a 
#define VS_LANG_SPANISH_ECUADOR 0x300a 
#define VS_LANG_SPANISH_CHILE 0x340a 
#define VS_LANG_SPANISH_URUGUAY 0x380a 
#define VS_LANG_SPANISH_PARAGUAY 0x3c0a 
#define VS_LANG_SPANISH_BOLIVIA 0x400a 
#define VS_LANG_SPANISH_ELSALVADOR 0x440a 
#define VS_LANG_SPANISH_HONDURAS 0x480a 
#define VS_LANG_SPANISH_NICARAGUA 0x4c0a 
#define VS_LANG_SPANISH_PUERTORICO 0x500a 
#define VS_LANG_SUTU 0x0430  
#define VS_LANG_SWAHILI_KENYA 0x0441 
#define VS_LANG_SWEDISH 0x041d  
#define VS_LANG_SWEDISH_FINLAND 0x081d 
#define VS_LANG_TAMIL 0x0449 
#define VS_LANG_TATAR_TATARSTAN 0x0444 
#define VS_LANG_TELUGU 0x044a 
#define VS_LANG_THAI 0x041e  
#define VS_LANG_TURKISH 0x041f  
#define VS_LANG_UKRAINIAN 0x0422  
#define VS_LANG_URDU_PAKISTAN 0x0420 
#define VS_LANG_URDU_INDIA 0x0820 
#define VS_LANG_UZBEK_LATIN 0x0443 
#define VS_LANG_UZBEK_CYRILLIC 0x0843 
#define VS_LANG_VIETNAMESE 0x042a  

#endif