#	GNUmakefile 
#       Developed by Abhay Ranade
#		Modified  by Narinder
#	$Id: GNUmakefile,v 1.1.2.2 2001/12/24 18:38:55 ajayaram Exp $
#

ECAS_HOME = ../../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


ifeq ($(CISCO), 1)
SPECIAL_sparc_DIRS = cisco
endif

SUBDIRS = vssc vsscsetup


include $(ECAS_RULES_DIR)/directory.cfg

