#	GNUmakefile 
#       Developed by Siddharth Bajaj
#	$Id: GNUmakefile,v 1.1.4.1 2001/06/05 02:01:33 sbajaj Exp $
#

ECAS_HOME = ../../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


ifeq ($(CISCO), 1)
SPECIAL_sparc_DIRS = cisco
endif

SUBDIRS = npptav3 N6PTA


include $(ECAS_RULES_DIR)/directory.cfg

