//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by vsctl.rc
//
#define IDS_EXT_TITLE                   1
#define IDS_FILE_NAME                   2
#define IDS_ORIG_LOCATION               3
#define IDB_HELP                        3
#define ID_HELP                         3
#define IDS_DATE_ENCRYPT                4
#define ID_NO                           4
#define ID_BROWSE                       4
#define ID_IMPORT                       4
#define IDS_FILE_TYPE                   5
#define ID_CREATE                       5
#define IDS_FILE_SIZE                   6
#define IDS_NEW_SAFE                    7
#define IDS_DECRYPT                     8
#define IDS_DECRYPT_ALL                 9
#define IDS_PROPERTIES                  10
#define IDS_VIEW_LARGE                  11
#define IDS_VIEW_SMALL                  12
#define IDS_VIEW_LIST                   13
#define IDS_VIEW_DETAILS                14
#define IDS_VIEW                        15
#define IDS_ARRANGE_ICONS               16
#define IDS_BY_NAME                     17
#define IDS_BY_ORIGIN                   18
#define IDS_BY_DATE_ENCRYPT             19
#define IDS_BY_TYPE                     20
#define IDS_BY_SIZE                     21
#define IDS_PASTE                       22
#define IDS_EXPLORE                     23
#define IDS_OPEN                        24
#define IDS_RESTORE                     25
#define IDS_SELECT_ALL                  26
#define IDS_INVERT_SELECTION            27
#define IDS_REMOVE_FILE                 28
#define IDS_WARNING                     29
#define IDS_REPLACE_FILE                30
#define IDS_REPLACE_FILE2               31
#define IDS_REPLACE_FOLDER              32
#define IDS_REPLACE_FOLDER2             33
#define IDS_ENCRYPT                     34
#define IDS_DELETE                      35
#define IDS_CURR_LOCATION               36
#define IDS_CLOSE                       37
#define IDS_CLEAR                       38
#define IDS_HIDE                        39
#define IDS_ENCRYPTED                   40
#define IDS_DECRYPTED                   41
#define IDS_VSSAFE                      42
#define IDS_ENCRYPT_FILE                43
#define IDS_DECRYPT_VERIFY              44
#define IDS_DATE_DECRYPT                45
#define IDS_REMOVAL_MESSAGE             46
#define IDB_LOG_OUT                     47
#define IDB_LOG_IN                      48
#define IDS_PROJNAME                    100
#define IDS_BY_DATE_DECRYPT             101
#define IDR_VSCTRL                      102
#define IDS_ID_REM_ERR                  102
#define IDD_NEW_SAFE                    103
#define IDS_FOLDER_OVERWRITE            103
#define IDS_FILE_FOLDER_PRESENT         104
#define IDD_ADVANCED_OPTS               105
#define IDS_FILE_OVERWRITE              105
#define IDD_SAFE_PROP                   106
#define IDS_LOCK_SAFE                   106
#define IDS_PASSWD_PROMPT               107
#define IDS_PASSWD_UNLOCK               108
#define IDS_PASSWD_TIMEOUT              109
#define IDD_FILE_PROP                   110
#define IDS_LOCKSAFE                    110
#define IDS_RESTORE_PASSWORD            110
#define IDD_FILE_DECRYPT                111
#define IDS_LOG_IN                      111
#define IDS_UNLOCK_SAFE                 111
#define IDS_LOG_OUT                     112
#define IDS_BACKUP                      113
#define IDS_HELP_TOPICS                 114
#define IDR_ACCELS                      115
#define IDS_ABOUT                       115
#define IDS_ABOUT_TEXT                  116
#define IDI_SAFE                        117
#define IDS_COMMENT                     117
#define IDD_REPLACE                     118
#define IDS_INSTALL_DIGID               118
#define IDI_UNLOCK                      119
#define IDS_DELETE_PROMPT               119
#define IDS_DELETE_CONFIRM              120
#define IDS_UNINSTALL                   121
#define IDS_DECRYPT_FOLDER_ERROR        122
#define IDS_DECRYPT_FILE_ERROR          123
#define IDS_NO_MEMORY                   124
#define IDS_REG_CREATE                  125
#define IDB_ENCRYPTED                   126
#define IDS_REG_WRITE                   126
#define IDB_CLOSESAFE                   127
#define IDS_CONNECT_ERROR               127
#define IDS_NETWORK_ERROR               128
#define IDS_REG_OPEN                    129
#define IDB_VSLOGO                      130
#define IDS_POLICY_DOWNLOAD_ERR         130
#define IDD_FILE_ADVPROP                131
#define IDS_CONTINUE_POLICY             131
#define IDD_SAFE_SECURITY               132
#define IDS_SAFE_DIR_ERR                132
#define IDS_READ_FILE_ERR               133
#define IDS_ROOT_FOLDER_ERR             134
#define IDS_OS_FOLDER_ERR               135
#define IDS_OS_FILE_ERR                 136
#define IDS_FILTER_ERR                  137
#define IDS_ENCRYPT_HIDDEN              138
#define IDB_RECENTLY_DECR               139
#define IDS_ENCRYPT_SYSTEM              139
#define IDS_ENCRYPT_READONLY            140
#define IDS_ENCRYPT_TEMP                141
#define IDS_DIR_SELECT                  142
#define IDS_ENCRYPTING                  143
#define IDS_DECRYPTING                  144
#define IDI_ICON_CHECK                  145
#define IDS_ENCRYPT_LOGOFF              145
#define IDI_ICON_CROSS                  146
#define IDS_DECRYPT_LOGON               146
#define IDD_FILE_ENCRYPT_DECRYPT        147
#define IDS_NO_IDS_FOR_SAFE             147
#define IDS_PASSWD_PROP                 148
#define IDD_ENCRYPT_ERROR               149
#define IDS_PASSWD_FILE                 149
#define IDD_CERT_MGMT                   150
#define IDS_PASSWD_ENCRYPT              150
#define IDS_PASSWD_DECRYPT              151
#define IDD_MULTI_SEL                   152
#define IDS_PASSWD_TIMEOUT_PROP         152
#define IDS_PASSWD_PROMPT_TIMEOUT       152
#define IDS_PASSWD_TIMEOUT_FILE         153
#define IDI_MULTIPLE_SEL                154
#define IDS_PASSWD_TIMEOUT_ENCRYPT      154
#define IDD_FOLDER_PROP                 155
#define IDS_PASSWD_TIMEOUT_DECRYPT      155
#define IDS_FROM_TO                     156
#define IDS_VERIFY_FAIL                 157
#define IDS_DECRYPT_FAIL                158
#define IDS_TEMP_FILE_ERR               159
#define IDS_WRITE_FILE_ERR              160
#define IDS_PASSWD_FILE_ERR             161
#define IDS_POLICY_OPEN_ERR             162
#define IDS_POLICY_CNT_ERR              163
#define IDS_CRYPT_SERVICE_ERR           164
#define IDS_UNINSTALL_MSG               165
#define IDS_TEMP_PATH_ERR               168
#define IDS_USERNAME_ERR                169
#define IDS_COPY_FILE_ERR               170
#define IDS_POLICY_UPDATE_ERR           171
#define IDS_POLICY_WRITE_ERR            173
#define IDS_REG_READ_ERR                174
#define IDS_CRYPT_ERR                   175
#define IDS_INVALID_RESULT              176
#define IDS_DIGID_ABSENT                178
#define IDS_INVALID_USER                179
#define IDS_ENCRYPT_ID_DEL              180
#define IDS_DIR_CREATE_ERR              181
#define IDS_ENCR_CERT_ERR               182
#define IDS_SHARE_ERR                   183
#define IDS_SIGN_CERT_ERR               184
#define IDS_SIGN_ID_DEL                 185
#define IDS_SIGN_ERR                    186
#define IDS_INVALID_PASSWD              187
#define IDS_DLL_INIT_ERR                188
#define IDS_PTA_INIT_ERR                189
#define IDS_SEL_SCRNSVR                 190
#define IDS_SCRNSVR_PASSWD              191
#define IDS_ENTER_PASSWD                192
#define IDS_PASSWD_MISMATCH             193
#define IDS_SCRNSVR_ERR                 194
#define IDS_OLD_PASSWD                  195
#define IDS_ENTER_NEW_PASSWD            196
#define IDS_PASSWD_CHANGE               197
#define IDS_FROM                        198
#define IDS_TO                          199
#define IDS_RECOVERY_FILE               200
#define IDD_GENERAL                     201
#define IDS_SEL_RECOVERY_FILE           201
#define IDS_UNINSTALL_CONFIRM           202
#define IDS_RECOVERY_FILE_CREATED       203
#define IDS_IMPORT_RECOVERY_FILE        204
#define IDS_LOST_PASSWORD               205
#define IDI_ICON_OVERLAY                206
#define IDS_TOKEN_IMPORTED              206
#define IDS_NEW_PASSWD                  207
#define IDS_RECOVER_PASSWD              208
#define IDS_SELID_ERROR                 209
#define IDS_SEL_FILES                   210
#define IDS_SAFE_PROP                   211
#define IDS_ITEM_PROP                   212
#define IDS_LOCK_THE_SAFE               213
#define IDI_ICON_CLOSED_FOLDER          214
#define IDS_UNLOCK_THE_SAFE             214
#define IDD_FILTER                      215
#define IDS_CLOSE_WINDOW                215
#define IDS_RECOVER_PASSWORD            216
#define IDD_FILE_EXT                    217
#define IDS_SELECT_ALL_ITEMS            217
#define IDD_FILTER2                     218
#define IDS_INVERT_SELECT_ALL_ITEMS     218
#define IDS_RECENTLY_DECRYPTED          219
#define IDD_EXT                         220
#define IDS_VIEW_LARGE_ITEMS            220
#define IDD_PASSWD_PROMPT               221
#define IDD_PASSWD_UNLOCK               221
#define IDS_VIEW_SMALL_ITEMS            221
#define IDD_NEW_PASSWD                  222
#define IDS_VIEW_LIST_ITEMS             222
#define IDS_VIEW_DETAIL_ITEMS           223
#define IDS_HELP                        224
#define IDD_PASSWD_ENTER                225
#define IDD_PASSWD_VERIFY               225
#define IDS_HELP_ABOUT                  225
#define IDD_CHANGE_PASSWD               226
#define IDS_OPEN_ITEM                   226
#define IDD_RECOVER_PASSWD              227
#define IDS_DECRYPTOPEN_ITEMS           227
#define IDS_DECRYPT_ITEMS               228
#define IDS_ENCRYPT_ITEMS               229
#define IDS_DECRYPTVERIFY_ITEMS         230
#define IDS_EXPLORE_ITEMS               231
#define IDS_DELETE_ITEMS                232
#define IDS_VIEW_ITEMS                  233
#define IDS_ARRANGE_ITEMS               234
#define IDS_BY_NAME_ITEM                235
#define IDS_BY_TYPE_ITEM                236
#define IDS_BY_DATE_ITEM                237
#define IDS_BY_SIZE_ITEM                238
#define IDS_BY_ORIGIN_ITEM              239
#define IDS_CLEAR_ITEM                  240
#define IDS_HIDE_ITEM                   241
#define IDS_ENCRYPT_ITEM                242
#define IDS_ENCRYPT_INPLACE_ITEM        243
#define IDI_OPEN_SAFE                   244
#define IDS_DECRYPT_ITEM                244
#define IDS_MS_TO_VS                    245
#define IDS_VS_TO_MS                    246
#define IDS_DIFF_PROFILE                247
#define IDS_ENTER_SAFE_PASSWD           248
#define IDS_MS_PASSWD1                  249
#define IDS_VS_PASSWD1                  250
#define IDS_MS_PASSWD2                  251
#define IDS_MS_PASSWD3                  252
#define IDS_VS_PASSWD3                  253
#define IDS_VS_PASSWD2                  254
#define IDS_OPEN_SAFE                   255
#define IDS_APP_DATA_ERR                256
#define IDS_INVALID_PROFILE             257
#define IDS_FORGOT_PASSWD               258
#define IDS_INSTALL_DIR_ERR             259
#define IDS_DIG_SIG_ERR                 260
#define IDS_SETTINGS_READ_ERR           261
#define IDS_SETTINGS_VERF_ERR           262
#define IDS_DECRYPT_ERR                 263
#define IDS_SAFE                        264
#define IDS_SAFE_DIR_ERR_PERM           265
#define IDD_PASSWORD_IMPORT             266
#define IDS_OPEN_FET_PROFILE            266
#define IDS_DIGID_REMOVED               267
#define IDS_SAFE_DIR                    268
#define IDB_OPENSAFE                    303
#define IDB_LINE                        308
#define IDD_LOGON_OFF                   310
#define IDD_DISP_TEXT                   311
#define IDI_ICON1                       313
#define IDD_DECRYPT_ERROR               314
#define IDB_LOGOUT                      318
#define IDB_LOGIN                       319
#define IDD_RECOVER_PASSWORD            321
#define IDR_SAFEACCELS                  322
#define IDD_CHANGE_CERT                 325
#define IDE_SAFE_NAME                   1001
#define IDR_PERSONAL                    1002
#define IDR_SHARED                      1003
#define IDB_USERS                       1004
#define IDC_NETWORK                     1005
#define IDC_BUTTON_MOVE                 1006
#define IDC_BUTTON_LINK                 1008
#define IDC_LOGOFF                      1010
#define IDC_LOGON                       1011
#define IDC_ENCRYPT                     1018
#define IDC_FILE_NAME                   1020
#define IDC_FILE_TYPE                   1028
#define IDC_ORIG_SIZE                   1029
#define IDC_ENCR_SIZE                   1030
#define IDC_CREATED                     1031
#define IDC_ENCRYPTED                   1032
#define IDB_NO                          1033
#define IDB_YESTOALL                    1034
#define IDC_FOLDERNAME                  1036
#define IDC_REPLACE_TEXT                1037
#define IDC_REPLACE_TEXT2               1038
#define IDC_DECRYPT                     1040
#define IDC_COMBO_ALGO                  1055
#define IDC_ENCRYPT_ALGO                1055
#define IDC_STATIC_ENCR_ALGO            1057
#define IDC_LIST3                       1068
#define IDC_BUTTON_MORE                 1070
#define IDB_SECURITY                    1070
#define IDC_CHECK_SIGN                  1076
#define IDC_SECURITY_ENCR               1077
#define IDC_SECURITY_SIGN               1078
#define IDC_CSP                         1080
#define IDC_ISSUEDTO_ENCR               1081
#define IDC_EXPIRY_ENCR                 1082
#define IDC_ISSUEDTO_SIGN               1085
#define IDC_EXPIRY_SIGN                 1086
#define IDC_SAFE_FILES                  1087
#define IDC_SAFE_SIZE                   1088
#define IDC_SIG_STAT                    1092
#define IDB_MODIFY_ENCR                 1095
#define IDC_PROGRESS1                   1096
#define IDC_PROGRESS                    1096
#define IDB_MODIFY_SIGN                 1097
#define IDC_COPY_FROM_TO                1098
#define ID_FILECOPY_AVI                 1099
#define IDC_FROM_TO                     1104
#define ID_YES_TO_ALL                   1105
#define IDC_ERROR_TEXT                  1106
#define IDC_SECURE_DEL                  1108
#define IDB_GET_DIGID                   1111
#define IDB_RENEW_DIGID                 1112
#define IDB_RECOVER_DIGID               1113
#define IDC_HASH_ALGO                   1113
#define IDB_REVOKE_DIGID                1114
#define IDC_NO_SEL                      1114
#define IDC_MULTI_FILE_ENCRYPTED        1115
#define IDC_MULTI_SIGNED                1116
#define IDC_MULTI_ENCR_AT_LOGOFF        1117
#define IDC_MULTI_DECR_LOGON            1118
#define IDC_VALID                       1119
#define IDC_FILE_ENCRYPTED              1120
#define IDC_FILE_SIGNED                 1121
#define IDC_FILE_ENCR_AT_LOGOFF         1122
#define IDC_FILE_DECR_LOGON             1123
#define IDC_MULTI_FILE_TYPE             1124
#define IDC_MULTI_ORIG_SIZE             1125
#define IDC_MULTI_ENCR_SIZE             1126
#define IDC_FOLDER_NAME                 1127
#define IDC_FOLDER_ORIG_SIZE            1129
#define IDC_FOLDER_ENCR_SIZE            1130
#define IDC_FOLDER_TYPE                 1131
#define IDC_PROMPT                      1136
#define IDC_TEXT                        1137
#define IDC_SCREEN_SAVER                1138
#define IDB_PASSWORD                    1139
#define IDC_PASSWORD                    1140
#define IDE_WAIT                        1141
#define IDC_DISPLAY_TEXT                1142
#define IDC_FILE_FOLDER                 1143
#define IDC_LIST_EXT                    1144
#define IDC_LIST_FOLDER                 1145
#define IDC_CHECK_RO                    1147
#define IDC_CHECK_A                     1148
#define IDC_CHECK_H                     1149
#define IDC_CHECK_S                     1150
#define IDB_ADD_EXT                     1153
#define IDB_ADD_FOLDER                  1154
#define IDB_REM_EXT                     1155
#define IDL_EXT_EXCLUDE                 1155
#define IDB_REM_FOLDER                  1156
#define IDC_FILTER                      1156
#define IDB_ADD                         1158
#define IDB_REMOVE                      1159
#define IDE_EXT                         1163
#define IDE_PASSWD                      1164
#define IDE_CONFIRM_PASSWD              1166
#define IDB_ENCDEC                      1167
#define IDB_TIMEOUT                     1168
#define IDE_PASSWD_TIMEOUT              1169
#define IDC_DISP_TXT                    1171
#define IDE_PASSWORD                    1173
#define IDB_PASSWD_CHANGE               1174
#define IDE_OLD_PASSWD                  1175
#define IDE_NEW_PASSWD                  1176
#define IDC_BUTTON_INPLACE              1177
#define IDB_EXPORT                      1179
#define IDB_IMPORT                      1180
#define IDC_NEW_PASSWORD                1181
#define IDC_CONFIRM_NEW_PASSWORD        1182
#define IDC_SPIN                        1196
#define IDC_STATIC_ENCDEC               1198
#define IDC_STATIC_TIMEOUT              1199
#define IDC_STATIC_MINUTES              1200
#define IDC_MSG                         1204
#define IDC_SERIAL_SIGN                 1205
#define IDC_SERIAL_ENCRYPT              1206
#define IDC_ERROR_MSG                   1207
#define IDC_FOLDER_TEXT                 1208
#define IDE_RECOVERY_FILE               1209
#define IDC_DISP_TEXT                   1214
#define IDC_TIMEOUT                     1216

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        326
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         1217
#define _APS_NEXT_SYMED_VALUE           156
#endif
#endif
