/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class java/lang/reflect/Array */

#ifdef IMPLEMENT_java_lang_reflect_Array
#define _implementing_java_lang_reflect_Array
#endif /* IMPLEMENT_java_lang_reflect_Array */
#define IMPLEMENT_java_lang_reflect_Array
#include "java_lang_reflect_Array.h"

#ifndef UNUSED_java_lang_reflect_Array_new
JRIMethodID FAR methodID_java_lang_reflect_Array_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_reflect_Array*)
java_lang_reflect_Array_new(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_java_lang_reflect_Array_new == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method <init> ()V");
	}
	return (struct java_lang_reflect_Array*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_reflect_Array_new);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_new */

#ifndef UNUSED_java_lang_reflect_Array_newInstance
JRIMethodID FAR methodID_java_lang_reflect_Array_newInstance = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Object *)
java_lang_reflect_Array_newInstance(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jint b) {
	if (methodID_java_lang_reflect_Array_newInstance == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method newInstance (Ljava/lang/Class;I)Ljava/lang/Object;");
	}
	return (struct java_lang_Object *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_newInstance, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_newInstance */

#ifndef UNUSED_java_lang_reflect_Array_newInstance_1
JRIMethodID FAR methodID_java_lang_reflect_Array_newInstance_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Object *)
java_lang_reflect_Array_newInstance_1(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jintArray b) {
	if (methodID_java_lang_reflect_Array_newInstance_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method newInstance (Ljava/lang/Class;[I)Ljava/lang/Object;");
	}
	return (struct java_lang_Object *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_newInstance_1, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_newInstance_1 */

#ifndef UNUSED_java_lang_reflect_Array_getLength
JRIMethodID FAR methodID_java_lang_reflect_Array_getLength = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_reflect_Array_getLength(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a) {
	if (methodID_java_lang_reflect_Array_getLength == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method getLength (Ljava/lang/Object;)I");
	}
	return (jint)JRI_CallStaticMethodInt(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getLength, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_getLength */

#ifndef UNUSED_java_lang_reflect_Array_get
JRIMethodID FAR methodID_java_lang_reflect_Array_get = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Object *)
java_lang_reflect_Array_get(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
	if (methodID_java_lang_reflect_Array_get == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method get (Ljava/lang/Object;I)Ljava/lang/Object;");
	}
	return (struct java_lang_Object *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_get, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_get */

#ifndef UNUSED_java_lang_reflect_Array_getBoolean
JRIMethodID FAR methodID_java_lang_reflect_Array_getBoolean = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_lang_reflect_Array_getBoolean(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
	if (methodID_java_lang_reflect_Array_getBoolean == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method getBoolean (Ljava/lang/Object;I)Z");
	}
	return (jbool)JRI_CallStaticMethodBoolean(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getBoolean, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_getBoolean */

#ifndef UNUSED_java_lang_reflect_Array_getByte
JRIMethodID FAR methodID_java_lang_reflect_Array_getByte = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbyte)
java_lang_reflect_Array_getByte(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
	if (methodID_java_lang_reflect_Array_getByte == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method getByte (Ljava/lang/Object;I)B");
	}
	return (jbyte)JRI_CallStaticMethodByte(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getByte, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_getByte */

#ifndef UNUSED_java_lang_reflect_Array_getChar
JRIMethodID FAR methodID_java_lang_reflect_Array_getChar = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jchar)
java_lang_reflect_Array_getChar(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
	if (methodID_java_lang_reflect_Array_getChar == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method getChar (Ljava/lang/Object;I)C");
	}
	return (jchar)JRI_CallStaticMethodChar(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getChar, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_getChar */

#ifndef UNUSED_java_lang_reflect_Array_getShort
JRIMethodID FAR methodID_java_lang_reflect_Array_getShort = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jshort)
java_lang_reflect_Array_getShort(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
	if (methodID_java_lang_reflect_Array_getShort == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method getShort (Ljava/lang/Object;I)S");
	}
	return (jshort)JRI_CallStaticMethodShort(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getShort, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_getShort */

#ifndef UNUSED_java_lang_reflect_Array_getInt
JRIMethodID FAR methodID_java_lang_reflect_Array_getInt = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_reflect_Array_getInt(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
	if (methodID_java_lang_reflect_Array_getInt == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method getInt (Ljava/lang/Object;I)I");
	}
	return (jint)JRI_CallStaticMethodInt(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getInt, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_getInt */

#ifndef UNUSED_java_lang_reflect_Array_getLong
JRIMethodID FAR methodID_java_lang_reflect_Array_getLong = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jlong)
java_lang_reflect_Array_getLong(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
	if (methodID_java_lang_reflect_Array_getLong == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method getLong (Ljava/lang/Object;I)J");
	}
	return (jlong)JRI_CallStaticMethodLong(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getLong, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_getLong */

#ifndef UNUSED_java_lang_reflect_Array_getFloat
JRIMethodID FAR methodID_java_lang_reflect_Array_getFloat = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jfloat)
java_lang_reflect_Array_getFloat(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
	if (methodID_java_lang_reflect_Array_getFloat == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method getFloat (Ljava/lang/Object;I)F");
	}
	return (jfloat)JRI_CallStaticMethodFloat(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getFloat, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_getFloat */

#ifndef UNUSED_java_lang_reflect_Array_getDouble
JRIMethodID FAR methodID_java_lang_reflect_Array_getDouble = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jdouble)
java_lang_reflect_Array_getDouble(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
	if (methodID_java_lang_reflect_Array_getDouble == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method getDouble (Ljava/lang/Object;I)D");
	}
	return (jdouble)JRI_CallStaticMethodDouble(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getDouble, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_getDouble */

#ifndef UNUSED_java_lang_reflect_Array_set
JRIMethodID FAR methodID_java_lang_reflect_Array_set = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_reflect_Array_set(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, struct java_lang_Object *c) {
	if (methodID_java_lang_reflect_Array_set == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method set (Ljava/lang/Object;ILjava/lang/Object;)V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_set, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_set */

#ifndef UNUSED_java_lang_reflect_Array_setBoolean
JRIMethodID FAR methodID_java_lang_reflect_Array_setBoolean = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_reflect_Array_setBoolean(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jbool c) {
	if (methodID_java_lang_reflect_Array_setBoolean == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method setBoolean (Ljava/lang/Object;IZ)V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setBoolean, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_setBoolean */

#ifndef UNUSED_java_lang_reflect_Array_setByte
JRIMethodID FAR methodID_java_lang_reflect_Array_setByte = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_reflect_Array_setByte(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jbyte c) {
	if (methodID_java_lang_reflect_Array_setByte == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method setByte (Ljava/lang/Object;IB)V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setByte, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_setByte */

#ifndef UNUSED_java_lang_reflect_Array_setChar
JRIMethodID FAR methodID_java_lang_reflect_Array_setChar = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_reflect_Array_setChar(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jchar c) {
	if (methodID_java_lang_reflect_Array_setChar == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method setChar (Ljava/lang/Object;IC)V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setChar, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_setChar */

#ifndef UNUSED_java_lang_reflect_Array_setShort
JRIMethodID FAR methodID_java_lang_reflect_Array_setShort = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_reflect_Array_setShort(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jshort c) {
	if (methodID_java_lang_reflect_Array_setShort == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method setShort (Ljava/lang/Object;IS)V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setShort, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_setShort */

#ifndef UNUSED_java_lang_reflect_Array_setInt
JRIMethodID FAR methodID_java_lang_reflect_Array_setInt = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_reflect_Array_setInt(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jint c) {
	if (methodID_java_lang_reflect_Array_setInt == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method setInt (Ljava/lang/Object;II)V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setInt, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_setInt */

#ifndef UNUSED_java_lang_reflect_Array_setLong
JRIMethodID FAR methodID_java_lang_reflect_Array_setLong = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_reflect_Array_setLong(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jlong c) {
	if (methodID_java_lang_reflect_Array_setLong == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method setLong (Ljava/lang/Object;IJ)V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setLong, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_setLong */

#ifndef UNUSED_java_lang_reflect_Array_setFloat
JRIMethodID FAR methodID_java_lang_reflect_Array_setFloat = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_reflect_Array_setFloat(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jfloat c) {
	if (methodID_java_lang_reflect_Array_setFloat == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method setFloat (Ljava/lang/Object;IF)V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setFloat, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_setFloat */

#ifndef UNUSED_java_lang_reflect_Array_setDouble
JRIMethodID FAR methodID_java_lang_reflect_Array_setDouble = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_reflect_Array_setDouble(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jdouble c) {
	if (methodID_java_lang_reflect_Array_setDouble == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method setDouble (Ljava/lang/Object;ID)V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setDouble, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_setDouble */

#ifndef UNUSED_java_lang_reflect_Array_newArray
JRIMethodID FAR methodID_java_lang_reflect_Array_newArray = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Object *)
java_lang_reflect_Array_newArray(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jint b) {
	if (methodID_java_lang_reflect_Array_newArray == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method newArray (Ljava/lang/Class;I)Ljava/lang/Object;");
	}
	return (struct java_lang_Object *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_newArray, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_newArray */

#ifndef UNUSED_java_lang_reflect_Array_multiNewArray
JRIMethodID FAR methodID_java_lang_reflect_Array_multiNewArray = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Object *)
java_lang_reflect_Array_multiNewArray(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jintArray b) {
	if (methodID_java_lang_reflect_Array_multiNewArray == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_reflect_Array(env) before calling method multiNewArray (Ljava/lang/Class;[I)Ljava/lang/Object;");
	}
	return (struct java_lang_Object *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_multiNewArray, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_reflect_Array_multiNewArray */

#ifndef UNUSED_use_java_lang_reflect_Array

static jglobal _globalclass_java_lang_reflect_Array = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_java_lang_reflect_Array(JRIEnv* env)
{
	if (_globalclass_java_lang_reflect_Array == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_lang_reflect_Array);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_java_lang_reflect_Array);
			return NULL;
		}
		use_java_lang_reflect_Array_new(env, clazz);
		use_java_lang_reflect_Array_newInstance(env, clazz);
		use_java_lang_reflect_Array_newInstance_1(env, clazz);
		use_java_lang_reflect_Array_getLength(env, clazz);
		use_java_lang_reflect_Array_get(env, clazz);
		use_java_lang_reflect_Array_getBoolean(env, clazz);
		use_java_lang_reflect_Array_getByte(env, clazz);
		use_java_lang_reflect_Array_getChar(env, clazz);
		use_java_lang_reflect_Array_getShort(env, clazz);
		use_java_lang_reflect_Array_getInt(env, clazz);
		use_java_lang_reflect_Array_getLong(env, clazz);
		use_java_lang_reflect_Array_getFloat(env, clazz);
		use_java_lang_reflect_Array_getDouble(env, clazz);
		use_java_lang_reflect_Array_set(env, clazz);
		use_java_lang_reflect_Array_setBoolean(env, clazz);
		use_java_lang_reflect_Array_setByte(env, clazz);
		use_java_lang_reflect_Array_setChar(env, clazz);
		use_java_lang_reflect_Array_setShort(env, clazz);
		use_java_lang_reflect_Array_setInt(env, clazz);
		use_java_lang_reflect_Array_setLong(env, clazz);
		use_java_lang_reflect_Array_setFloat(env, clazz);
		use_java_lang_reflect_Array_setDouble(env, clazz);
		use_java_lang_reflect_Array_newArray(env, clazz);
		use_java_lang_reflect_Array_multiNewArray(env, clazz);
		_globalclass_java_lang_reflect_Array = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_java_lang_reflect_Array);
	}
}

JRI_PUBLIC_API(void)
unuse_java_lang_reflect_Array(JRIEnv* env)
{
	if (_globalclass_java_lang_reflect_Array != NULL) {
		struct java_lang_Class* clazz = (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_java_lang_reflect_Array);
		unuse_java_lang_reflect_Array_new(env, clazz);
		unuse_java_lang_reflect_Array_newInstance(env, clazz);
		unuse_java_lang_reflect_Array_newInstance_1(env, clazz);
		unuse_java_lang_reflect_Array_getLength(env, clazz);
		unuse_java_lang_reflect_Array_get(env, clazz);
		unuse_java_lang_reflect_Array_getBoolean(env, clazz);
		unuse_java_lang_reflect_Array_getByte(env, clazz);
		unuse_java_lang_reflect_Array_getChar(env, clazz);
		unuse_java_lang_reflect_Array_getShort(env, clazz);
		unuse_java_lang_reflect_Array_getInt(env, clazz);
		unuse_java_lang_reflect_Array_getLong(env, clazz);
		unuse_java_lang_reflect_Array_getFloat(env, clazz);
		unuse_java_lang_reflect_Array_getDouble(env, clazz);
		unuse_java_lang_reflect_Array_set(env, clazz);
		unuse_java_lang_reflect_Array_setBoolean(env, clazz);
		unuse_java_lang_reflect_Array_setByte(env, clazz);
		unuse_java_lang_reflect_Array_setChar(env, clazz);
		unuse_java_lang_reflect_Array_setShort(env, clazz);
		unuse_java_lang_reflect_Array_setInt(env, clazz);
		unuse_java_lang_reflect_Array_setLong(env, clazz);
		unuse_java_lang_reflect_Array_setFloat(env, clazz);
		unuse_java_lang_reflect_Array_setDouble(env, clazz);
		unuse_java_lang_reflect_Array_newArray(env, clazz);
		unuse_java_lang_reflect_Array_multiNewArray(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_java_lang_reflect_Array);
		_globalclass_java_lang_reflect_Array = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_java_lang_reflect_Array */

#ifdef _implementing_java_lang_reflect_Array

JRI_PUBLIC_API(struct java_lang_Class*)
register_java_lang_reflect_Array(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		"getLength(Ljava/lang/Object;)I",
		"get(Ljava/lang/Object;I)Ljava/lang/Object;",
		"getBoolean(Ljava/lang/Object;I)Z",
		"getByte(Ljava/lang/Object;I)B",
		"getChar(Ljava/lang/Object;I)C",
		"getShort(Ljava/lang/Object;I)S",
		"getInt(Ljava/lang/Object;I)I",
		"getLong(Ljava/lang/Object;I)J",
		"getFloat(Ljava/lang/Object;I)F",
		"getDouble(Ljava/lang/Object;I)D",
		"set(Ljava/lang/Object;ILjava/lang/Object;)V",
		"setBoolean(Ljava/lang/Object;IZ)V",
		"setByte(Ljava/lang/Object;IB)V",
		"setChar(Ljava/lang/Object;IC)V",
		"setShort(Ljava/lang/Object;IS)V",
		"setInt(Ljava/lang/Object;II)V",
		"setLong(Ljava/lang/Object;IJ)V",
		"setFloat(Ljava/lang/Object;IF)V",
		"setDouble(Ljava/lang/Object;ID)V",
		"newArray(Ljava/lang/Class;I)Ljava/lang/Object;",
		"multiNewArray(Ljava/lang/Class;[I)Ljava/lang/Object;",
		NULL
	};
	void* nativeProcs[] = {
		(void*)native_java_lang_reflect_Array_getLength,
		(void*)native_java_lang_reflect_Array_get,
		(void*)native_java_lang_reflect_Array_getBoolean,
		(void*)native_java_lang_reflect_Array_getByte,
		(void*)native_java_lang_reflect_Array_getChar,
		(void*)native_java_lang_reflect_Array_getShort,
		(void*)native_java_lang_reflect_Array_getInt,
		(void*)native_java_lang_reflect_Array_getLong,
		(void*)native_java_lang_reflect_Array_getFloat,
		(void*)native_java_lang_reflect_Array_getDouble,
		(void*)native_java_lang_reflect_Array_set,
		(void*)native_java_lang_reflect_Array_setBoolean,
		(void*)native_java_lang_reflect_Array_setByte,
		(void*)native_java_lang_reflect_Array_setChar,
		(void*)native_java_lang_reflect_Array_setShort,
		(void*)native_java_lang_reflect_Array_setInt,
		(void*)native_java_lang_reflect_Array_setLong,
		(void*)native_java_lang_reflect_Array_setFloat,
		(void*)native_java_lang_reflect_Array_setDouble,
		(void*)native_java_lang_reflect_Array_newArray,
		(void*)native_java_lang_reflect_Array_multiNewArray,
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_lang_reflect_Array);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_java_lang_reflect_Array);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_java_lang_reflect_Array(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_java_lang_reflect_Array(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_lang_reflect_Array);
	JRI_UnregisterNatives(env, clazz);
	unuse_java_lang_reflect_Array(env);
}

#endif /* _implementing_java_lang_reflect_Array */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

#endif /* NO_JDK */

