/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class java/util/Date */

#ifdef IMPLEMENT_java_util_Date
#define _implementing_java_util_Date
#endif /* IMPLEMENT_java_util_Date */
#define IMPLEMENT_java_util_Date
#include "java_util_Date.h"

#ifndef UNUSED_java_util_Date_value
JRIFieldID FAR fieldID_java_util_Date_value = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jlong)
get_java_util_Date_value(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_value == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field value J");
	}
	return JRI_GetFieldLong(env, obj, fieldID_java_util_Date_value);
}
JRI_PUBLIC_API(void)
set_java_util_Date_value(JRIEnv* env, struct java_util_Date* obj, jlong v) {
	if (fieldID_java_util_Date_value == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field value J");
	}
	JRI_SetFieldLong(env, obj, fieldID_java_util_Date_value, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_value */

#ifndef UNUSED_java_util_Date_valueValid
JRIFieldID FAR fieldID_java_util_Date_valueValid = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
get_java_util_Date_valueValid(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_valueValid == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field valueValid Z");
	}
	return JRI_GetFieldBoolean(env, obj, fieldID_java_util_Date_valueValid);
}
JRI_PUBLIC_API(void)
set_java_util_Date_valueValid(JRIEnv* env, struct java_util_Date* obj, jbool v) {
	if (fieldID_java_util_Date_valueValid == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field valueValid Z");
	}
	JRI_SetFieldBoolean(env, obj, fieldID_java_util_Date_valueValid, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_valueValid */

#ifndef UNUSED_java_util_Date_expanded
JRIFieldID FAR fieldID_java_util_Date_expanded = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
get_java_util_Date_expanded(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_expanded == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field expanded Z");
	}
	return JRI_GetFieldBoolean(env, obj, fieldID_java_util_Date_expanded);
}
JRI_PUBLIC_API(void)
set_java_util_Date_expanded(JRIEnv* env, struct java_util_Date* obj, jbool v) {
	if (fieldID_java_util_Date_expanded == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field expanded Z");
	}
	JRI_SetFieldBoolean(env, obj, fieldID_java_util_Date_expanded, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_expanded */

#ifndef UNUSED_java_util_Date_tm_millis
JRIFieldID FAR fieldID_java_util_Date_tm_millis = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jshort)
get_java_util_Date_tm_millis(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_tm_millis == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_millis S");
	}
	return JRI_GetFieldShort(env, obj, fieldID_java_util_Date_tm_millis);
}
JRI_PUBLIC_API(void)
set_java_util_Date_tm_millis(JRIEnv* env, struct java_util_Date* obj, jshort v) {
	if (fieldID_java_util_Date_tm_millis == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_millis S");
	}
	JRI_SetFieldShort(env, obj, fieldID_java_util_Date_tm_millis, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_tm_millis */

#ifndef UNUSED_java_util_Date_tm_sec
JRIFieldID FAR fieldID_java_util_Date_tm_sec = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbyte)
get_java_util_Date_tm_sec(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_tm_sec == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_sec B");
	}
	return JRI_GetFieldByte(env, obj, fieldID_java_util_Date_tm_sec);
}
JRI_PUBLIC_API(void)
set_java_util_Date_tm_sec(JRIEnv* env, struct java_util_Date* obj, jbyte v) {
	if (fieldID_java_util_Date_tm_sec == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_sec B");
	}
	JRI_SetFieldByte(env, obj, fieldID_java_util_Date_tm_sec, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_tm_sec */

#ifndef UNUSED_java_util_Date_tm_min
JRIFieldID FAR fieldID_java_util_Date_tm_min = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbyte)
get_java_util_Date_tm_min(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_tm_min == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_min B");
	}
	return JRI_GetFieldByte(env, obj, fieldID_java_util_Date_tm_min);
}
JRI_PUBLIC_API(void)
set_java_util_Date_tm_min(JRIEnv* env, struct java_util_Date* obj, jbyte v) {
	if (fieldID_java_util_Date_tm_min == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_min B");
	}
	JRI_SetFieldByte(env, obj, fieldID_java_util_Date_tm_min, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_tm_min */

#ifndef UNUSED_java_util_Date_tm_hour
JRIFieldID FAR fieldID_java_util_Date_tm_hour = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbyte)
get_java_util_Date_tm_hour(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_tm_hour == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_hour B");
	}
	return JRI_GetFieldByte(env, obj, fieldID_java_util_Date_tm_hour);
}
JRI_PUBLIC_API(void)
set_java_util_Date_tm_hour(JRIEnv* env, struct java_util_Date* obj, jbyte v) {
	if (fieldID_java_util_Date_tm_hour == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_hour B");
	}
	JRI_SetFieldByte(env, obj, fieldID_java_util_Date_tm_hour, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_tm_hour */

#ifndef UNUSED_java_util_Date_tm_mday
JRIFieldID FAR fieldID_java_util_Date_tm_mday = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbyte)
get_java_util_Date_tm_mday(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_tm_mday == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_mday B");
	}
	return JRI_GetFieldByte(env, obj, fieldID_java_util_Date_tm_mday);
}
JRI_PUBLIC_API(void)
set_java_util_Date_tm_mday(JRIEnv* env, struct java_util_Date* obj, jbyte v) {
	if (fieldID_java_util_Date_tm_mday == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_mday B");
	}
	JRI_SetFieldByte(env, obj, fieldID_java_util_Date_tm_mday, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_tm_mday */

#ifndef UNUSED_java_util_Date_tm_mon
JRIFieldID FAR fieldID_java_util_Date_tm_mon = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbyte)
get_java_util_Date_tm_mon(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_tm_mon == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_mon B");
	}
	return JRI_GetFieldByte(env, obj, fieldID_java_util_Date_tm_mon);
}
JRI_PUBLIC_API(void)
set_java_util_Date_tm_mon(JRIEnv* env, struct java_util_Date* obj, jbyte v) {
	if (fieldID_java_util_Date_tm_mon == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_mon B");
	}
	JRI_SetFieldByte(env, obj, fieldID_java_util_Date_tm_mon, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_tm_mon */

#ifndef UNUSED_java_util_Date_tm_wday
JRIFieldID FAR fieldID_java_util_Date_tm_wday = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbyte)
get_java_util_Date_tm_wday(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_tm_wday == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_wday B");
	}
	return JRI_GetFieldByte(env, obj, fieldID_java_util_Date_tm_wday);
}
JRI_PUBLIC_API(void)
set_java_util_Date_tm_wday(JRIEnv* env, struct java_util_Date* obj, jbyte v) {
	if (fieldID_java_util_Date_tm_wday == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_wday B");
	}
	JRI_SetFieldByte(env, obj, fieldID_java_util_Date_tm_wday, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_tm_wday */

#ifndef UNUSED_java_util_Date_tm_yday
JRIFieldID FAR fieldID_java_util_Date_tm_yday = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jshort)
get_java_util_Date_tm_yday(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_tm_yday == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_yday S");
	}
	return JRI_GetFieldShort(env, obj, fieldID_java_util_Date_tm_yday);
}
JRI_PUBLIC_API(void)
set_java_util_Date_tm_yday(JRIEnv* env, struct java_util_Date* obj, jshort v) {
	if (fieldID_java_util_Date_tm_yday == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_yday S");
	}
	JRI_SetFieldShort(env, obj, fieldID_java_util_Date_tm_yday, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_tm_yday */

#ifndef UNUSED_java_util_Date_tm_year
JRIFieldID FAR fieldID_java_util_Date_tm_year = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_java_util_Date_tm_year(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_tm_year == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_year I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_java_util_Date_tm_year);
}
JRI_PUBLIC_API(void)
set_java_util_Date_tm_year(JRIEnv* env, struct java_util_Date* obj, jint v) {
	if (fieldID_java_util_Date_tm_year == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_year I");
	}
	JRI_SetFieldInt(env, obj, fieldID_java_util_Date_tm_year, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_tm_year */

#ifndef UNUSED_java_util_Date_tm_isdst
JRIFieldID FAR fieldID_java_util_Date_tm_isdst = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_java_util_Date_tm_isdst(JRIEnv* env, struct java_util_Date* obj) {
	if (fieldID_java_util_Date_tm_isdst == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_isdst I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_java_util_Date_tm_isdst);
}
JRI_PUBLIC_API(void)
set_java_util_Date_tm_isdst(JRIEnv* env, struct java_util_Date* obj, jint v) {
	if (fieldID_java_util_Date_tm_isdst == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field tm_isdst I");
	}
	JRI_SetFieldInt(env, obj, fieldID_java_util_Date_tm_isdst, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_tm_isdst */

#ifndef UNUSED_java_util_Date_monthOffset
JRIFieldID FAR fieldID_java_util_Date_monthOffset = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jref)
get_java_util_Date_monthOffset(JRIEnv* env, struct java_lang_Class* clazz) {
	if (fieldID_java_util_Date_monthOffset == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field monthOffset [S");
	}
	return (jref)
		JRI_GetStaticField(env, clazz, fieldID_java_util_Date_monthOffset);
}
JRI_PUBLIC_API(void)
set_java_util_Date_monthOffset(JRIEnv* env, struct java_lang_Class* clazz, jref v) {
	if (fieldID_java_util_Date_monthOffset == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field monthOffset [S");
	}
	JRI_SetStaticField(env, clazz, fieldID_java_util_Date_monthOffset, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_monthOffset */

#ifndef UNUSED_java_util_Date_wtb
JRIFieldID FAR fieldID_java_util_Date_wtb = JRIUninitialized;
#ifdef DEBUG
struct java_lang_String;
JRI_PUBLIC_API(jref)
get_java_util_Date_wtb(JRIEnv* env, struct java_lang_Class* clazz) {
	if (fieldID_java_util_Date_wtb == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field wtb [Ljava/lang/String;");
	}
	return (jref)
		JRI_GetStaticField(env, clazz, fieldID_java_util_Date_wtb);
}
JRI_PUBLIC_API(void)
set_java_util_Date_wtb(JRIEnv* env, struct java_lang_Class* clazz, jref v) {
	if (fieldID_java_util_Date_wtb == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field wtb [Ljava/lang/String;");
	}
	JRI_SetStaticField(env, clazz, fieldID_java_util_Date_wtb, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_wtb */

#ifndef UNUSED_java_util_Date_ttb
JRIFieldID FAR fieldID_java_util_Date_ttb = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jref)
get_java_util_Date_ttb(JRIEnv* env, struct java_lang_Class* clazz) {
	if (fieldID_java_util_Date_ttb == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field ttb [I");
	}
	return (jref)
		JRI_GetStaticField(env, clazz, fieldID_java_util_Date_ttb);
}
JRI_PUBLIC_API(void)
set_java_util_Date_ttb(JRIEnv* env, struct java_lang_Class* clazz, jref v) {
	if (fieldID_java_util_Date_ttb == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before accessing field ttb [I");
	}
	JRI_SetStaticField(env, clazz, fieldID_java_util_Date_ttb, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_ttb */

#ifndef UNUSED_java_util_Date_new
JRIMethodID FAR methodID_java_util_Date_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_util_Date*)
java_util_Date_new(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_java_util_Date_new == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method <init> ()V");
	}
	return (struct java_util_Date*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_util_Date_new);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_new */

#ifndef UNUSED_java_util_Date_new_1
JRIMethodID FAR methodID_java_util_Date_new_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_util_Date*)
java_util_Date_new_1(JRIEnv* env, struct java_lang_Class* clazz, jlong a) {
	if (methodID_java_util_Date_new_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method <init> (J)V");
	}
	return (struct java_util_Date*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_util_Date_new_1, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_new_1 */

#ifndef UNUSED_java_util_Date_new_2
JRIMethodID FAR methodID_java_util_Date_new_2 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_util_Date*)
java_util_Date_new_2(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c) {
	if (methodID_java_util_Date_new_2 == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method <init> (III)V");
	}
	return (struct java_util_Date*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_util_Date_new_2, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_new_2 */

#ifndef UNUSED_java_util_Date_new_3
JRIMethodID FAR methodID_java_util_Date_new_3 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_util_Date*)
java_util_Date_new_3(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c, jint d, jint e) {
	if (methodID_java_util_Date_new_3 == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method <init> (IIIII)V");
	}
	return (struct java_util_Date*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_util_Date_new_3, a, b, c, d, e);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_new_3 */

#ifndef UNUSED_java_util_Date_new_4
JRIMethodID FAR methodID_java_util_Date_new_4 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_util_Date*)
java_util_Date_new_4(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c, jint d, jint e, jint f) {
	if (methodID_java_util_Date_new_4 == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method <init> (IIIIII)V");
	}
	return (struct java_util_Date*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_util_Date_new_4, a, b, c, d, e, f);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_new_4 */

#ifndef UNUSED_java_util_Date_new_5
JRIMethodID FAR methodID_java_util_Date_new_5 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_util_Date*)
java_util_Date_new_5(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a) {
	if (methodID_java_util_Date_new_5 == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method <init> (Ljava/lang/String;)V");
	}
	return (struct java_util_Date*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_util_Date_new_5, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_new_5 */

#ifndef UNUSED_java_util_Date_UTC
JRIMethodID FAR methodID_java_util_Date_UTC = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jlong)
java_util_Date_UTC(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c, jint d, jint e, jint f) {
	if (methodID_java_util_Date_UTC == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method UTC (IIIIII)J");
	}	
	return JRI_CallStaticMethodLong(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_util_Date_UTC, a, b, c, d, e, f);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_UTC */

#ifndef UNUSED_java_util_Date_parse
JRIMethodID FAR methodID_java_util_Date_parse = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jlong)
java_util_Date_parse(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a) {
	if (methodID_java_util_Date_parse == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method parse (Ljava/lang/String;)J");
	}

	return JRI_CallStaticMethodLong(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_util_Date_parse, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_parse */

#ifndef UNUSED_java_util_Date_getYear
JRIMethodID FAR methodID_java_util_Date_getYear = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_util_Date_getYear(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_getYear == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method getYear ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_getYear);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_getYear */

#ifndef UNUSED_java_util_Date_setYear
JRIMethodID FAR methodID_java_util_Date_setYear = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_util_Date_setYear(JRIEnv* env, struct java_util_Date* self, jint a) {
	if (methodID_java_util_Date_setYear == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method setYear (I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_setYear, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_setYear */

#ifndef UNUSED_java_util_Date_getMonth
JRIMethodID FAR methodID_java_util_Date_getMonth = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_util_Date_getMonth(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_getMonth == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method getMonth ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_getMonth);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_getMonth */

#ifndef UNUSED_java_util_Date_setMonth
JRIMethodID FAR methodID_java_util_Date_setMonth = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_util_Date_setMonth(JRIEnv* env, struct java_util_Date* self, jint a) {
	if (methodID_java_util_Date_setMonth == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method setMonth (I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_setMonth, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_setMonth */

#ifndef UNUSED_java_util_Date_getDate
JRIMethodID FAR methodID_java_util_Date_getDate = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_util_Date_getDate(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_getDate == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method getDate ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_getDate);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_getDate */

#ifndef UNUSED_java_util_Date_setDate
JRIMethodID FAR methodID_java_util_Date_setDate = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_util_Date_setDate(JRIEnv* env, struct java_util_Date* self, jint a) {
	if (methodID_java_util_Date_setDate == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method setDate (I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_setDate, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_setDate */

#ifndef UNUSED_java_util_Date_getDay
JRIMethodID FAR methodID_java_util_Date_getDay = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_util_Date_getDay(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_getDay == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method getDay ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_getDay);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_getDay */

#ifndef UNUSED_java_util_Date_getHours
JRIMethodID FAR methodID_java_util_Date_getHours = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_util_Date_getHours(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_getHours == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method getHours ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_getHours);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_getHours */

#ifndef UNUSED_java_util_Date_setHours
JRIMethodID FAR methodID_java_util_Date_setHours = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_util_Date_setHours(JRIEnv* env, struct java_util_Date* self, jint a) {
	if (methodID_java_util_Date_setHours == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method setHours (I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_setHours, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_setHours */

#ifndef UNUSED_java_util_Date_getMinutes
JRIMethodID FAR methodID_java_util_Date_getMinutes = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_util_Date_getMinutes(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_getMinutes == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method getMinutes ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_getMinutes);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_getMinutes */

#ifndef UNUSED_java_util_Date_setMinutes
JRIMethodID FAR methodID_java_util_Date_setMinutes = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_util_Date_setMinutes(JRIEnv* env, struct java_util_Date* self, jint a) {
	if (methodID_java_util_Date_setMinutes == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method setMinutes (I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_setMinutes, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_setMinutes */

#ifndef UNUSED_java_util_Date_getSeconds
JRIMethodID FAR methodID_java_util_Date_getSeconds = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_util_Date_getSeconds(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_getSeconds == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method getSeconds ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_getSeconds);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_getSeconds */

#ifndef UNUSED_java_util_Date_setSeconds
JRIMethodID FAR methodID_java_util_Date_setSeconds = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_util_Date_setSeconds(JRIEnv* env, struct java_util_Date* self, jint a) {
	if (methodID_java_util_Date_setSeconds == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method setSeconds (I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_setSeconds, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_setSeconds */

#ifndef UNUSED_java_util_Date_getTime
JRIMethodID FAR methodID_java_util_Date_getTime = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jlong)
java_util_Date_getTime(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_getTime == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method getTime ()J");
	}
	return JRI_CallMethodLong(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_getTime);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_getTime */

#ifndef UNUSED_java_util_Date_setTime
JRIMethodID FAR methodID_java_util_Date_setTime = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_util_Date_setTime(JRIEnv* env, struct java_util_Date* self, jlong a) {
	if (methodID_java_util_Date_setTime == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method setTime (J)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_setTime, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_setTime */

#ifndef UNUSED_java_util_Date_before
JRIMethodID FAR methodID_java_util_Date_before = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_util_Date_before(JRIEnv* env, struct java_util_Date* self, struct java_util_Date *a) {
	if (methodID_java_util_Date_before == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method before (Ljava/util/Date;)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_before, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_before */

#ifndef UNUSED_java_util_Date_after
JRIMethodID FAR methodID_java_util_Date_after = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_util_Date_after(JRIEnv* env, struct java_util_Date* self, struct java_util_Date *a) {
	if (methodID_java_util_Date_after == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method after (Ljava/util/Date;)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_after, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_after */

#ifndef UNUSED_java_util_Date_equals
JRIMethodID FAR methodID_java_util_Date_equals = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_util_Date_equals(JRIEnv* env, struct java_util_Date* self, struct java_lang_Object *a) {
	if (methodID_java_util_Date_equals == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method equals (Ljava/lang/Object;)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_equals, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_equals */

#ifndef UNUSED_java_util_Date_hashCode
JRIMethodID FAR methodID_java_util_Date_hashCode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_util_Date_hashCode(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_hashCode == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method hashCode ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_hashCode);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_hashCode */

#ifndef UNUSED_java_util_Date_toString
JRIMethodID FAR methodID_java_util_Date_toString = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_util_Date_toString(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_toString == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method toString ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_toString);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_toString */

#ifndef UNUSED_java_util_Date_toLocaleString
JRIMethodID FAR methodID_java_util_Date_toLocaleString = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_util_Date_toLocaleString(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_toLocaleString == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method toLocaleString ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_toLocaleString);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_toLocaleString */

#ifndef UNUSED_java_util_Date_toGMTString
JRIMethodID FAR methodID_java_util_Date_toGMTString = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_util_Date_toGMTString(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_toGMTString == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method toGMTString ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_toGMTString);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_toGMTString */

#ifndef UNUSED_java_util_Date_getTimezoneOffset
JRIMethodID FAR methodID_java_util_Date_getTimezoneOffset = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_util_Date_getTimezoneOffset(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_getTimezoneOffset == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method getTimezoneOffset ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_getTimezoneOffset);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_getTimezoneOffset */

#ifndef UNUSED_java_util_Date_expand
JRIMethodID FAR methodID_java_util_Date_expand = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_util_Date_expand(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_expand == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method expand ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_expand);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_expand */

#ifndef UNUSED_java_util_Date_computeValue
JRIMethodID FAR methodID_java_util_Date_computeValue = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_util_Date_computeValue(JRIEnv* env, struct java_util_Date* self) {
	if (methodID_java_util_Date_computeValue == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method computeValue ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_util_Date_computeValue);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date_computeValue */

#ifndef UNUSED_java_util_Date__0003cclinit_0003e
JRIMethodID FAR methodID_java_util_Date__0003cclinit_0003e = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_util_Date__0003cclinit_0003e(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_java_util_Date__0003cclinit_0003e == JRIUninitialized) {
		assert(!"Forgot to call use_java_util_Date(env) before calling method <clinit> ()V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_util_Date__0003cclinit_0003e);
}
#endif /* DEBUG */
#endif /* UNUSED_java_util_Date__0003cclinit_0003e */

#ifndef UNUSED_use_java_util_Date

static jglobal _globalclass_java_util_Date = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_java_util_Date(JRIEnv* env)
{
	if (_globalclass_java_util_Date == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_util_Date);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_java_util_Date);
			return NULL;
		}
		use_java_util_Date_value(env, clazz);
		use_java_util_Date_valueValid(env, clazz);
		use_java_util_Date_expanded(env, clazz);
		use_java_util_Date_tm_millis(env, clazz);
		use_java_util_Date_tm_sec(env, clazz);
		use_java_util_Date_tm_min(env, clazz);
		use_java_util_Date_tm_hour(env, clazz);
		use_java_util_Date_tm_mday(env, clazz);
		use_java_util_Date_tm_mon(env, clazz);
		use_java_util_Date_tm_wday(env, clazz);
		use_java_util_Date_tm_yday(env, clazz);
		use_java_util_Date_tm_year(env, clazz);
		use_java_util_Date_tm_isdst(env, clazz);
		use_java_util_Date_monthOffset(env, clazz);
		use_java_util_Date_wtb(env, clazz);
		use_java_util_Date_ttb(env, clazz);
		use_java_util_Date_new(env, clazz);
		use_java_util_Date_new_1(env, clazz);
		use_java_util_Date_new_2(env, clazz);
		use_java_util_Date_new_3(env, clazz);
		use_java_util_Date_new_4(env, clazz);
		use_java_util_Date_new_5(env, clazz);
		use_java_util_Date_UTC(env, clazz);
		use_java_util_Date_parse(env, clazz);
		use_java_util_Date_getYear(env, clazz);
		use_java_util_Date_setYear(env, clazz);
		use_java_util_Date_getMonth(env, clazz);
		use_java_util_Date_setMonth(env, clazz);
		use_java_util_Date_getDate(env, clazz);
		use_java_util_Date_setDate(env, clazz);
		use_java_util_Date_getDay(env, clazz);
		use_java_util_Date_getHours(env, clazz);
		use_java_util_Date_setHours(env, clazz);
		use_java_util_Date_getMinutes(env, clazz);
		use_java_util_Date_setMinutes(env, clazz);
		use_java_util_Date_getSeconds(env, clazz);
		use_java_util_Date_setSeconds(env, clazz);
		use_java_util_Date_getTime(env, clazz);
		use_java_util_Date_setTime(env, clazz);
		use_java_util_Date_before(env, clazz);
		use_java_util_Date_after(env, clazz);
		use_java_util_Date_equals(env, clazz);
		use_java_util_Date_hashCode(env, clazz);
		use_java_util_Date_toString(env, clazz);
		use_java_util_Date_toLocaleString(env, clazz);
		use_java_util_Date_toGMTString(env, clazz);
		use_java_util_Date_getTimezoneOffset(env, clazz);
		use_java_util_Date_expand(env, clazz);
		use_java_util_Date_computeValue(env, clazz);
		use_java_util_Date__0003cclinit_0003e(env, clazz);
		_globalclass_java_util_Date = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_java_util_Date);
	}
}

JRI_PUBLIC_API(void)
unuse_java_util_Date(JRIEnv* env)
{
	if (_globalclass_java_util_Date != NULL) {
		struct java_lang_Class* clazz = (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_java_util_Date);
		unuse_java_util_Date_value(env, clazz);
		unuse_java_util_Date_valueValid(env, clazz);
		unuse_java_util_Date_expanded(env, clazz);
		unuse_java_util_Date_tm_millis(env, clazz);
		unuse_java_util_Date_tm_sec(env, clazz);
		unuse_java_util_Date_tm_min(env, clazz);
		unuse_java_util_Date_tm_hour(env, clazz);
		unuse_java_util_Date_tm_mday(env, clazz);
		unuse_java_util_Date_tm_mon(env, clazz);
		unuse_java_util_Date_tm_wday(env, clazz);
		unuse_java_util_Date_tm_yday(env, clazz);
		unuse_java_util_Date_tm_year(env, clazz);
		unuse_java_util_Date_tm_isdst(env, clazz);
		unuse_java_util_Date_monthOffset(env, clazz);
		unuse_java_util_Date_wtb(env, clazz);
		unuse_java_util_Date_ttb(env, clazz);
		unuse_java_util_Date_new(env, clazz);
		unuse_java_util_Date_new_1(env, clazz);
		unuse_java_util_Date_new_2(env, clazz);
		unuse_java_util_Date_new_3(env, clazz);
		unuse_java_util_Date_new_4(env, clazz);
		unuse_java_util_Date_new_5(env, clazz);
		unuse_java_util_Date_UTC(env, clazz);
		unuse_java_util_Date_parse(env, clazz);
		unuse_java_util_Date_getYear(env, clazz);
		unuse_java_util_Date_setYear(env, clazz);
		unuse_java_util_Date_getMonth(env, clazz);
		unuse_java_util_Date_setMonth(env, clazz);
		unuse_java_util_Date_getDate(env, clazz);
		unuse_java_util_Date_setDate(env, clazz);
		unuse_java_util_Date_getDay(env, clazz);
		unuse_java_util_Date_getHours(env, clazz);
		unuse_java_util_Date_setHours(env, clazz);
		unuse_java_util_Date_getMinutes(env, clazz);
		unuse_java_util_Date_setMinutes(env, clazz);
		unuse_java_util_Date_getSeconds(env, clazz);
		unuse_java_util_Date_setSeconds(env, clazz);
		unuse_java_util_Date_getTime(env, clazz);
		unuse_java_util_Date_setTime(env, clazz);
		unuse_java_util_Date_before(env, clazz);
		unuse_java_util_Date_after(env, clazz);
		unuse_java_util_Date_equals(env, clazz);
		unuse_java_util_Date_hashCode(env, clazz);
		unuse_java_util_Date_toString(env, clazz);
		unuse_java_util_Date_toLocaleString(env, clazz);
		unuse_java_util_Date_toGMTString(env, clazz);
		unuse_java_util_Date_getTimezoneOffset(env, clazz);
		unuse_java_util_Date_expand(env, clazz);
		unuse_java_util_Date_computeValue(env, clazz);
		unuse_java_util_Date__0003cclinit_0003e(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_java_util_Date);
		_globalclass_java_util_Date = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_java_util_Date */

#ifdef _implementing_java_util_Date

JRI_PUBLIC_API(struct java_lang_Class*)
register_java_util_Date(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		"toString()Ljava/lang/String;",
		"toLocaleString()Ljava/lang/String;",
		"toGMTString()Ljava/lang/String;",
		"expand()V",
		"computeValue()V",
		NULL
	};
	void* nativeProcs[] = {
		(void*)native_java_util_Date_toString,
		(void*)native_java_util_Date_toLocaleString,
		(void*)native_java_util_Date_toGMTString,
		(void*)native_java_util_Date_expand,
		(void*)native_java_util_Date_computeValue,
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_util_Date);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_java_util_Date);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_java_util_Date(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_java_util_Date(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_util_Date);
	JRI_UnregisterNatives(env, clazz);
	unuse_java_util_Date(env);
}

#endif /* _implementing_java_util_Date */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

#endif /* NO_JDK */

