#	GNUmakefile 
#       Developed by Ajay Jayaram
#	$Id: GNUmakefile,v 1.1.2.2 2001/12/11 22:35:38 npaul Exp $
#

ECAS_HOME = ../../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


ifeq ($(CISCO), 1)
SPECIAL_sparc_DIRS = cisco
endif

SUBDIRS = npvssc vsscnpsetup npsesetup


include $(ECAS_RULES_DIR)/directory.cfg

