#	GNUmakefile 
#       Developed by Ajay Jayaram
#	$Id: GNUmakefile,v 1.1.4.1 2003/05/16 20:51:20 sgoginen Exp $
#

ECAS_HOME = ../../../

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


ifeq ($(CISCO), 1)
SPECIAL_sparc_DIRS = cisco
endif

SUBDIRS = ptav3 msi


include $(ECAS_RULES_DIR)/directory.cfg

