#	GNUmakefile 
#       Developed by Abhay Ranade
#	$Id: GNUmakefile,v 1.4.174.2 2006/11/18 09:39:14 schenna Exp $
#

ECAS_HOME = ../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg

SUBDIRS = cgi-bin config fdf htmldocs htmldocs/error htmldocs/graphics


include $(ECAS_RULES_DIR)/directory.cfg

