<!-- VSSKBEGINPOLICYVAL#show#2 -->
<TABLE WIDTH=588 BGCOLOR="ffffcc" CELLPADDING=7 CELLSPACING=0 BORDER=0>
<TR>
	<TD WIDTH=588>
<FONT SIZE=2 FACE="verdana, arial, helvetica"><B>Digital ID Subscriber Agreement</B><br>

By applying for, submitting, or using a Digital ID, you are agreeing to the terms of the VeriSign Subscriber Agreement.  </FONT>
</TD>	
</TR>
 <TR><TD>
	<!--<TABLE WIDTH=574 CELLPADDING=3 CELLSPACING=2 BORDER=0>
	<TR>
		<TD WIDTH=100% BGCOLOR="ffcc00"><A HREF="%%subAgrURL%%">%%subAgrURL%%</A>&nbsp;</TD>
	</TR>
	</TABLE> -->

		<TABLE WIDTH=588 CELLPADDING=7 CELLSPACING=0 BORDER=0 BGCOLOR="ffffcc">
<TR><TD><center>
<textarea name="Agreement" ROWS="30" COLS="68" wrap="soft" onFocus=javascript:blur()>
SUBSCRIBER AGREEMENT

YOU MUST READ THIS SUBSCRIBER AGREEMENT ("SUBSCRIBER AGREEMENT") BEFORE APPLYING FOR, ACCEPTING, OR USING A VERISIGN CERTIFICATE OR DIGITAL ID ("CERTIFICATE" OR "DIGITAL ID"). IF YOU DO NOT AGREE TO THE TERMS OF THIS SUBSCRIBER AGREEMENT, DO NOT APPLY FOR, ACCEPT, OR USE THE CERTIFICATE.


1.  Certificate Application and Description of Certificates. This section details the terms and conditions regarding your application ("Certificate Application") for a Certificate and, if VeriSign accepts your Certificate Application, the terms and conditions regarding the your use of the Certificate to be issued by VeriSign to you as "Subscriber" of that Certificate. A Certificate is a digitally signed message that contains a Subscriber's public key and associates it with information authenticated by VeriSign or a VeriSign-authorized entity. The Certificates provided under this Agreement are issued within the VeriSign Trust Network ("VTN"). The VTN is a global public key infrastructure that provides Certificates for both wired and wireless applications. VeriSign is one of the service providers within the VTN, together with a global network of affiliates and partners throughout the world. The VTN and VeriSign under this Agreement offer three distinct classes ("Classes") of certification services, Classes 1-3, for both the wired and wireless Internet and other networks. Each level, or class, of Certificate provides specific functionality and security features and corresponds to a specific level of trust. You are responsible for choosing which Class of Certificate you need.  The following subsections state the appropriate uses and authentication procedures for each Class of Certificate.  For more detailed information about VeriSign's certification services, please see the VeriSign Certification Practice Statement (the "VeriSign CPS") which may be accessed at http://www.verisign.com/CPS.

(i) Class 1 Certificates. Class 1 Certificates offer the lowest level of assurances within the VTN. The Certificates are issued to individual Subscribers only, and authentication procedures are based on assurances that the Subscriber's distinguished name is unique and unambiguous within the domain of a particular issuer of Certificates (a "Certification Authority") and that a certain e-mail address is associated with a public key.  Class 1 Certificates are appropriate for digital signatures, encryption, and access control for non-commercial or low-value transactions where proof of identity is unnecessary.

(ii) Class 2 Certificates. Class 2 Certificates offer a medium level of assurances in comparison with the other two Classes. Again, they are issued to individual Subscribers only. In addition to the Class 1 authentication procedures, Class 2 authentication includes procedures based on a comparison of information submitted by the certificate applicant against information in business records or databases or the database of a VeriSign-approved identity proofing service. They can be used for digital signatures, encryption, and access control, including as proof of identity in medium-value transactions.

(iii) Class 3 Certificates. Class 3 Certificates provide the highest level of assurances within the VTN. Class 3 Certificates are issued to individuals and organizations for use with both client and server software. Class 3 individual Certificates may be used for digital signatures, encryption, and access control, including as proof of identity, in high-value transactions. Class 3 individual Certificates provide assurances of the identity of the Subscriber based on the personal (physical) presence of the Subscriber before a person that confirms the identity of the Subscriber using, at a minimum, a well-recognized form of government-issued identification and one other identification credential. Class 3 organizational Certificates are issued to devices to provide authentication; message, software, and content integrity and signing; and confidentiality encryption. Class 3 organizational Certificates provide assurances of the identity of the Subscriber based on a confirmation that the Subscriber organization does in fact exist, that the organization has authorized the Certificate Application, and that the person submitting the Certificate Application on behalf of the Subscriber was authorized to do so. Class 3 organizational Certificates for servers also provide assurances that the Subscriber is entitled to use the domain name listed in the Certificate Application, if a domain name is listed in such Certificate Application.

2.  Processing Your Certificate Application. Upon VeriSign's receipt of the necessary payment and upon completion of authentication procedures required for the Certificate you have purchased, VeriSign will process your Certificate Application. VeriSign will notify you whether your Certificate Application is approved or rejected. If your Certificate Application is approved, VeriSign will issue you a Certificate for your use in accordance with this Subscriber Agreement.  Your use of the PIN from VeriSign to pick up the Certificate or otherwise installing or using the Certificate is considered your acceptance of the Certificate. After you pick up or otherwise install your Certificate, you must review the information in it before using it and promptly notify VeriSign of any errors. Upon receipt of such notice, VeriSign may revoke your Certificate and issue a corrected Certificate.

3.  Obligations Upon Revocation or Expiration. Upon expiration or notice of revocation of your Certificate, you shall no longer use the Certificate for any purpose.  

4.  Ownership.  Except as otherwise set forth herein, all right, title and interest in and to all, (i) registered and unregistered trademarks, service marks and logos; (ii) patents, patent applications, and patentable ideas, inventions, and/or improvements; (iii) trade secrets, proprietary information, and know-how; (iv) all divisions, continuations, reissues, renewals, and extensions thereof now existing or hereafter filed, issued, or acquired; (v) registered and unregistered copyrights including, without limitation, any forms, images, audiovisual displays, text, software and (vi) all other intellectual property, proprietary rights or other rights related to intangible property which are used, developed, comprising, embodied in, or practiced in connection with any of the VeriSign services identified herein ("VeriSign Intellectual Property Rights") are owned by VeriSign or its licensors, and you agree to make no claim of interest in or ownership of any such VeriSign Intellectual Property Rights.  You acknowledge that no title to the VeriSign Intellectual Property Rights is transferred to you, and that you do not obtain any rights, express or implied, in the VeriSign or its licensors' service, other than the rights expressly granted in this Agreement.  To the extent that you create any Derivative Work (any work that is based upon one or more preexisting versions of a work provided to you, such as an enhancement or modification, revision, translation, abridgement, condensation, expansion, collection, compilation or any other form in which such preexisting works may be recast, transformed or adapted) such Derivative Work shall be owned by VeriSign and all right, title and interest in and to each such Derivative Work shall automatically vest in VeriSign.  VeriSign shall have no obligation to grant you any right in any such Derivative Work.  You may not reverse engineer, disassemble or decompile the VeriSign Intellectual Property or make any attempt to obtain source code to the VeriSign Intellectual Property.  You have the right to use the Certificate under the terms and conditions of this Subscriber Agreement.

5.  Modifications to Agreement. Except as otherwise provided in this Subscriber Agreement, you agree, during the term of this Subscriber Agreement, that VeriSign may: (1) revise the terms and conditions of this Subscriber Agreement; and/or (2) change part of the services provided under this Subscriber Agreement at any time. Any such revision or change will be binding and effective thirty (30) days after posting of the revised Subscriber Agreement or change to the service(s) on VeriSign's Web sites, or upon notification to you by e-mail or United States mail.  You agree to periodically review VerriSign's Web sites, including the current version of this Subscriber Agreement available on VeriSign's Web sites, to be aware of any such revisions. If you do not agree with any revision to the Subscriber Agreement, you may terminate this Subscriber Agreement at any time by providing notice to VeriSign.  Notice of your termination will be effective on receipt and processing by VeriSign. Any fees paid by you if you terminate this Subscriber Agreement are nonrefundable.  By continuing to use VeriSign services after any revision to this Subscriber Agreement or change in service(s), you agree to abide by and be bound by any such revisions or changes. VeriSign is not bound by nor should you rely on any representation by (i) any agent, representative or employee of any third party that you may use to apply for VeriSign's services; or in (ii) information posted on VeriSign's Web site of a general informational nature. No employee, contractor, agent or representative of VeriSign is authorized to alter or amend the terms and conditions of this Subscriber Agreement.

6.  Warranties. 

(6.1)  VeriSign Warranties. VeriSign warrants to you that (a) there are no errors introduced by VeriSign in your Certificate information as a result of VeriSign's failure to use reasonable care in creating the Certificate, (b) your Certificate complies in all material respects with the VeriSign CPS, and (c) VeriSign's revocation services and use of a repository conform to the VeriSign CPS in all material aspects. 
 
(6.2) Your Warranty.  You warrant to VeriSign and anyone who relies on your Certificate that (a) all the information you provide to VeriSign in your Certificate Application is accurate; (b) no Certificate information you provided (including your e-mail address) infringes the intellectual property rights of any third parties; (c) the Certificate Application information you provided (including your email address) has not been and will not be used for any unlawful purpose; (d) you have been (since the time of its creation) and will remain the only person possessing your private key and no unauthorized person has had or will have access to your private key; (e) you have been (since the time of its creation) and will remain the only person possessing any challenge phrase), PIN, software, or hardware mechanism protecting your private key and no unauthorized person has had or will have access to the same; (f) you are using your Certificate exclusively for authorized and legal purposes consistent with this Subscriber Agreement; (g) you are using your Certificate as an end-user Subscriber and not as a Certification Authority issuing Certificates, Certification revocation lists, or otherwise; (h) each digital signature created using your private key is your digital signature, and the Certificate has been accepted and is operational (not expired or revoked) at the time the digital signature is created; (i) you manifest assent to this Subscriber Agreement as a condition of obtaining a Certificate.  You also agree that you will not monitor, interfere with, or reverse engineer the technical implementation of the VTN, except with the prior written approval from VeriSign, and shall not otherwise intentionally compromise the security of the VTN.

7.  Disclaimers of Warranties.  YOU AGREE THAT YOUR USE OF VERISIGN'S SERVICE(S) IS SOLELY AT YOUR OWN RISK.  YOU AGREE THAT ALL SUCH SERVICES ARE PROVIDED ON AN "AS IS" AND AS AVAILABLE BASIS, EXCEPT AS OTHERWISE NOTED IN THIS SUBSCRIBER AGREEMENT.  VERISIGN EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.  OTHER THAN THE WARRANTIES AS SET FORTH IN SECTION 6, VERISIGN DOES NOT MAKE ANY WARRANTY THAT THE SERVICE WILL MEET YOUR REQUIRMENTS, OR THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR FREE; NOR DOES VERISIGN MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE OR TO THE ACCURACY OR RELIABILITY OF ANY INFORMATION OBTAINED THROUGH VERISIGN'S SERVICE.  YOU UNDERSTAND AND AGREE THAT ANY MATERIAL AND/OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF VERISIGN'S SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK.  NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM VERISIGN OR THROUGH VERISIGN'S SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLEY MADE HEREIN, YOU MAY NOT RELY ON ANY SUCH INFORMATION OR ADVICE.  TO THE EXTENT JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES, SOME OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.  VERISIGN IS NOT RESPONSIBLE FOR AND SHALL HAVE NO LIABILITY WITH RESPECT TO ANY PRODUCTS AND/OR SERVICES PURCHASED BY YOU FROM A THIRD PARTY.

8.  Indemnity.  You agree to release, indemnify, defend and hold harmless VeriSign and any of its contractors, agents, employees, officers, directors, shareholders, affiliates and assigns from all liabilities, claims, damages, costs and expenses, including reasonable attorney's fees and expenses, of third parties relating to or arising out of (a) this Subscriber Agreement or the breach of your warranties, representations and obligations under this Subscriber Agreement, (b) falsehoods or misrepresentations of fact by you on the Certificate Application, (c) any intellectual property or other proprietary right of any person or entity, (d) failure to disclose a material fact on the Certificate Application if the misrepresentation or omission was made negligently or with intent to deceive any party, (e) failure to protect the private key, or use a trustworthy system, or to take the precautions necessary to prevent the compromise, loss, disclosure, modification or unauthorized use of the private key under the terms of this Subscriber Agreement.  When VeriSign is threatened with suit or sued by a third party, VeriSign may seek written assurances from you concerning your promise to indemnify VeriSign, your failure to provide those assurances may be considered by VeriSign to be a material breach of this Subscriber Agreement.  VeriSign shall have the right to participate in any defense by you of a third-party claim related to your use of any VeriSign services, with counsel of our choice at your own expense.  You shall have sole responsibility to defend VeriSign against any claim, but you must receive VeriSign's prior written consent regarding any related settlement.  The terms of this paragraph will survive any termination or cancellation of this Subscriber Agreement.

9.  Limitations of Liability.
(i)  Limitations under the NetSure Protection Plan.  THE MOST THAT VERISIGN MUST PAY YOU UNDER THE NETSURE PROTECTION PLAN IS THE AMOUNT DETERMINED UNDER THE NETSURE PROTECTION PLAN.  THE LIMITATIONS ON DAMAGES AND PAYMENTS IN THIS SECTION 9(i) DO NOT APPLY TO REFUND PAYMENTS.  DETAILS ON THE NETSURE PROTECTION PLAN CAN BE FOUND AT http://www.verisign.com/repository/netsure_faq/

(ii)  Other Limitations. THIS SECTION 9 (ii) APPLIES TO LIABILITY UNDER CONTRACT (INCLUDING BREACH OF WARRANTY), TORT (INCLUDING NEGLIGENCE AND/OR STRICT LIABILITY), AND ANY OTHER LEGAL OR EQUITABLE FORM OF CLAIM.  IF YOU INITIATE ANY CLAIM, ACTION, SUIT, ARBITRATION, OR OTHER PROCEEDING SEPARATE FROM A REQUEST FOR PAYMENT UNDER THE NETSURE PROTECTION PLAN RELATING TO SERVICES PROVIDED UNDER THIS AGREEMENT, AND TO THE EXTENT PERMITTED BY APPLICABLE LAW, VERISIGN'S TOTAL LIABILITY FOR DAMAGES SUSTAINED BY YOU AND ANY THIRD PARTY FOR ANY USE OR RELIANCE ON A SPECIFIC CERTIFICATE SHALL BE LIMITED, IN THE AGGREGATE, TO THE AMOUNTS SET FORTH BELOW.

Class	Liability Caps
Class 1	One Hundred U.S. Dollars ($ 100.00  US)
Class 2	Five Thousand U.S. Dollars ($ 5,000.00  US)
Class 3	One Hundred Thousand U.S. Dollars ($ 100,000.00  US)

THE LIABILITY LIMITATIONS PROVIDED IN THIS SECTION 9 (ii) SHALL BE THE SAME REGARDLESS OF THE NUMBER OF DIGITAL SIGNATURES, TRANSACTIONS, OR CLAIMS RELATED TO SUCH CERTIFICATE. SUBJECT TO THE NETSURE PROTECTION PLAN, VERISIGN SHALL NOT BE OBLIGATED TO PAY MORE THAN THE TOTAL LIABILITY LIMITATION FOR EACH CERTIFICATE.  THIS SECTION 9 (ii) DOES NOT LIMIT REFUND PAYMENTS OR PAYMENTS UNDER THE NETSURE PROTECTION PLAN. 

.10.  Force Majeure.  Except for payment and indemnity obligations hereunder, neither party shall be deemed in default hereunder, nor shall it hold the other party responsible for, any cessation, interruption or delay in the performance of its obligations hereunder due to earthquake, flood, fire, storm, natural disaster, act of God, war, armed conflict, terrorist action, labor strike, lockout, boycott, provided that the Party relying upon this Section 10 shall have given the other party written notice thereof promptly and, in any event, within five (5) days of discovery thereof and (ii) shall take all reasonable steps reasonably necessary under the circumstances to mitigate the effects of the force majeure event upon which such notice is based; provided further, that in the event a force majeure event described in this Section 16 extends for a period in excess of thirty (30) days in aggregate, the other party may immediately terminate this Subscriber Agreement.

11.  Export. You acknowledge and agree that you shall not import, export, or re-export directly or indirectly, any commodity, including your Certificate, to any country in violation of the laws and regulations of any applicable jurisdiction.  This restriction expressly includes, but is not limited to, the export regulations of the United States of America (the "United States"). Specifically, you shall not download or otherwise export or re-export the Certificate to (i) a national or resident of) Cuba, Iran, Iraq, Libya, Sudan, North Korea, Syria, or Taliban controlled areas of Afghanistan or any other country where such use is prohibited under United States export regulations, or (ii) to anyone on the United States Treasury Department's list of Specially Designated Nationals or the United States Commerce Department's Table of Denial Orders. You agree to the foregoing and represent and warrant that you are not located in, under the control of, or a national or resident of any such country or on any such list.  VERISIGN MAY BE REQUIRED BY LAW TO REPORT TO THE UNITED STATES GOVERNMENT YOUR COMPANY NAME AND ADDRESS IF YOU ARE A NON-UNITED STATES OR CANADA ENTITY OR INDIVIDUAL PURCHASING THE CERTIFICATE.  

12. Severability.  You agree that the terms of this Subscriber Agreement are severable. If any term or provision is declared invalid or unenforceable, in whole or in part, that term or provision will not affect the remainder of this Subscriber Agreement; this Subscriber Agreement will be deemed amended to the extent necessary to make this Subscriber Agreement enforceable, valid and, to the maximum extent possible consistent with applicable law, consistent with the original intentions of the parties; and the remaining terms and provisions will remain in full force and effect.

13. Governing Law.   You and VeriSign agree that any disputes related to the services provided under this Subscriber Agreement shall be governed in all respects by and construed in accordance with the laws of the State of California, United States of America, excluding its conflict of laws rules.

14.  Dispute Resolution.  To the extent permitted by law, before you may invoke any dispute resolution mechanism with respect to a dispute involving any aspect of this Subscriber Agreement, you shall notify VeriSign, and any other party to the dispute for the purpose of seeking dispute resolution.  If the dispute is not resolved within sixty (60) days after the initial notice, then a party may proceed in accordance with the following:

(i)  When each party to the dispute is a Canadian or U.S. resident or organization situated or doing business in Canada or the United States.  All suits to enforce any provision of this Subscriber Agreement or arising in connection with this Subscriber Agreement shall be brought in the United States District Court for the Northern District of California or the Superior or Municipal Court in and for the County of Santa Clara, California, U.S.A.  The parties agree that such courts shall have exclusive in personam jurisdiction and venue and the parties submit to the exclusive in personam jurisdiction and venue of such courts. The parties further waive any right to a jury trial regarding any action brought in connection with this Subscriber Agreement.

(ii)  Where one or more parties to the dispute is not a Canadian or U.S. resident or organization situated or doing business in Canada or the United States. All disputes arising in connection with this Subscriber Agreement shall be finally settled under the Rules of Conciliation and Arbitration of the International Chamber of Commerce (ICC) as modified as necessary to reflect the provisions herein by one or more arbitrators.  The place of arbitration shall be in New York or San Francisco, U.S.A., and the proceedings shall be conducted in English.  In cases involving a single arbiter, that single arbiter shall be appointed by mutual agreement of the parties.  If the parties fail to agree to an arbiter within fifteen (15) days, the ICC shall choose an arbiter knowledgeable in computer software law, information security and cryptography or otherwise having special qualifications in the field, such as a lawyer, academician, or judge in common law jurisdiction.  Nothing in this Subscriber Agreement will be deemed as preventing either party from seeking injunctive relief (or any other provisional remedy) from any court having jurisdiction over the parities and the subject matter of this dispute as is necessary to protect either party's name, proprietary information, trade secret, know-how, or, or any other intellectual property rights.

15.  Non-Assignment.   Except as otherwise set forth herein, your rights under this Agreement are not assignable or transferable.  Any attempt by your creditors to obtain an interest in your rights under this Subscriber Agreement, whether by attachment, levy, garnishment or otherwise, renders this Subscriber Agreement voidable at VeriSign's option.  

16.  Notices.  You will make all notices, demands or requests to VeriSign with respect to this Subscriber Agreement in writing to:  Attn:  General Counsel, VeriSign, Inc., 487 East Middlefield Road, Mountain View, CA 94043.

17.  Survival.  This Subscriber Agreement shall be applicable for as long as the Certificate remains valid and you have not breached any provision of this Subscriber Agreement.

18.  Privacy.  You agree that VeriSign may place in your Certificate certain information that you provide for inclusion in your Certificate.  You also agree that VeriSign may publish your Certificate and information about its status in VeriSign's repository of Certificate information and make this information available to other repositories.

</textarea></center>
</TD>
</TR>
</TABLE>
</TD></TR>
</TABLE>
<BR><BR>
<!-- VSSKENDPOLICYVAL#show#2 -->
