#	GNUmakefile 
#       Developed by Abhay Ranade
#	$Id: GNUmakefile,v 1.2.348.1 2001/02/12 18:05:56 aabhyank Exp $
#

ECAS_HOME = ../../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


ifeq ($(CISCO), 1)
SPECIAL_sparc_DIRS = cisco
endif

SUBDIRS = NPPTAv3 N6pta vsnpsetup


include $(ECAS_RULES_DIR)/directory.cfg

