#	GNUmakefile 
#       Developed by Abhay Ranade
#	$Id: GNUmakefile,v 1.8.174.2 2006/11/18 09:39:01 schenna Exp $
#

ECAS_HOME = ../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg

SUBDIRS = cgi-bin fdf htmldocs htmldocs/error htmldocs/graphics htmldocs/client \
		htmldocs/client/graphics htmldocs/client/help htmldocs/client/help/faq \
		htmldocs/client/help/concepts htmldocs/client/help/popup htmldocs/client/help/tasks \
		htmldocs/client/help/tasks/ie3 htmldocs/client/help/tasks/ie4 \
		htmldocs/client/help/tasks/ie5 htmldocs/client/help/tasks/netscape3 \
		htmldocs/client/help/tasks/netscape4 htmldocs/client/help/tasks/netscape45 \
                pta htmldocs/client/help/apps htmldocs/client/help/fet ptaSmLogin


include $(ECAS_RULES_DIR)/directory.cfg

