// SignAtrb.idl : IDL source for SignAtrb.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SignAtrb.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(71C6919D-F9C0-11D2-8344-0060B0B32E16),
		dual,
		helpstring("ISignAttributes Interface"),
		pointer_default(unique)
	]
	interface ISignAttributes : IDispatch
	{
		[propput, id(1), helpstring("property userCertificate")] HRESULT userCertificate([in] BSTR newVal);
		[propget, id(2), helpstring("property EncUserCertificate")] HRESULT EncUserCertificate([out, retval] BSTR *pVal);
		[propget, id(3), helpstring("property EncUserSMIMECertificate")] HRESULT EncUserSMIMECertificate([out, retval] BSTR *pVal);
		[propget, id(4), helpstring("property ChallengePhrase")] HRESULT ChallengePhrase([out, retval] BSTR *pVal);
		[propput, id(4), helpstring("property ChallengePhrase")] HRESULT ChallengePhrase([in] BSTR newVal);
	//	[propget, id(5), helpstring("property HostName")] HRESULT HostName([out, retval] BSTR *pVal);
	//	[propput, id(5), helpstring("property HostName")] HRESULT HostName([in] BSTR newVal);
		[propget, id(6), helpstring("property AuthEncUserSMIMECertificate")] HRESULT AuthEncUserSMIMECertificate([out, retval] BSTR *pVal);
		[propget, id(7), helpstring("property SMIMECapabilityBlob")] HRESULT SMIMECapabilityBlob(USHORT *cbSMIMECapabilityBlobSize, [out, retval] BYTE *pVal);
	};

[
	uuid(71C69191-F9C0-11D2-8344-0060B0B32E16),
	version(1.0),
	helpstring("SignAtrb 1.0 Type Library")
]
library SIGNATRBLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(71C6919E-F9C0-11D2-8344-0060B0B32E16),
		helpstring("SignAttributes Class")
	]
	coclass SignAttributes
	{
		[default] interface ISignAttributes;
	};
};
