/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Header for class java/lang/reflect/Array */

#ifndef _java_lang_reflect_Array_H_
#define _java_lang_reflect_Array_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct java_lang_Class;
struct java_lang_Object;
struct java_lang_Class;

/*******************************************************************************
 * Class java/lang/reflect/Array
 ******************************************************************************/

typedef struct java_lang_reflect_Array java_lang_reflect_Array;

#define classname_java_lang_reflect_Array	"java/lang/reflect/Array"

#define class_java_lang_reflect_Array(env) \
	((struct java_lang_Class*)JRI_FindClass(env, classname_java_lang_reflect_Array))

/*******************************************************************************
 * Public Methods
 ******************************************************************************/

#ifdef DEBUG

/*** public static newInstance (Ljava/lang/Class;I)Ljava/lang/Object; ***/
extern JRI_PUBLIC_API(struct java_lang_Object *)
java_lang_reflect_Array_newInstance(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jint b);

/*** public static newInstance (Ljava/lang/Class;[I)Ljava/lang/Object; ***/
extern JRI_PUBLIC_API(struct java_lang_Object *)
java_lang_reflect_Array_newInstance_1(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jintArray b);

/*** public static native getLength (Ljava/lang/Object;)I ***/
extern JRI_PUBLIC_API(jint)
java_lang_reflect_Array_getLength(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a);

/*** public static native get (Ljava/lang/Object;I)Ljava/lang/Object; ***/
extern JRI_PUBLIC_API(struct java_lang_Object *)
java_lang_reflect_Array_get(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getBoolean (Ljava/lang/Object;I)Z ***/
extern JRI_PUBLIC_API(jbool)
java_lang_reflect_Array_getBoolean(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getByte (Ljava/lang/Object;I)B ***/
extern JRI_PUBLIC_API(jbyte)
java_lang_reflect_Array_getByte(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getChar (Ljava/lang/Object;I)C ***/
extern JRI_PUBLIC_API(jchar)
java_lang_reflect_Array_getChar(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getShort (Ljava/lang/Object;I)S ***/
extern JRI_PUBLIC_API(jshort)
java_lang_reflect_Array_getShort(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getInt (Ljava/lang/Object;I)I ***/
extern JRI_PUBLIC_API(jint)
java_lang_reflect_Array_getInt(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getLong (Ljava/lang/Object;I)J ***/
extern JRI_PUBLIC_API(jlong)
java_lang_reflect_Array_getLong(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getFloat (Ljava/lang/Object;I)F ***/
extern JRI_PUBLIC_API(jfloat)
java_lang_reflect_Array_getFloat(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getDouble (Ljava/lang/Object;I)D ***/
extern JRI_PUBLIC_API(jdouble)
java_lang_reflect_Array_getDouble(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native set (Ljava/lang/Object;ILjava/lang/Object;)V ***/
extern JRI_PUBLIC_API(void)
java_lang_reflect_Array_set(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, struct java_lang_Object *c);

/*** public static native setBoolean (Ljava/lang/Object;IZ)V ***/
extern JRI_PUBLIC_API(void)
java_lang_reflect_Array_setBoolean(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jbool c);

/*** public static native setByte (Ljava/lang/Object;IB)V ***/
extern JRI_PUBLIC_API(void)
java_lang_reflect_Array_setByte(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jbyte c);

/*** public static native setChar (Ljava/lang/Object;IC)V ***/
extern JRI_PUBLIC_API(void)
java_lang_reflect_Array_setChar(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jchar c);

/*** public static native setShort (Ljava/lang/Object;IS)V ***/
extern JRI_PUBLIC_API(void)
java_lang_reflect_Array_setShort(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jshort c);

/*** public static native setInt (Ljava/lang/Object;II)V ***/
extern JRI_PUBLIC_API(void)
java_lang_reflect_Array_setInt(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jint c);

/*** public static native setLong (Ljava/lang/Object;IJ)V ***/
extern JRI_PUBLIC_API(void)
java_lang_reflect_Array_setLong(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jlong c);

/*** public static native setFloat (Ljava/lang/Object;IF)V ***/
extern JRI_PUBLIC_API(void)
java_lang_reflect_Array_setFloat(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jfloat c);

/*** public static native setDouble (Ljava/lang/Object;ID)V ***/
extern JRI_PUBLIC_API(void)
java_lang_reflect_Array_setDouble(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jdouble c);

#else /* !DEBUG */

/*** public static newInstance (Ljava/lang/Class;I)Ljava/lang/Object; ***/
#define java_lang_reflect_Array_newInstance(env, clazz, a, b) \
	((struct java_lang_Object *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_newInstance, a, b))

/*** public static newInstance (Ljava/lang/Class;[I)Ljava/lang/Object; ***/
#define java_lang_reflect_Array_newInstance_1(env, clazz, a, b) \
	((struct java_lang_Object *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_newInstance_1, a, b))

/*** public static native getLength (Ljava/lang/Object;)I ***/
#define java_lang_reflect_Array_getLength(env, clazz, a) \
	((jint)JRI_CallStaticMethodInt(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getLength, a))

/*** public static native get (Ljava/lang/Object;I)Ljava/lang/Object; ***/
#define java_lang_reflect_Array_get(env, clazz, a, b) \
	((struct java_lang_Object *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_get, a, b))

/*** public static native getBoolean (Ljava/lang/Object;I)Z ***/
#define java_lang_reflect_Array_getBoolean(env, clazz, a, b) \
	((jbool)JRI_CallStaticMethodBoolean(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getBoolean, a, b))

/*** public static native getByte (Ljava/lang/Object;I)B ***/
#define java_lang_reflect_Array_getByte(env, clazz, a, b) \
	((jbyte)JRI_CallStaticMethodByte(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getByte, a, b))

/*** public static native getChar (Ljava/lang/Object;I)C ***/
#define java_lang_reflect_Array_getChar(env, clazz, a, b) \
	((jchar)JRI_CallStaticMethodChar(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getChar, a, b))

/*** public static native getShort (Ljava/lang/Object;I)S ***/
#define java_lang_reflect_Array_getShort(env, clazz, a, b) \
	((jshort)JRI_CallStaticMethodShort(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getShort, a, b))

/*** public static native getInt (Ljava/lang/Object;I)I ***/
#define java_lang_reflect_Array_getInt(env, clazz, a, b) \
	((jint)JRI_CallStaticMethodInt(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getInt, a, b))

/*** public static native getLong (Ljava/lang/Object;I)J ***/
#define java_lang_reflect_Array_getLong(env, clazz, a, b) \
	((jlong)JRI_CallStaticMethodLong(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getLong, a, b))

/*** public static native getFloat (Ljava/lang/Object;I)F ***/
#define java_lang_reflect_Array_getFloat(env, clazz, a, b) \
	((jfloat)JRI_CallStaticMethodFloat(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getFloat, a, b))

/*** public static native getDouble (Ljava/lang/Object;I)D ***/
#define java_lang_reflect_Array_getDouble(env, clazz, a, b) \
	((jdouble)JRI_CallStaticMethodDouble(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_getDouble, a, b))

/*** public static native set (Ljava/lang/Object;ILjava/lang/Object;)V ***/
#define java_lang_reflect_Array_set(env, clazz, a, b, c) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_set, a, b, c))

/*** public static native setBoolean (Ljava/lang/Object;IZ)V ***/
#define java_lang_reflect_Array_setBoolean(env, clazz, a, b, c) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setBoolean, a, b, c))

/*** public static native setByte (Ljava/lang/Object;IB)V ***/
#define java_lang_reflect_Array_setByte(env, clazz, a, b, c) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setByte, a, b, c))

/*** public static native setChar (Ljava/lang/Object;IC)V ***/
#define java_lang_reflect_Array_setChar(env, clazz, a, b, c) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setChar, a, b, c))

/*** public static native setShort (Ljava/lang/Object;IS)V ***/
#define java_lang_reflect_Array_setShort(env, clazz, a, b, c) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setShort, a, b, c))

/*** public static native setInt (Ljava/lang/Object;II)V ***/
#define java_lang_reflect_Array_setInt(env, clazz, a, b, c) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setInt, a, b, c))

/*** public static native setLong (Ljava/lang/Object;IJ)V ***/
#define java_lang_reflect_Array_setLong(env, clazz, a, b, c) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setLong, a, b, c))

/*** public static native setFloat (Ljava/lang/Object;IF)V ***/
#define java_lang_reflect_Array_setFloat(env, clazz, a, b, c) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setFloat, a, b, c))

/*** public static native setDouble (Ljava/lang/Object;ID)V ***/
#define java_lang_reflect_Array_setDouble(env, clazz, a, b, c) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_setDouble, a, b, c))

#endif /* !DEBUG*/

/*** public static newInstance (Ljava/lang/Class;I)Ljava/lang/Object; ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_newInstance;
#define name_java_lang_reflect_Array_newInstance	"newInstance"
#define sig_java_lang_reflect_Array_newInstance 	"(Ljava/lang/Class;I)Ljava/lang/Object;"
#define use_java_lang_reflect_Array_newInstance(env, clazz)	\
	(methodID_java_lang_reflect_Array_newInstance =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_newInstance,	\
			sig_java_lang_reflect_Array_newInstance))
#define unuse_java_lang_reflect_Array_newInstance(env, clazz)	\
	(methodID_java_lang_reflect_Array_newInstance = JRIUninitialized)

/*** public static newInstance (Ljava/lang/Class;[I)Ljava/lang/Object; ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_newInstance_1;
#define name_java_lang_reflect_Array_newInstance_1	"newInstance"
#define sig_java_lang_reflect_Array_newInstance_1 	"(Ljava/lang/Class;[I)Ljava/lang/Object;"
#define use_java_lang_reflect_Array_newInstance_1(env, clazz)	\
	(methodID_java_lang_reflect_Array_newInstance_1 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_newInstance_1,	\
			sig_java_lang_reflect_Array_newInstance_1))
#define unuse_java_lang_reflect_Array_newInstance_1(env, clazz)	\
	(methodID_java_lang_reflect_Array_newInstance_1 = JRIUninitialized)

/*** public static native getLength (Ljava/lang/Object;)I ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_getLength;
#define name_java_lang_reflect_Array_getLength	"getLength"
#define sig_java_lang_reflect_Array_getLength 	"(Ljava/lang/Object;)I"
#define use_java_lang_reflect_Array_getLength(env, clazz)	\
	(methodID_java_lang_reflect_Array_getLength =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_getLength,	\
			sig_java_lang_reflect_Array_getLength))
#define unuse_java_lang_reflect_Array_getLength(env, clazz)	\
	(methodID_java_lang_reflect_Array_getLength = JRIUninitialized)

/*** public static native get (Ljava/lang/Object;I)Ljava/lang/Object; ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_get;
#define name_java_lang_reflect_Array_get	"get"
#define sig_java_lang_reflect_Array_get 	"(Ljava/lang/Object;I)Ljava/lang/Object;"
#define use_java_lang_reflect_Array_get(env, clazz)	\
	(methodID_java_lang_reflect_Array_get =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_get,	\
			sig_java_lang_reflect_Array_get))
#define unuse_java_lang_reflect_Array_get(env, clazz)	\
	(methodID_java_lang_reflect_Array_get = JRIUninitialized)

/*** public static native getBoolean (Ljava/lang/Object;I)Z ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_getBoolean;
#define name_java_lang_reflect_Array_getBoolean	"getBoolean"
#define sig_java_lang_reflect_Array_getBoolean 	"(Ljava/lang/Object;I)Z"
#define use_java_lang_reflect_Array_getBoolean(env, clazz)	\
	(methodID_java_lang_reflect_Array_getBoolean =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_getBoolean,	\
			sig_java_lang_reflect_Array_getBoolean))
#define unuse_java_lang_reflect_Array_getBoolean(env, clazz)	\
	(methodID_java_lang_reflect_Array_getBoolean = JRIUninitialized)

/*** public static native getByte (Ljava/lang/Object;I)B ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_getByte;
#define name_java_lang_reflect_Array_getByte	"getByte"
#define sig_java_lang_reflect_Array_getByte 	"(Ljava/lang/Object;I)B"
#define use_java_lang_reflect_Array_getByte(env, clazz)	\
	(methodID_java_lang_reflect_Array_getByte =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_getByte,	\
			sig_java_lang_reflect_Array_getByte))
#define unuse_java_lang_reflect_Array_getByte(env, clazz)	\
	(methodID_java_lang_reflect_Array_getByte = JRIUninitialized)

/*** public static native getChar (Ljava/lang/Object;I)C ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_getChar;
#define name_java_lang_reflect_Array_getChar	"getChar"
#define sig_java_lang_reflect_Array_getChar 	"(Ljava/lang/Object;I)C"
#define use_java_lang_reflect_Array_getChar(env, clazz)	\
	(methodID_java_lang_reflect_Array_getChar =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_getChar,	\
			sig_java_lang_reflect_Array_getChar))
#define unuse_java_lang_reflect_Array_getChar(env, clazz)	\
	(methodID_java_lang_reflect_Array_getChar = JRIUninitialized)

/*** public static native getShort (Ljava/lang/Object;I)S ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_getShort;
#define name_java_lang_reflect_Array_getShort	"getShort"
#define sig_java_lang_reflect_Array_getShort 	"(Ljava/lang/Object;I)S"
#define use_java_lang_reflect_Array_getShort(env, clazz)	\
	(methodID_java_lang_reflect_Array_getShort =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_getShort,	\
			sig_java_lang_reflect_Array_getShort))
#define unuse_java_lang_reflect_Array_getShort(env, clazz)	\
	(methodID_java_lang_reflect_Array_getShort = JRIUninitialized)

/*** public static native getInt (Ljava/lang/Object;I)I ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_getInt;
#define name_java_lang_reflect_Array_getInt	"getInt"
#define sig_java_lang_reflect_Array_getInt 	"(Ljava/lang/Object;I)I"
#define use_java_lang_reflect_Array_getInt(env, clazz)	\
	(methodID_java_lang_reflect_Array_getInt =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_getInt,	\
			sig_java_lang_reflect_Array_getInt))
#define unuse_java_lang_reflect_Array_getInt(env, clazz)	\
	(methodID_java_lang_reflect_Array_getInt = JRIUninitialized)

/*** public static native getLong (Ljava/lang/Object;I)J ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_getLong;
#define name_java_lang_reflect_Array_getLong	"getLong"
#define sig_java_lang_reflect_Array_getLong 	"(Ljava/lang/Object;I)J"
#define use_java_lang_reflect_Array_getLong(env, clazz)	\
	(methodID_java_lang_reflect_Array_getLong =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_getLong,	\
			sig_java_lang_reflect_Array_getLong))
#define unuse_java_lang_reflect_Array_getLong(env, clazz)	\
	(methodID_java_lang_reflect_Array_getLong = JRIUninitialized)

/*** public static native getFloat (Ljava/lang/Object;I)F ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_getFloat;
#define name_java_lang_reflect_Array_getFloat	"getFloat"
#define sig_java_lang_reflect_Array_getFloat 	"(Ljava/lang/Object;I)F"
#define use_java_lang_reflect_Array_getFloat(env, clazz)	\
	(methodID_java_lang_reflect_Array_getFloat =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_getFloat,	\
			sig_java_lang_reflect_Array_getFloat))
#define unuse_java_lang_reflect_Array_getFloat(env, clazz)	\
	(methodID_java_lang_reflect_Array_getFloat = JRIUninitialized)

/*** public static native getDouble (Ljava/lang/Object;I)D ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_getDouble;
#define name_java_lang_reflect_Array_getDouble	"getDouble"
#define sig_java_lang_reflect_Array_getDouble 	"(Ljava/lang/Object;I)D"
#define use_java_lang_reflect_Array_getDouble(env, clazz)	\
	(methodID_java_lang_reflect_Array_getDouble =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_getDouble,	\
			sig_java_lang_reflect_Array_getDouble))
#define unuse_java_lang_reflect_Array_getDouble(env, clazz)	\
	(methodID_java_lang_reflect_Array_getDouble = JRIUninitialized)

/*** public static native set (Ljava/lang/Object;ILjava/lang/Object;)V ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_set;
#define name_java_lang_reflect_Array_set	"set"
#define sig_java_lang_reflect_Array_set 	"(Ljava/lang/Object;ILjava/lang/Object;)V"
#define use_java_lang_reflect_Array_set(env, clazz)	\
	(methodID_java_lang_reflect_Array_set =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_set,	\
			sig_java_lang_reflect_Array_set))
#define unuse_java_lang_reflect_Array_set(env, clazz)	\
	(methodID_java_lang_reflect_Array_set = JRIUninitialized)

/*** public static native setBoolean (Ljava/lang/Object;IZ)V ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_setBoolean;
#define name_java_lang_reflect_Array_setBoolean	"setBoolean"
#define sig_java_lang_reflect_Array_setBoolean 	"(Ljava/lang/Object;IZ)V"
#define use_java_lang_reflect_Array_setBoolean(env, clazz)	\
	(methodID_java_lang_reflect_Array_setBoolean =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_setBoolean,	\
			sig_java_lang_reflect_Array_setBoolean))
#define unuse_java_lang_reflect_Array_setBoolean(env, clazz)	\
	(methodID_java_lang_reflect_Array_setBoolean = JRIUninitialized)

/*** public static native setByte (Ljava/lang/Object;IB)V ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_setByte;
#define name_java_lang_reflect_Array_setByte	"setByte"
#define sig_java_lang_reflect_Array_setByte 	"(Ljava/lang/Object;IB)V"
#define use_java_lang_reflect_Array_setByte(env, clazz)	\
	(methodID_java_lang_reflect_Array_setByte =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_setByte,	\
			sig_java_lang_reflect_Array_setByte))
#define unuse_java_lang_reflect_Array_setByte(env, clazz)	\
	(methodID_java_lang_reflect_Array_setByte = JRIUninitialized)

/*** public static native setChar (Ljava/lang/Object;IC)V ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_setChar;
#define name_java_lang_reflect_Array_setChar	"setChar"
#define sig_java_lang_reflect_Array_setChar 	"(Ljava/lang/Object;IC)V"
#define use_java_lang_reflect_Array_setChar(env, clazz)	\
	(methodID_java_lang_reflect_Array_setChar =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_setChar,	\
			sig_java_lang_reflect_Array_setChar))
#define unuse_java_lang_reflect_Array_setChar(env, clazz)	\
	(methodID_java_lang_reflect_Array_setChar = JRIUninitialized)

/*** public static native setShort (Ljava/lang/Object;IS)V ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_setShort;
#define name_java_lang_reflect_Array_setShort	"setShort"
#define sig_java_lang_reflect_Array_setShort 	"(Ljava/lang/Object;IS)V"
#define use_java_lang_reflect_Array_setShort(env, clazz)	\
	(methodID_java_lang_reflect_Array_setShort =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_setShort,	\
			sig_java_lang_reflect_Array_setShort))
#define unuse_java_lang_reflect_Array_setShort(env, clazz)	\
	(methodID_java_lang_reflect_Array_setShort = JRIUninitialized)

/*** public static native setInt (Ljava/lang/Object;II)V ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_setInt;
#define name_java_lang_reflect_Array_setInt	"setInt"
#define sig_java_lang_reflect_Array_setInt 	"(Ljava/lang/Object;II)V"
#define use_java_lang_reflect_Array_setInt(env, clazz)	\
	(methodID_java_lang_reflect_Array_setInt =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_setInt,	\
			sig_java_lang_reflect_Array_setInt))
#define unuse_java_lang_reflect_Array_setInt(env, clazz)	\
	(methodID_java_lang_reflect_Array_setInt = JRIUninitialized)

/*** public static native setLong (Ljava/lang/Object;IJ)V ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_setLong;
#define name_java_lang_reflect_Array_setLong	"setLong"
#define sig_java_lang_reflect_Array_setLong 	"(Ljava/lang/Object;IJ)V"
#define use_java_lang_reflect_Array_setLong(env, clazz)	\
	(methodID_java_lang_reflect_Array_setLong =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_setLong,	\
			sig_java_lang_reflect_Array_setLong))
#define unuse_java_lang_reflect_Array_setLong(env, clazz)	\
	(methodID_java_lang_reflect_Array_setLong = JRIUninitialized)

/*** public static native setFloat (Ljava/lang/Object;IF)V ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_setFloat;
#define name_java_lang_reflect_Array_setFloat	"setFloat"
#define sig_java_lang_reflect_Array_setFloat 	"(Ljava/lang/Object;IF)V"
#define use_java_lang_reflect_Array_setFloat(env, clazz)	\
	(methodID_java_lang_reflect_Array_setFloat =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_setFloat,	\
			sig_java_lang_reflect_Array_setFloat))
#define unuse_java_lang_reflect_Array_setFloat(env, clazz)	\
	(methodID_java_lang_reflect_Array_setFloat = JRIUninitialized)

/*** public static native setDouble (Ljava/lang/Object;ID)V ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_setDouble;
#define name_java_lang_reflect_Array_setDouble	"setDouble"
#define sig_java_lang_reflect_Array_setDouble 	"(Ljava/lang/Object;ID)V"
#define use_java_lang_reflect_Array_setDouble(env, clazz)	\
	(methodID_java_lang_reflect_Array_setDouble =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_setDouble,	\
			sig_java_lang_reflect_Array_setDouble))
#define unuse_java_lang_reflect_Array_setDouble(env, clazz)	\
	(methodID_java_lang_reflect_Array_setDouble = JRIUninitialized)

/*******************************************************************************
 * IMPLEMENTATION SECTION: 
 * Define the IMPLEMENT_java_lang_reflect_Array symbol 
 * if you intend to implement the native methods of this class. This 
 * symbol makes the private and protected methods available. You should 
 * also call the register_java_lang_reflect_Array routine 
 * to make your native methods available.
 ******************************************************************************/

extern JRI_PUBLIC_API(struct java_lang_Class*)
use_java_lang_reflect_Array(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unuse_java_lang_reflect_Array(JRIEnv* env);

extern JRI_PUBLIC_API(struct java_lang_Class*)
register_java_lang_reflect_Array(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unregister_java_lang_reflect_Array(JRIEnv* env);

#ifdef IMPLEMENT_java_lang_reflect_Array

/*******************************************************************************
 * Native Methods: 
 * These are the signatures of the native methods which you must implement.
 ******************************************************************************/

/*** public static native getLength (Ljava/lang/Object;)I ***/
extern JRI_PUBLIC_API(jint)
native_java_lang_reflect_Array_getLength(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a);

/*** public static native get (Ljava/lang/Object;I)Ljava/lang/Object; ***/
extern JRI_PUBLIC_API(struct java_lang_Object *)
native_java_lang_reflect_Array_get(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getBoolean (Ljava/lang/Object;I)Z ***/
extern JRI_PUBLIC_API(jbool)
native_java_lang_reflect_Array_getBoolean(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getByte (Ljava/lang/Object;I)B ***/
extern JRI_PUBLIC_API(jbyte)
native_java_lang_reflect_Array_getByte(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getChar (Ljava/lang/Object;I)C ***/
extern JRI_PUBLIC_API(jchar)
native_java_lang_reflect_Array_getChar(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getShort (Ljava/lang/Object;I)S ***/
extern JRI_PUBLIC_API(jshort)
native_java_lang_reflect_Array_getShort(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getInt (Ljava/lang/Object;I)I ***/
extern JRI_PUBLIC_API(jint)
native_java_lang_reflect_Array_getInt(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getLong (Ljava/lang/Object;I)J ***/
extern JRI_PUBLIC_API(jlong)
native_java_lang_reflect_Array_getLong(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getFloat (Ljava/lang/Object;I)F ***/
extern JRI_PUBLIC_API(jfloat)
native_java_lang_reflect_Array_getFloat(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native getDouble (Ljava/lang/Object;I)D ***/
extern JRI_PUBLIC_API(jdouble)
native_java_lang_reflect_Array_getDouble(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b);

/*** public static native set (Ljava/lang/Object;ILjava/lang/Object;)V ***/
extern JRI_PUBLIC_API(void)
native_java_lang_reflect_Array_set(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, struct java_lang_Object *c);

/*** public static native setBoolean (Ljava/lang/Object;IZ)V ***/
extern JRI_PUBLIC_API(void)
native_java_lang_reflect_Array_setBoolean(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jbool c);

/*** public static native setByte (Ljava/lang/Object;IB)V ***/
extern JRI_PUBLIC_API(void)
native_java_lang_reflect_Array_setByte(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jbyte c);

/*** public static native setChar (Ljava/lang/Object;IC)V ***/
extern JRI_PUBLIC_API(void)
native_java_lang_reflect_Array_setChar(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jchar c);

/*** public static native setShort (Ljava/lang/Object;IS)V ***/
extern JRI_PUBLIC_API(void)
native_java_lang_reflect_Array_setShort(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jshort c);

/*** public static native setInt (Ljava/lang/Object;II)V ***/
extern JRI_PUBLIC_API(void)
native_java_lang_reflect_Array_setInt(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jint c);

/*** public static native setLong (Ljava/lang/Object;IJ)V ***/
extern JRI_PUBLIC_API(void)
native_java_lang_reflect_Array_setLong(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jlong c);

/*** public static native setFloat (Ljava/lang/Object;IF)V ***/
extern JRI_PUBLIC_API(void)
native_java_lang_reflect_Array_setFloat(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jfloat c);

/*** public static native setDouble (Ljava/lang/Object;ID)V ***/
extern JRI_PUBLIC_API(void)
native_java_lang_reflect_Array_setDouble(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jdouble c);

/*** private static native newArray (Ljava/lang/Class;I)Ljava/lang/Object; ***/
extern JRI_PUBLIC_API(struct java_lang_Object *)
native_java_lang_reflect_Array_newArray(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jint b);

/*** private static native multiNewArray (Ljava/lang/Class;[I)Ljava/lang/Object; ***/
extern JRI_PUBLIC_API(struct java_lang_Object *)
native_java_lang_reflect_Array_multiNewArray(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jintArray b);

/*******************************************************************************
 * Implementation Methods: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** private <init> ()V ***/
extern JRI_PUBLIC_API(struct java_lang_reflect_Array*)
java_lang_reflect_Array_new(JRIEnv* env, struct java_lang_Class* clazz);

/*** private static native newArray (Ljava/lang/Class;I)Ljava/lang/Object; ***/
extern JRI_PUBLIC_API(struct java_lang_Object *)
java_lang_reflect_Array_newArray(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jint b);

/*** private static native multiNewArray (Ljava/lang/Class;[I)Ljava/lang/Object; ***/
extern JRI_PUBLIC_API(struct java_lang_Object *)
java_lang_reflect_Array_multiNewArray(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jintArray b);

#else /* !DEBUG */

/*** private <init> ()V ***/
#define java_lang_reflect_Array_new(env, clazz)	\
	((struct java_lang_reflect_Array*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_reflect_Array_new))

/*** private static native newArray (Ljava/lang/Class;I)Ljava/lang/Object; ***/
#define java_lang_reflect_Array_newArray(env, clazz, a, b) \
	((struct java_lang_Object *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_newArray, a, b))

/*** private static native multiNewArray (Ljava/lang/Class;[I)Ljava/lang/Object; ***/
#define java_lang_reflect_Array_multiNewArray(env, clazz, a, b) \
	((struct java_lang_Object *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_reflect_Array_multiNewArray, a, b))

#endif /* !DEBUG*/

/*** private <init> ()V ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_new;
#define name_java_lang_reflect_Array_new	"<init>"
#define sig_java_lang_reflect_Array_new 	"()V"
#define use_java_lang_reflect_Array_new(env, clazz)	\
	(methodID_java_lang_reflect_Array_new =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_lang_reflect_Array_new,	\
			sig_java_lang_reflect_Array_new))
#define unuse_java_lang_reflect_Array_new(env, clazz)	\
	(methodID_java_lang_reflect_Array_new = JRIUninitialized)

/*** private static native newArray (Ljava/lang/Class;I)Ljava/lang/Object; ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_newArray;
#define name_java_lang_reflect_Array_newArray	"newArray"
#define sig_java_lang_reflect_Array_newArray 	"(Ljava/lang/Class;I)Ljava/lang/Object;"
#define use_java_lang_reflect_Array_newArray(env, clazz)	\
	(methodID_java_lang_reflect_Array_newArray =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_newArray,	\
			sig_java_lang_reflect_Array_newArray))
#define unuse_java_lang_reflect_Array_newArray(env, clazz)	\
	(methodID_java_lang_reflect_Array_newArray = JRIUninitialized)

/*** private static native multiNewArray (Ljava/lang/Class;[I)Ljava/lang/Object; ***/
extern JRIMethodID FAR methodID_java_lang_reflect_Array_multiNewArray;
#define name_java_lang_reflect_Array_multiNewArray	"multiNewArray"
#define sig_java_lang_reflect_Array_multiNewArray 	"(Ljava/lang/Class;[I)Ljava/lang/Object;"
#define use_java_lang_reflect_Array_multiNewArray(env, clazz)	\
	(methodID_java_lang_reflect_Array_multiNewArray =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_lang_reflect_Array_multiNewArray,	\
			sig_java_lang_reflect_Array_multiNewArray))
#define unuse_java_lang_reflect_Array_multiNewArray(env, clazz)	\
	(methodID_java_lang_reflect_Array_multiNewArray = JRIUninitialized)

#endif /* IMPLEMENT_java_lang_reflect_Array */

#ifdef __cplusplus
} /* extern "C" */

/*******************************************************************************
 * C++ Definitions
 ******************************************************************************/

#include "java_lang_Object.h"

struct java_lang_reflect_Array : virtual public java_lang_Object {

	static struct java_lang_Class* _use(JRIEnv* env) {
		return use_java_lang_reflect_Array(env);
	}

	static void _unuse(JRIEnv* env) {
		unuse_java_lang_reflect_Array(env);
	}

	static struct java_lang_Class* _register(JRIEnv* env) {
		return register_java_lang_reflect_Array(env);
	}

	static void _unregister(JRIEnv* env) {
		unregister_java_lang_reflect_Array(env);
	}

	static struct java_lang_Class* _class(JRIEnv* env) {
		return class_java_lang_reflect_Array(env);
	}

	/* Public Methods */
	/*** public static newInstance (Ljava/lang/Class;I)Ljava/lang/Object; ***/
	static struct java_lang_Object * newInstance(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jint b) {
		return java_lang_reflect_Array_newInstance(env, clazz, a, b);
	}

	/*** public static newInstance (Ljava/lang/Class;[I)Ljava/lang/Object; ***/
	static struct java_lang_Object * newInstance(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jintArray b) {
		return java_lang_reflect_Array_newInstance_1(env, clazz, a, b);
	}

	/*** public static native getLength (Ljava/lang/Object;)I ***/
	static jint getLength(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a) {
		return java_lang_reflect_Array_getLength(env, clazz, a);
	}

	/*** public static native get (Ljava/lang/Object;I)Ljava/lang/Object; ***/
	static struct java_lang_Object * get(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
		return java_lang_reflect_Array_get(env, clazz, a, b);
	}

	/*** public static native getBoolean (Ljava/lang/Object;I)Z ***/
	static jbool getBoolean(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
		return java_lang_reflect_Array_getBoolean(env, clazz, a, b);
	}

	/*** public static native getByte (Ljava/lang/Object;I)B ***/
	static jbyte getByte(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
		return java_lang_reflect_Array_getByte(env, clazz, a, b);
	}

	/*** public static native getChar (Ljava/lang/Object;I)C ***/
	static jchar getChar(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
		return java_lang_reflect_Array_getChar(env, clazz, a, b);
	}

	/*** public static native getShort (Ljava/lang/Object;I)S ***/
	static jshort getShort(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
		return java_lang_reflect_Array_getShort(env, clazz, a, b);
	}

	/*** public static native getInt (Ljava/lang/Object;I)I ***/
	static jint getInt(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
		return java_lang_reflect_Array_getInt(env, clazz, a, b);
	}

	/*** public static native getLong (Ljava/lang/Object;I)J ***/
	static jlong getLong(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
		return java_lang_reflect_Array_getLong(env, clazz, a, b);
	}

	/*** public static native getFloat (Ljava/lang/Object;I)F ***/
	static jfloat getFloat(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
		return java_lang_reflect_Array_getFloat(env, clazz, a, b);
	}

	/*** public static native getDouble (Ljava/lang/Object;I)D ***/
	static jdouble getDouble(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b) {
		return java_lang_reflect_Array_getDouble(env, clazz, a, b);
	}

	/*** public static native set (Ljava/lang/Object;ILjava/lang/Object;)V ***/
	static void set(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, struct java_lang_Object *c) {
		java_lang_reflect_Array_set(env, clazz, a, b, c);
	}

	/*** public static native setBoolean (Ljava/lang/Object;IZ)V ***/
	static void setBoolean(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jbool c) {
		java_lang_reflect_Array_setBoolean(env, clazz, a, b, c);
	}

	/*** public static native setByte (Ljava/lang/Object;IB)V ***/
	static void setByte(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jbyte c) {
		java_lang_reflect_Array_setByte(env, clazz, a, b, c);
	}

	/*** public static native setChar (Ljava/lang/Object;IC)V ***/
	static void setChar(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jchar c) {
		java_lang_reflect_Array_setChar(env, clazz, a, b, c);
	}

	/*** public static native setShort (Ljava/lang/Object;IS)V ***/
	static void setShort(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jshort c) {
		java_lang_reflect_Array_setShort(env, clazz, a, b, c);
	}

	/*** public static native setInt (Ljava/lang/Object;II)V ***/
	static void setInt(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jint c) {
		java_lang_reflect_Array_setInt(env, clazz, a, b, c);
	}

	/*** public static native setLong (Ljava/lang/Object;IJ)V ***/
	static void setLong(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jlong c) {
		java_lang_reflect_Array_setLong(env, clazz, a, b, c);
	}

	/*** public static native setFloat (Ljava/lang/Object;IF)V ***/
	static void setFloat(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jfloat c) {
		java_lang_reflect_Array_setFloat(env, clazz, a, b, c);
	}

	/*** public static native setDouble (Ljava/lang/Object;ID)V ***/
	static void setDouble(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a, jint b, jdouble c) {
		java_lang_reflect_Array_setDouble(env, clazz, a, b, c);
	}

#ifdef IMPLEMENT_java_lang_reflect_Array

	/* Private Methods */
	/*** private <init> ()V ***/
	static java_lang_reflect_Array* _new(JRIEnv* env, struct java_lang_Class* clazz) {
		return java_lang_reflect_Array_new(env, clazz);
	}

	/*** private static native newArray (Ljava/lang/Class;I)Ljava/lang/Object; ***/
	static struct java_lang_Object * newArray(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jint b) {
		return java_lang_reflect_Array_newArray(env, clazz, a, b);
	}

	/*** private static native multiNewArray (Ljava/lang/Class;[I)Ljava/lang/Object; ***/
	static struct java_lang_Object * multiNewArray(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Class *a, jintArray b) {
		return java_lang_reflect_Array_multiNewArray(env, clazz, a, b);
	}

#endif /* IMPLEMENT_java_lang_reflect_Array */
};

#endif /* __cplusplus */

#endif /* Class java/lang/reflect/Array */
