//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Ptav3.rc
//
#define IDBTN3                          3
#define IDS_PROJNAME                    100
#define IDB_VSPTA                       101
#define IDS_ERR_INITIALIZED             101
#define IDR_VSPTA                       102
#define IDS_ERR_EMPTYARGS               102
#define IDS_ERR_INVALIDARGS             103
#define IDC_IBROWSER                    103
#define IDS_LGNDLG_TITLE                104
#define IDS_NEWPASSWD_TEXT              105
#define IDS_NEWPASSWD_TITLE             106
#define IDS_OPENPROF_TEXT               107
#define IDS_OPENPROF_TITLE              108
#define IDS_RVWMSG_TEXT                 109
#define IDS_RVWMSG_TITLE                110
#define IDS_SELID_TEXT                  111
#define IDS_SELID_TITLE                 112
#define IDS_SELID_CHKBOXTEXT            113
#define IDS_SGNDLG_TITLE                114
#define IDS_ERR_NOTINITIALIZED          115
#define IDS_ERR_CARDNOTOPEN             116
#define IDS_ERR_CAPIMODEONLY            117
#define IDS_ERR_LANGNOTSUPPORTED        118
#define IDS_ERR_NOFONT                  119
#define IDS_ERR_FONTNOTAVAILABLE        120
#define IDS_ERR_FONTDOESNOTSUPPORTLANG  121
#define IDS_OK                          122
#define IDS_SIGN                        123
#define IDS_ACCEPT                      124
#define IDS_LOGIN                       125
#define IDS_SELECT                      126
#define IDS_RENEW                       127
#define IDS_YES                         128
#define IDS_CANCEL                      129
#define IDS_REJECT                      130
#define IDS_NO                          131
#define IDS_ERR_INVALIDVALUE            132
#define IDS_ERR_IDNOTSELECTED           133
#define IDS_ERR_CARDOPEN                134
#define IDS_ERR_CANNOTLOADMSCAPI        135
#define IDS_ERR_CANNOTLOADVSCAPI        136
#define IDS_ERR_NONCAPIMODEONLY         137
#define IDS_ERR_INVALIDFLAGS            138
#define IDS_PREV                        139
#define IDS_NEXT                        140
#define IDS_HELP                        141
#define IDS_OPEN                        142
#define IDS_CREATE                      143
#define IDS_ERR_CARDALREADYOPEN         144
#define IDS_DEFLOGOURL                  145
#define IDS_CREATEPROF_PROFNAMELBL      146
#define IDS_CREATEPROF_PASSWDLBL        147
#define IDS_CREATEPROF_CNFRMPASSWDLBL   148
#define IDS_VALIDITYLBL                 149
#define IDS_CERTLIST_FNCOL_HEAD         150
#define IDS_CERTLIST_CNCOL_HEAD         151
#define IDS_CERTLIST_EXPIRES_HEAD       152
#define IDS_CREATEDLG_TITLE             153
#define IDS_INTRODLG_TITLE              154
#define IDS_INTRODLG_TEXT               155
#define IDS_PASSWDQUALINTRO             156
#define IDS_PASSWDLENINTRO              157
#define IDS_NUMERICONLYINTRO            158
#define IDS_ALPHANUMERICINTRO           159
#define IDS_PASSWDNUMOFNUMINTRO         160
#define IDS_PASSWDNUMNOTATBEGININTRO    161
#define IDS_PASSWDNUMNOTATENDINTRO      162
#define IDS_PASSWDNUMNOTATBEGINENDINTRO 163
#define IDS_NUMBERRANDCHARS             164
#define IDS_INVALIDPASSWDMSG            165
#define IDS_PROFILEDOESTNOTEXISTMSG     166
#define IDS_PROFILEEXISTMSG             167
#define IDS_CONFIRMPASSWORDNOMATCH      168
#define IDS_PASSWDQUALERRINTRO          169
#define IDS_INSTALLCERTPROFNOTCORRECT   170
#define IDS_CNFRMACTIONCREATE           171
#define IDS_CNFRMACTIONDELETE           172
#define IDS_CNFRMACTIONOPEN             173
#define IDS_NEWPASSWDNOPROF_TEXT        174
#define IDS_PROFLOCKEDOUTMSG            175
#define IDS_ANYCHARS                    176
#define IDS_CHANGEPASSWD_TEXT           177
#define IDS_CHANGEPASSWD_TITLE          178
#define IDS_CHANGE                      179
#define IDS_CHNGPASSWD_OLDPASSWDLBL     180
#define IDS_CHANGEPASSWD_NEWPASSWDLBL   181
#define IDS_UNLOCK                      182
#define IDS_TIMEOUT_TEXT                183
#define IDS_TIMEOUT_TITLE               184
#define IDS_INSTALL_FAILED              185
#define IDS_READ_FILE_ERR               186
#define IDS_FILE_SIZE_ERR               187
#define IDS_MEMORY_FAIL                 188
#define IDS_OPEN_FILE_ERR               189
#define IDS_INVALID_SIGFILE             190
#define IDS_REG_CREATE_ERR              191
#define IDS_REG_WRITE_ERR               192
#define IDS_MODULE_NAME_ERR             193
#define IDS_STRING_ERR                  194
#define IDS_IMPORT                      195
#define IDS_IMPORT_TEXT                 196
#define IDS_IMPORTDLG_TITLE             197
#define IDS_IMPORT_TITLE                198
#define IDS_SIGNATURE_NOTIFICATION      199
#define IDS_DECRYPT_NOTIFICATION        200
#define IDD_PTAUI                       201
#define IDS_EXPORTP12_FILENAMELBL       201
#define IDS_EXPORT                      202
#define IDS_EXPORT_TEXT                 203
#define IDS_EXPORT_TITLE                204
#define IDS_EXPORTDLG_TITLE             205
#define IDS_FILEEXISTS                  206
#define IDS_CNFRMACTIONNEWPATH          207
#define IDS_BROWSE                      208
#define IDS_CREATEPASSWD_TITLE          209
#define IDS_CREATEPASSWD_TEXT           210
#define IDS_RESETPASSWD_TEXT            242
#define IDS_RESETPASSWD_TITLE           243
#define IDS_FILEFILTER                  211
#define IDC_TOP_SEPARATOR               212
#define IDS_INVALID_PATH                212
#define IDC_BOTTOM_SEPARATOR            213
#define IDS_EXPORTPROFDLG_TITLE         213
#define IDB_VSLARGE                     214
#define IDS_IMPORTPROFDLG_TITLE         214
#define IDC_HEADER_LOGO                 215
#define IDS_CREATEPASSWD_NEWPASSWDLBL   215
#define IDS_RESET                       244
#define IDC_HEADER_TITLE                216
#define IDS_CREATEPASSWD_CNFRMPASSWDLBL 216
#define IDS_RESETPASSWD_SECANSWERLBL    245
#define IDC_UI_TITLE                    217
#define IDS_ENTERPASSWD_TITLE           217
#define IDS_RESETPASSWD_NEWPASSWDLBL    246
#define IDC_UI_TEXT                     218
#define IDS_ENTERPASSWD_TEXT            218
#define IDS_GETSECRETQUESTION_TEXT      247
#define IDC_LABEL1                      219
#define IDS_ENTERPASSWD_THEPASSWDLBL    219
#define IDS_GETSECRETQUESTION_TITLE     248
#define IDC_EDIT1                       220
#define IDS_RESETPASSWD_SECQUESLBL      220
#define IDC_LABEL2                      221
#define IDS_CREATESECRET_TEXT           221
#define IDC_EDIT2                       222
#define IDS_CREATESECRET_TITLE          222
#define IDC_LABEL3                      223
#define IDS_GETSECRET_PROFILEREQD       223
#define IDC_EDIT3                       224
#define IDS_GETSECRET_PROFDOESNOTEXIST  224
#define IDC_EDIT_RDONLY                 225
#define IDS_RESETPASSWD_ANSWERPASSWDREQD 225
#define IDC_CERT_LOGO                   226
#define IDS_RESETPASSWD_WRONGANSWER     226
#define IDC_LABEL4                      227
#define IDS_RESETPASSWD_PROFLOCKOUT     227
#define IDC_LIST_CERTLIST               228
#define IDS_CREATESECRET_SECRETREQD     228
#define IDC_CHECKBOX                    229
#define IDS_STRING229                   229
#define IDC_VRSN_LOGO                   230
#define IDC_COMBO1                      231
#define IDC_EDIT4                       232
#define IDBTN2                          233
#define IDC_LABEL5                      234
#define IDC_LABEL6                      235
#define IDC_EDIT5                       236
#define IDC_OUTLINE                     238
#define IDBTN4                          239
#define IDR_VSROOTS                     240
#define IDR_HTML1                       241
#define IDS_RESETPASSWD_TEXT            242
#define IDS_RESETPASSWD_TITLE           243
#define IDS_RESET                       244
#define IDS_RESETPASSWD_SECANSWERLBL    245
#define IDS_RESETPASSWD_NEWPASSWDLBL    246
#define IDS_GETSECRETQUESTION_TEXT      247
#define IDS_GETSECRETQUESTION_TITLE     248
#define IDS_PASSWORD_NUMERIC_INFY       249
#define IDS_PASSWORD_NUMERIC            249
#define IDS_PASSWORD_ALPHANUMERIC_INFY  250
#define IDS_PASSWORD_ALPHANUMERIC       250
#define IDS_PASSWORD_ALPHANUMERIC_NUMLEN_INFY 251
#define IDS_PASSWORD_ALPHANUMERIC_NUMLEN 251
#define IDS_PASSWORD_ALPHANUMERIC_NUMLEN_NOTATBEGIN_INFY 252
#define IDS_PASSWORD_ALPHANUMERIC_NUMLEN_NOTATBEGIN 252
#define IDS_PASSWORD_ALPHANUMERIC_NUMLEN_NOTATEND_INFY 253
#define IDS_PASSWORD_ALPHANUMERIC_NUMLEN_NOTATEND 253
#define IDS_PASSWORD_ALPHANUMERIC_NUMLEN_NOTATBEGINEND_INFY 254
#define IDS_PASSWORD_ALPHANUMERIC_NUMLEN_NOTATBEGINEND 254
#define IDS_PASSWORD_ANY_INFY           255
#define IDS_PASSWORD_ANY                255

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        222
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         240
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
