/*
 * $Revision: 1.2.404.1 $
 * $Header: /cvs/itgclient/client/modules/RoamingClient/include/vsrmerr.h,v 1.2.404.1 2003/06/09 23:41:31 sgoginen Exp $
 */

/*--------------------------------------------------------------------\
| Copyright (C) VeriSign, Inc. created 2000. All rights reserved.     |
| This is an unpublished work protected as such under copyright law.  |  
| This work contains proprietary, confidential, and trade secret      |
| information of VeriSign, Inc.  Use, disclosure or reproduction      |
| without the expressed written authorization of VeriSign, Inc.       |
| is prohibited.                                                      |
\--------------------------------------------------------------------*/

// vsrmerr.h : Defines common error codes
//

#ifndef VSRMERR_H
#define VSRMERR_H

typedef enum {
    VSRM_SUCCESS = 0x00,
    VSRM_ERR_BASE = 0x4100,

    /* ----- common errors ------ */
    VSRM_ERR_UNKNOWN = VSRM_ERR_BASE + 0x01,
    VSRM_ERR_INTERNAL,
    VSRM_ERR_NULL_PARAMETER,
    VSRM_ERR_OUT_OF_MEMORY,
    VSRM_ERR_INVALID_INPUT,
    VSRM_ERR_INDEX_OUT_OF_BOUND,
    VSRM_ERR_FLATTEN_NV_TO_BUFFER,
    VSRM_ERR_CREATE_THREAD,
    VSRM_ERR_ENTRY_NOT_FOUND,
    VSRM_ERR_NULL_SERVER_INFO,
    VSRM_ERR_NULL_SERVER_INFO_SIG,
    VSRM_ERR_BAD_FORMAT_SERVER_INFO,
    VSRM_ERR_SERVER_INFO_MISS_DATA,
    VSRM_ERR_SERVER_INFO_SIG_MISMATCH,
    VSRM_ERR_EXTRACT_PUBLIC_KEY_FROM_CERT,
    VSRM_ERR_VERSION_MISSING,
    VSRM_ERR_VERSION_NOT_SUPPORTED,
    VSRM_ERR_SERVER_ID_MISSING,

    /* ----- encoding errors ------ */

    VSRM_ERR_BASE64_ENCODE = VSRM_ERR_BASE + 0x50,
    VSRM_ERR_BASE64_DECODE,
    VSRM_ERR_BASE64_NOT_ENOUGH_BUFFER_SPACE,    
    VSRM_ERR_DECODE_BASE64_INVALID_CHAR,
    VSRM_ERR_HASC_ENCODE,
    VSRM_ERR_HASC_DECODE,
    VSRM_ERR_INVALID_NUMBER,
    VSRM_ERR_UNSUPPORT_ENCODE_ALG,
    VSRM_ERR_UNICODE_TO_UTF8,
    VSRM_ERR_UTF8_TO_UNICODE,

    /* ----- crypto errors ------ */

    VSRM_ERR_CRYPTO = VSRM_ERR_BASE + 0x70,
    VSRM_ERR_FIND_PRIME,
    VSRM_ERR_MOD_EXP,
    VSRM_ERR_KEY_CREATION,
    VSRM_ERR_COMPUTE_DIGEST,
    VSRM_ERR_COMPUTE_XOR,
    VSRM_ERR_COMPUTE_RANDOM,
    VSRM_ERR_COMPUTE_RANDOM_INVERSE,
    VSRM_ERR_ENCRYPT,
    VSRM_ERR_DECRYPT,
    VSRM_ERR_DECRYPT_SK,
    VSRM_ERR_KEY_NULL,
    VSRM_ERR_SIG_MISMATCH,
    VSRM_ERR_UNSUPPORT_DIGEST_ALG,
    VSRM_ERR_READ_CERT,
    VSRM_ERR_BAD_RSA_KEY_BUFFER,  /* VSRM_ERR_BASE + 0x7f */
    VSRM_ERR_PADDING_DATA,

    /* ----- http connection errors ------ */

    VSRM_ERR_BAD_URL = VSRM_ERR_BASE + 0x90,
    VSRM_ERR_UNSUPPORT_URL_SCHEME,
    VSRM_ERR_OPEN_SESSION,
    VSRM_ERR_CONNECT_URL,
    VSRM_ERR_OPEN_REQUEST,
    VSRM_ERR_SEND_REQUEST,
    VSRM_ERR_END_REQUEST,
    VSRM_ERR_READ_HTTP_RESPONSE,
    VSRM_ERR_QUERY_SERVER_STATUS,
    VSRM_ERR_QUERY_SERVER_RESPONSE_HEADER,
    VSRM_ERR_REQUESTED_URL_NOT_FOUND,
    VSRM_ERR_BAD_REQUEST,
    VSRM_ERR_UNKNOWN_SERVER_ERROR,
    VSRM_ERR_SERVER_CAPACITY_REACHED,
    VSRM_ERR_SERVER_RESPONSE_DATA_UNRECOGNIZED,
    VSRM_ERR_HTTP_VERSION_NOT_SUPPORTED,
    VSRM_ERR_HTTP_BAD_REQUEST,
    VSRM_ERR_HTTP_DENIED,
    VSRM_ERR_HTTP_FORBIDDEN,


    /* ----- protocol errors ------ */

    VSRM_ERR_INVALID_SESSION_IDENTIFIER = VSRM_ERR_BASE + 0x0110,
    VSRM_ERR_UNSUPPORT_OPERATION,
    VSRM_ERR_NULL_PROFILE,
    VSRM_ERR_READ_FILE,
    VSRM_ERR_CONVERT_RESPONSE_TO_NV,
    VSRM_ERR_ROAMING_SERVER_URL_ID_CNT_MISMATCH,
    VSRM_ERR_STORAGE_SERVER_INFO,
    VSRM_ERR_NO_SUCH_USER,
    VSRM_ERR_USER_NON_COMPLETE,
    VSRM_ERR_USER_ALREADY_EXISTS,
    VSRM_ERR_BAD_STATE,
    VSRM_ERR_USER_PENDING_STATE,
    VSRM_ERR_ATTEMPT_EXCEED_THRESHOLD,
    VSRM_ERR_VERIFIER_MISMATCH,
    VSRM_ERR_PROFILE_DATA_CORRUPTED,    
    VSRM_ERR_WRONG_PASSWORD,   
    VSRM_ERR_UPDATE_LOCKOUT_THRESHOLD_CACHE_FAILED,
    VSRM_ERR_INVALID_RESPONSE_DATA_SIZE,
    VSRM_ERR_LOCKOUT_THRESHOLD_NOT_FOUND,    
    VSRM_ERR_VERSION_MISMATCH,
    VSRM_ERR_CHANGE_SAME_PASSWORD,
    VSRM_ERR_USERNAME_TOO_LONG,
    VSRM_ERR_BAD_PASSWORD_INPUT,   /* VSRM_ERR_BASE + 0x0126 */
	VSRM_ERR_BAD_QUESTION,
	VSRM_ERR_BAD_ANSWER,
	VSRM_ERR_SERVER_MIX,
   
    // used by server only
  
    VSRM_ERR_CFG = VSRM_ERR_BASE + 0x200,
    VSRM_ERR_CFG_FILE_OPEN,
    VSRM_ERR_CFG_ENTRY_MISSING,  
    VSRM_ERR_CFG_ENTRY_INVALID,
    VSRM_ERR_CFG_CLIENT_CERT_SERIAL_NULL,
    VSRM_ERR_CFG_DUPL_ENTRIES,
    VSRM_ERR_CFG_FILE_LINE_TOO_LONG,
    VSRM_ERR_CFG_ILLEGAL_SPACE_MARKER,
    VSRM_ERR_MISSING_CFG_DLL_NAME,
    VSRM_ERR_LOAD_DLL,
    VSRM_ERR_QUERY_DLL_API,
    VSRM_ERR_INVALID_DATA,
    VSRM_ERR_CLIENT_CERT_NOT_FOUND,
    VSRM_ERR_CLIENT_CERT_NOT_AUTHORIZED,    
    VSRM_ERR_PRIVATE_KEY_FILE_OPEN,
    VSRM_ERR_PRIVATE_KEY_FILE_DATA_FORMAT,
    VSRM_ERR_WRONG_PASSWORD_OPEN_PRIVATE_KEY_FILE,
    VSRM_ERR_OP_MODIFIED,             /* VSRM_ERR_BASE + 0x211 */
  
    /* LDAP support error codes */

    VSRM_LDAP_ERR = VSRM_ERR_BASE + 0x220,
    VSRM_LDAP_ERR_CFG,
    VSRM_LDAP_ERR_INIT,
    VSRM_LDAP_ERR_BIND,
    VSRM_LDAP_ERR_SEARCH,
    VSRM_LDAP_ERR_INVALID_DATA,
    VSRM_LDAP_ERR_CFG_BINDDN,
    VSRM_LDAP_ERR_AUTH_ATTR_NOT_FOUND,
    VSRM_LDAP_ERR_AUTH_ATTR_NOT_QUALIFY,
    VSRM_LDAP_ERR_HOSTNAME_NULL,
    VSRM_LDAP_ERR_PORT_MISSING,
  
    /* ODBC support error codes */

    VSRM_ODBC_ERR = VSRM_ERR_BASE + 0x240,
    VSRM_ODBC_ERR_OPEN_CONNECTION,
    VSRM_ODBC_ERR_OPEN_CURSOR,
    VSRM_ODBC_ERR_CFG,
    VSRM_ODBC_ERR_CFG_SQL,
    
    /* Flat file DB error codes */
    VSRM_FILE_ERR = VSRM_ERR_BASE + 0x260,
    VSRM_FILE_ERR_OPEN,
    
    /* QM client handler error codes */
    VSRM_QM_ERR = VSRM_ERR_BASE + 0x280,
    VSRM_QM_ERR_CONNECT,
    VSRM_QM_ERR_NULL_RESPONSE,

    /* Mapped from Query Manager Server errors */
    VSRM_QM_NO_ERROR_PARTIAL_RESULTS, 
    VSRM_QM_ERR_INTERNAL_ERROR,
    VSRM_QM_ERR_QUERY_TEMPLATE_NOT_SUPPLIED,
    VSRM_QM_ERR_QUERY_TEMPLATE_OPENING_ERROR,
    VSRM_QM_ERR_OUT_OF_MEMORY,
    VSRM_QM_ERR_CONNREFUSED,
    VSRM_QM_ERR_TIMEDOUT,
    VSRM_QM_ERR_NO_DATA_FOUND,
    VSRM_QM_ERR_UPDATE_NOT_ALLOW,
    VSRM_QM_ERR_UPDATE_EXCEED_LIMIT,  /* VSRM_ERR_BASE + 0x28c */

    /* ----- Luna Token related errors ----- */

    VSRM_ERR_LUNA =  VSRM_ERR_BASE + 0x300,
    VSRM_ERR_LUNA_ENCRYPT,
    VSRM_ERR_LUNA_DECRYPT,
    VSRM_ERR_LUNA_ENC_DEC_MISMATCH,
    VSRM_ERR_LUNA_NO_KEY_BY_NAME,

    /* Audit error codes */
    VSRM_AUDIT_ERR = VSRM_ERR_BASE + 0x400,
    VSRM_AUDIT_ERR_OP_NULL,

    VSRM_ERR_LAST = VSRM_ERR_BASE + 0x04ff

} VSRM_STATUS;

#endif // VSRMERR_H
