/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class java/lang/StringBuffer */

#ifdef IMPLEMENT_java_lang_StringBuffer
#define _implementing_java_lang_StringBuffer
#endif /* IMPLEMENT_java_lang_StringBuffer */
#define IMPLEMENT_java_lang_StringBuffer
#include "java_lang_StringBuffer.h"

#ifndef UNUSED_java_lang_StringBuffer_value
JRIFieldID FAR fieldID_java_lang_StringBuffer_value = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jref)
get_java_lang_StringBuffer_value(JRIEnv* env, struct java_lang_StringBuffer* obj) {
	if (fieldID_java_lang_StringBuffer_value == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before accessing field value [C");
	}
	return (jref)
		JRI_GetField(env, obj, fieldID_java_lang_StringBuffer_value);
}
JRI_PUBLIC_API(void)
set_java_lang_StringBuffer_value(JRIEnv* env, struct java_lang_StringBuffer* obj, jref v) {
	if (fieldID_java_lang_StringBuffer_value == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before accessing field value [C");
	}
	JRI_SetField(env, obj, fieldID_java_lang_StringBuffer_value, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_value */

#ifndef UNUSED_java_lang_StringBuffer_count
JRIFieldID FAR fieldID_java_lang_StringBuffer_count = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_java_lang_StringBuffer_count(JRIEnv* env, struct java_lang_StringBuffer* obj) {
	if (fieldID_java_lang_StringBuffer_count == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before accessing field count I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_java_lang_StringBuffer_count);
}
JRI_PUBLIC_API(void)
set_java_lang_StringBuffer_count(JRIEnv* env, struct java_lang_StringBuffer* obj, jint v) {
	if (fieldID_java_lang_StringBuffer_count == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before accessing field count I");
	}
	JRI_SetFieldInt(env, obj, fieldID_java_lang_StringBuffer_count, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_count */

#ifndef UNUSED_java_lang_StringBuffer_shared
JRIFieldID FAR fieldID_java_lang_StringBuffer_shared = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
get_java_lang_StringBuffer_shared(JRIEnv* env, struct java_lang_StringBuffer* obj) {
	if (fieldID_java_lang_StringBuffer_shared == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before accessing field shared Z");
	}
	return JRI_GetFieldBoolean(env, obj, fieldID_java_lang_StringBuffer_shared);
}
JRI_PUBLIC_API(void)
set_java_lang_StringBuffer_shared(JRIEnv* env, struct java_lang_StringBuffer* obj, jbool v) {
	if (fieldID_java_lang_StringBuffer_shared == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before accessing field shared Z");
	}
	JRI_SetFieldBoolean(env, obj, fieldID_java_lang_StringBuffer_shared, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_shared */

#ifndef UNUSED_java_lang_StringBuffer_new
JRIMethodID FAR methodID_java_lang_StringBuffer_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer*)
java_lang_StringBuffer_new(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_java_lang_StringBuffer_new == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method <init> ()V");
	}
	return (struct java_lang_StringBuffer*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_StringBuffer_new);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_new */

#ifndef UNUSED_java_lang_StringBuffer_new_1
JRIMethodID FAR methodID_java_lang_StringBuffer_new_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer*)
java_lang_StringBuffer_new_1(JRIEnv* env, struct java_lang_Class* clazz, jint a) {
	if (methodID_java_lang_StringBuffer_new_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method <init> (I)V");
	}
	return (struct java_lang_StringBuffer*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_StringBuffer_new_1, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_new_1 */

#ifndef UNUSED_java_lang_StringBuffer_new_2
JRIMethodID FAR methodID_java_lang_StringBuffer_new_2 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer*)
java_lang_StringBuffer_new_2(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a) {
	if (methodID_java_lang_StringBuffer_new_2 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method <init> (Ljava/lang/String;)V");
	}
	return (struct java_lang_StringBuffer*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_StringBuffer_new_2, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_new_2 */

#ifndef UNUSED_java_lang_StringBuffer_length
JRIMethodID FAR methodID_java_lang_StringBuffer_length = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_StringBuffer_length(JRIEnv* env, struct java_lang_StringBuffer* self) {
	if (methodID_java_lang_StringBuffer_length == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method length ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_length);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_length */

#ifndef UNUSED_java_lang_StringBuffer_capacity
JRIMethodID FAR methodID_java_lang_StringBuffer_capacity = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_StringBuffer_capacity(JRIEnv* env, struct java_lang_StringBuffer* self) {
	if (methodID_java_lang_StringBuffer_capacity == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method capacity ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_capacity);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_capacity */

#ifndef UNUSED_java_lang_StringBuffer_copyWhenShared
JRIMethodID FAR methodID_java_lang_StringBuffer_copyWhenShared = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_StringBuffer_copyWhenShared(JRIEnv* env, struct java_lang_StringBuffer* self) {
	if (methodID_java_lang_StringBuffer_copyWhenShared == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method copyWhenShared ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_copyWhenShared);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_copyWhenShared */

#ifndef UNUSED_java_lang_StringBuffer_ensureCapacity
JRIMethodID FAR methodID_java_lang_StringBuffer_ensureCapacity = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_StringBuffer_ensureCapacity(JRIEnv* env, struct java_lang_StringBuffer* self, jint a) {
	if (methodID_java_lang_StringBuffer_ensureCapacity == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method ensureCapacity (I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_ensureCapacity, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_ensureCapacity */

#ifndef UNUSED_java_lang_StringBuffer_setLength
JRIMethodID FAR methodID_java_lang_StringBuffer_setLength = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_StringBuffer_setLength(JRIEnv* env, struct java_lang_StringBuffer* self, jint a) {
	if (methodID_java_lang_StringBuffer_setLength == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method setLength (I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_setLength, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_setLength */

#ifndef UNUSED_java_lang_StringBuffer_charAt
JRIMethodID FAR methodID_java_lang_StringBuffer_charAt = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jchar)
java_lang_StringBuffer_charAt(JRIEnv* env, struct java_lang_StringBuffer* self, jint a) {
	if (methodID_java_lang_StringBuffer_charAt == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method charAt (I)C");
	}
	return (jchar)JRI_CallMethodChar(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_charAt, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_charAt */

#ifndef UNUSED_java_lang_StringBuffer_getChars
JRIMethodID FAR methodID_java_lang_StringBuffer_getChars = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_StringBuffer_getChars(JRIEnv* env, struct java_lang_StringBuffer* self, jint a, jint b, jcharArray c, jint d) {
	if (methodID_java_lang_StringBuffer_getChars == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method getChars (II[CI)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_getChars, a, b, c, d);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_getChars */

#ifndef UNUSED_java_lang_StringBuffer_setCharAt
JRIMethodID FAR methodID_java_lang_StringBuffer_setCharAt = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_StringBuffer_setCharAt(JRIEnv* env, struct java_lang_StringBuffer* self, jint a, jchar b) {
	if (methodID_java_lang_StringBuffer_setCharAt == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method setCharAt (IC)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_setCharAt, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_setCharAt */

#ifndef UNUSED_java_lang_StringBuffer_append
JRIMethodID FAR methodID_java_lang_StringBuffer_append = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_append(JRIEnv* env, struct java_lang_StringBuffer* self, struct java_lang_Object *a) {
	if (methodID_java_lang_StringBuffer_append == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method append (Ljava/lang/Object;)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_append, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_append */

#ifndef UNUSED_java_lang_StringBuffer_append_1
JRIMethodID FAR methodID_java_lang_StringBuffer_append_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_append_1(JRIEnv* env, struct java_lang_StringBuffer* self, struct java_lang_String *a) {
	if (methodID_java_lang_StringBuffer_append_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method append (Ljava/lang/String;)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_append_1, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_append_1 */

#ifndef UNUSED_java_lang_StringBuffer_append_2
JRIMethodID FAR methodID_java_lang_StringBuffer_append_2 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_append_2(JRIEnv* env, struct java_lang_StringBuffer* self, jcharArray a) {
	if (methodID_java_lang_StringBuffer_append_2 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method append ([C)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_append_2, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_append_2 */

#ifndef UNUSED_java_lang_StringBuffer_append_3
JRIMethodID FAR methodID_java_lang_StringBuffer_append_3 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_append_3(JRIEnv* env, struct java_lang_StringBuffer* self, jcharArray a, jint b, jint c) {
	if (methodID_java_lang_StringBuffer_append_3 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method append ([CII)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_append_3, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_append_3 */

#ifndef UNUSED_java_lang_StringBuffer_append_4
JRIMethodID FAR methodID_java_lang_StringBuffer_append_4 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_append_4(JRIEnv* env, struct java_lang_StringBuffer* self, jbool a) {
	if (methodID_java_lang_StringBuffer_append_4 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method append (Z)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_append_4, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_append_4 */

#ifndef UNUSED_java_lang_StringBuffer_append_5
JRIMethodID FAR methodID_java_lang_StringBuffer_append_5 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_append_5(JRIEnv* env, struct java_lang_StringBuffer* self, jchar a) {
	if (methodID_java_lang_StringBuffer_append_5 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method append (C)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_append_5, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_append_5 */

#ifndef UNUSED_java_lang_StringBuffer_append_6
JRIMethodID FAR methodID_java_lang_StringBuffer_append_6 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_append_6(JRIEnv* env, struct java_lang_StringBuffer* self, jint a) {
	if (methodID_java_lang_StringBuffer_append_6 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method append (I)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_append_6, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_append_6 */

#ifndef UNUSED_java_lang_StringBuffer_append_7
JRIMethodID FAR methodID_java_lang_StringBuffer_append_7 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_append_7(JRIEnv* env, struct java_lang_StringBuffer* self, jlong a) {
	if (methodID_java_lang_StringBuffer_append_7 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method append (J)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_append_7, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_append_7 */

#ifndef UNUSED_java_lang_StringBuffer_append_8
JRIMethodID FAR methodID_java_lang_StringBuffer_append_8 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_append_8(JRIEnv* env, struct java_lang_StringBuffer* self, jfloat a) {
	if (methodID_java_lang_StringBuffer_append_8 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method append (F)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_append_8, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_append_8 */

#ifndef UNUSED_java_lang_StringBuffer_append_9
JRIMethodID FAR methodID_java_lang_StringBuffer_append_9 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_append_9(JRIEnv* env, struct java_lang_StringBuffer* self, jdouble a) {
	if (methodID_java_lang_StringBuffer_append_9 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method append (D)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_append_9, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_append_9 */

#ifndef UNUSED_java_lang_StringBuffer_insert
JRIMethodID FAR methodID_java_lang_StringBuffer_insert = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_insert(JRIEnv* env, struct java_lang_StringBuffer* self, jint a, struct java_lang_Object *b) {
	if (methodID_java_lang_StringBuffer_insert == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method insert (ILjava/lang/Object;)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_insert, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_insert */

#ifndef UNUSED_java_lang_StringBuffer_insert_1
JRIMethodID FAR methodID_java_lang_StringBuffer_insert_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_insert_1(JRIEnv* env, struct java_lang_StringBuffer* self, jint a, struct java_lang_String *b) {
	if (methodID_java_lang_StringBuffer_insert_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method insert (ILjava/lang/String;)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_insert_1, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_insert_1 */

#ifndef UNUSED_java_lang_StringBuffer_insert_2
JRIMethodID FAR methodID_java_lang_StringBuffer_insert_2 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_insert_2(JRIEnv* env, struct java_lang_StringBuffer* self, jint a, jcharArray b) {
	if (methodID_java_lang_StringBuffer_insert_2 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method insert (I[C)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_insert_2, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_insert_2 */

#ifndef UNUSED_java_lang_StringBuffer_insert_3
JRIMethodID FAR methodID_java_lang_StringBuffer_insert_3 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_insert_3(JRIEnv* env, struct java_lang_StringBuffer* self, jint a, jbool b) {
	if (methodID_java_lang_StringBuffer_insert_3 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method insert (IZ)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_insert_3, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_insert_3 */

#ifndef UNUSED_java_lang_StringBuffer_insert_4
JRIMethodID FAR methodID_java_lang_StringBuffer_insert_4 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_insert_4(JRIEnv* env, struct java_lang_StringBuffer* self, jint a, jchar b) {
	if (methodID_java_lang_StringBuffer_insert_4 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method insert (IC)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_insert_4, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_insert_4 */

#ifndef UNUSED_java_lang_StringBuffer_insert_5
JRIMethodID FAR methodID_java_lang_StringBuffer_insert_5 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_insert_5(JRIEnv* env, struct java_lang_StringBuffer* self, jint a, jint b) {
	if (methodID_java_lang_StringBuffer_insert_5 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method insert (II)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_insert_5, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_insert_5 */

#ifndef UNUSED_java_lang_StringBuffer_insert_6
JRIMethodID FAR methodID_java_lang_StringBuffer_insert_6 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_insert_6(JRIEnv* env, struct java_lang_StringBuffer* self, jint a, jlong b) {
	if (methodID_java_lang_StringBuffer_insert_6 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method insert (IJ)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_insert_6, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_insert_6 */

#ifndef UNUSED_java_lang_StringBuffer_insert_7
JRIMethodID FAR methodID_java_lang_StringBuffer_insert_7 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_insert_7(JRIEnv* env, struct java_lang_StringBuffer* self, jint a, jfloat b) {
	if (methodID_java_lang_StringBuffer_insert_7 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method insert (IF)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_insert_7, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_insert_7 */

#ifndef UNUSED_java_lang_StringBuffer_insert_8
JRIMethodID FAR methodID_java_lang_StringBuffer_insert_8 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_insert_8(JRIEnv* env, struct java_lang_StringBuffer* self, jint a, jdouble b) {
	if (methodID_java_lang_StringBuffer_insert_8 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method insert (ID)Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_insert_8, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_insert_8 */

#ifndef UNUSED_java_lang_StringBuffer_reverse
JRIMethodID FAR methodID_java_lang_StringBuffer_reverse = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_StringBuffer *)
java_lang_StringBuffer_reverse(JRIEnv* env, struct java_lang_StringBuffer* self) {
	if (methodID_java_lang_StringBuffer_reverse == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method reverse ()Ljava/lang/StringBuffer;");
	}
	return (struct java_lang_StringBuffer *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_reverse);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_reverse */

#ifndef UNUSED_java_lang_StringBuffer_toString
JRIMethodID FAR methodID_java_lang_StringBuffer_toString = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_StringBuffer_toString(JRIEnv* env, struct java_lang_StringBuffer* self) {
	if (methodID_java_lang_StringBuffer_toString == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method toString ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_toString);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_toString */

#ifndef UNUSED_java_lang_StringBuffer_setShared
JRIMethodID FAR methodID_java_lang_StringBuffer_setShared = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_StringBuffer_setShared(JRIEnv* env, struct java_lang_StringBuffer* self) {
	if (methodID_java_lang_StringBuffer_setShared == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method setShared ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_setShared);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_setShared */

#ifndef UNUSED_java_lang_StringBuffer_getValue
JRIMethodID FAR methodID_java_lang_StringBuffer_getValue = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jref)
java_lang_StringBuffer_getValue(JRIEnv* env, struct java_lang_StringBuffer* self) {
	if (methodID_java_lang_StringBuffer_getValue == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_StringBuffer(env) before calling method getValue ()[C");
	}
	return (jref)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_StringBuffer_getValue);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_StringBuffer_getValue */

#ifndef UNUSED_use_java_lang_StringBuffer

static jglobal _globalclass_java_lang_StringBuffer = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_java_lang_StringBuffer(JRIEnv* env)
{
	if (_globalclass_java_lang_StringBuffer == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_lang_StringBuffer);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_java_lang_StringBuffer);
			return NULL;
		}
		use_java_lang_StringBuffer_value(env, clazz);
		use_java_lang_StringBuffer_count(env, clazz);
		use_java_lang_StringBuffer_shared(env, clazz);
		use_java_lang_StringBuffer_new(env, clazz);
		use_java_lang_StringBuffer_new_1(env, clazz);
		use_java_lang_StringBuffer_new_2(env, clazz);
		use_java_lang_StringBuffer_length(env, clazz);
		use_java_lang_StringBuffer_capacity(env, clazz);
		use_java_lang_StringBuffer_copyWhenShared(env, clazz);
		use_java_lang_StringBuffer_ensureCapacity(env, clazz);
		use_java_lang_StringBuffer_setLength(env, clazz);
		use_java_lang_StringBuffer_charAt(env, clazz);
		use_java_lang_StringBuffer_getChars(env, clazz);
		use_java_lang_StringBuffer_setCharAt(env, clazz);
		use_java_lang_StringBuffer_append(env, clazz);
		use_java_lang_StringBuffer_append_1(env, clazz);
		use_java_lang_StringBuffer_append_2(env, clazz);
		use_java_lang_StringBuffer_append_3(env, clazz);
		use_java_lang_StringBuffer_append_4(env, clazz);
		use_java_lang_StringBuffer_append_5(env, clazz);
		use_java_lang_StringBuffer_append_6(env, clazz);
		use_java_lang_StringBuffer_append_7(env, clazz);
		use_java_lang_StringBuffer_append_8(env, clazz);
		use_java_lang_StringBuffer_append_9(env, clazz);
		use_java_lang_StringBuffer_insert(env, clazz);
		use_java_lang_StringBuffer_insert_1(env, clazz);
		use_java_lang_StringBuffer_insert_2(env, clazz);
		use_java_lang_StringBuffer_insert_3(env, clazz);
		use_java_lang_StringBuffer_insert_4(env, clazz);
		use_java_lang_StringBuffer_insert_5(env, clazz);
		use_java_lang_StringBuffer_insert_6(env, clazz);
		use_java_lang_StringBuffer_insert_7(env, clazz);
		use_java_lang_StringBuffer_insert_8(env, clazz);
		use_java_lang_StringBuffer_reverse(env, clazz);
		use_java_lang_StringBuffer_toString(env, clazz);
		use_java_lang_StringBuffer_setShared(env, clazz);
		use_java_lang_StringBuffer_getValue(env, clazz);
		_globalclass_java_lang_StringBuffer = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_java_lang_StringBuffer);
	}
}

JRI_PUBLIC_API(void)
unuse_java_lang_StringBuffer(JRIEnv* env)
{
	if (_globalclass_java_lang_StringBuffer != NULL) {
		struct java_lang_Class* clazz = (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_java_lang_StringBuffer);
		unuse_java_lang_StringBuffer_value(env, clazz);
		unuse_java_lang_StringBuffer_count(env, clazz);
		unuse_java_lang_StringBuffer_shared(env, clazz);
		unuse_java_lang_StringBuffer_new(env, clazz);
		unuse_java_lang_StringBuffer_new_1(env, clazz);
		unuse_java_lang_StringBuffer_new_2(env, clazz);
		unuse_java_lang_StringBuffer_length(env, clazz);
		unuse_java_lang_StringBuffer_capacity(env, clazz);
		unuse_java_lang_StringBuffer_copyWhenShared(env, clazz);
		unuse_java_lang_StringBuffer_ensureCapacity(env, clazz);
		unuse_java_lang_StringBuffer_setLength(env, clazz);
		unuse_java_lang_StringBuffer_charAt(env, clazz);
		unuse_java_lang_StringBuffer_getChars(env, clazz);
		unuse_java_lang_StringBuffer_setCharAt(env, clazz);
		unuse_java_lang_StringBuffer_append(env, clazz);
		unuse_java_lang_StringBuffer_append_1(env, clazz);
		unuse_java_lang_StringBuffer_append_2(env, clazz);
		unuse_java_lang_StringBuffer_append_3(env, clazz);
		unuse_java_lang_StringBuffer_append_4(env, clazz);
		unuse_java_lang_StringBuffer_append_5(env, clazz);
		unuse_java_lang_StringBuffer_append_6(env, clazz);
		unuse_java_lang_StringBuffer_append_7(env, clazz);
		unuse_java_lang_StringBuffer_append_8(env, clazz);
		unuse_java_lang_StringBuffer_append_9(env, clazz);
		unuse_java_lang_StringBuffer_insert(env, clazz);
		unuse_java_lang_StringBuffer_insert_1(env, clazz);
		unuse_java_lang_StringBuffer_insert_2(env, clazz);
		unuse_java_lang_StringBuffer_insert_3(env, clazz);
		unuse_java_lang_StringBuffer_insert_4(env, clazz);
		unuse_java_lang_StringBuffer_insert_5(env, clazz);
		unuse_java_lang_StringBuffer_insert_6(env, clazz);
		unuse_java_lang_StringBuffer_insert_7(env, clazz);
		unuse_java_lang_StringBuffer_insert_8(env, clazz);
		unuse_java_lang_StringBuffer_reverse(env, clazz);
		unuse_java_lang_StringBuffer_toString(env, clazz);
		unuse_java_lang_StringBuffer_setShared(env, clazz);
		unuse_java_lang_StringBuffer_getValue(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_java_lang_StringBuffer);
		_globalclass_java_lang_StringBuffer = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_java_lang_StringBuffer */

#ifdef _implementing_java_lang_StringBuffer

JRI_PUBLIC_API(struct java_lang_Class*)
register_java_lang_StringBuffer(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		NULL
	};
	void* nativeProcs[] = {
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_lang_StringBuffer);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_java_lang_StringBuffer);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_java_lang_StringBuffer(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_java_lang_StringBuffer(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_lang_StringBuffer);
	JRI_UnregisterNatives(env, clazz);
	unuse_java_lang_StringBuffer(env);
}

#endif /* _implementing_java_lang_StringBuffer */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

#endif /* NO_JDK */

