#	GNUmakefile 
#       Developed by Siddharth Bajaj
#	$Id: Makefile.others,v 1.1.4.1 2006/04/13 19:11:03 bagrawala Exp $
#

ECAS_HOME = ../../../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg

SPECIAL_winnt_SUBDIRS = libvsptam loadreg_exe libvssmauth
SPECIAL_sparc_SUBDIRS = mod_pta libvssmauth
SPECIAL_hpux_SUBDIRS = mod_pta

SUBDIRS = libvsssc libvsptan $(SPECIAL_$(TARCH)_SUBDIRS)

include $(ECAS_RULES_DIR)/directory.cfg

