#	GNUmakefile 
#       Developed by Abhay Ranade
#		Modified  by Narinder
#	$Id: GNUmakefile,v 1.1.2.1 2001/09/12 00:23:15 npaul Exp $
#

ECAS_HOME = ../../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


ifeq ($(CISCO), 1)
SPECIAL_sparc_DIRS = cisco
endif

SUBDIRS = pestub


include $(ECAS_RULES_DIR)/directory.cfg

