#	GNUmakefile 
#       Developed by Wasim Ilkal
#

ECAS_HOME = ../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


ifeq ($(CISCO), 1)
SPECIAL_sparc_DIRS = cisco
endif

SUBDIRS = activex plugins


include $(ECAS_RULES_DIR)/directory.cfg

