#	GNUmakefile 
#       
#	$Id: GNUmakefile,v 1.1.4.1 2003/05/06 17:03:01 npaul Exp $
#

ECAS_HOME = ../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


ifeq ($(CISCO), 1)
SPECIAL_sparc_DIRS = cisco
endif

SUBDIRS = activex 


include $(ECAS_RULES_DIR)/directory.cfg

