#	GNUmakefile 
#       Developed by Abhay Ranade
#	$Id: GNUmakefile,v 1.1.4.1 2000/11/21 00:01:02 sbajaj Exp $
#

ECAS_HOME = ../../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg

SPECIAL_winnt_SUBDIRS=valConfig

SUBDIRS = $(SPECIAL_$(TARCH)_SUBDIRS) configfiles certcache


include $(ECAS_RULES_DIR)/directory.cfg

