#	GNUmakefile for the ecas module
#	Developed by Raj Srinivasan
#	$Id: GNUmakefile,v 1.1.4.1 2006/04/13 19:14:21 bagrawala Exp $
#

ECAS_HOME=../../../../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


SUBDIRS = dynamic

include $(ECAS_RULES_DIR)/directory.cfg
