#	GNUmakefile 
#       Developed by Abhay Ranade
#	$Id: GNUmakefile,v 1.2.696.2 2006/11/18 09:38:57 schenna Exp $
#

ECAS_HOME = ../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg

SUBDIRS = fragments templates engine


include $(ECAS_RULES_DIR)/directory.cfg

