#ifndef VSPRS_ERRORS_H
#define VSPRS_ERRORS_H

#define VSPRS_OPEN_PTA_FAILED				0xF001
#define VSPRS_INVALID_PTA_APPLICATION		0xF002
#define VSPRS_INVALID_PROXY_INFO            0xF003
#define VSPRS_INVALID_EML_MESSAGE           0xF004
#define VSPRS_OUT_OF_MEMORY					0xF005
#define VSPRS_OPEN_PTA_PROFILE_FAILED		0xF006
#define VSPRS_CAN_NOT_PARSE_ENC_MESSAGE		0xF007
#define VSPRS_PARSE_ENVELOPED_DATA_FAILED	0xF008
#define	VSPRS_CAN_NOT_PARSE_SIGNED_MESSAGE	0xF009
#define	VSPRS_PKCS7_TYPE_IS_NOT_SIGNED_MESSAGE_TYPE	0xF00A
#define	VSPRS_PARSE_SIGNED_DATA_FAILED		0xF00B
#define VSPRS_INVALID_PKCS7_TYPE			0xF00C
#define VSPRS_VERIFY_SIGNATURE_FAILED       0xF00D
#define VSPRS_PKCS7_TYPE_IS_NOT_ENVELOPED_MESSAGE_TYPE 0xF00E
#define VSPRS_NULL_PTR_EXCEPTION			0xF00F
#define VSPRS_MISSING_ENCRYPTION_CERT		0xF010
#define  VSPRS_CAN_NOT_PARSE_OTHER_MESSAGE   0xF011
#define VSPRS_MISSING_REENCRYPT_PARMS        0xF012
#define VSPRS_MISSING_ROAMING_CLIENT_INFO	 0xF013
#define VSPRS_MISSING_SSC_EMAIL              0xF014
#endif