#	GNUmakefile 
#       Developed by Abhay Ranade
#

ECAS_HOME = ../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


ifeq ($(CISCO), 1)
SPECIAL_sparc_DIRS = cisco
endif

SUBDIRS = vsdnotz


include $(ECAS_RULES_DIR)/directory.cfg
