#	GNUmakefile 
#       Developed by Siddharth Bajaj
#	$Id: GNUmakefile,v 1.1.4.1 2001/10/12 07:53:14 sbajaj Exp $
#

ECAS_HOME = ../../../../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg


SUBDIRS = dynamic

include $(ECAS_RULES_DIR)/directory.cfg

