//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by vsdnotz.rc
//
#define IDBTN3                          3
#define IDBTN4                          4
#define IDS_PROJNAME                    100
#define IDB_VSNZ                        101
#define IDS_NOTARIZE                    101
#define IDR_VSNZ                        102
#define IDS_MENU_STATUS                 102
#define IDS_SELFILE_FILENAMELBL         103
#define IDS_REG_QUERY_ERR               104
#define IDS_BROWSE                      104
#define IDS_FILEFILTER                  105
#define IDS_VRSNDNZ                     106
#define IDS_BADREQUEST                  106
#define IDS_FILEOPEN                    107
#define IDS_PREV                        108
#define IDS_NEXT                        109
#define IDS_CANCEL                      110
#define IDS_SELECT                      111
#define IDS_HELP                        112
#define IDS_SELFILE_TITLE               113
#define IDS_SELFILE_TEXT                114
#define IDS_CREATENOTREQ_WIZTITLE       115
#define IDS_FINISH                      116
#define IDS_DONE                        117
#define IDS_PROGRESS_TEXT               118
#define IDS_PROGRESS_TITLE              119
#define IDS_RCPTVRFY_GOOD               120
#define IDS_RCPTVRFY_BAD                121
#define IDS_INTEGRITY_GOOD              122
#define IDS_INTEGRITY_BAD               123
#define IDS_VERFYRCPT_TITLE             124
#define IDS_VERFYRCPTTXT_TEXT           125
#define IDS_NZSERVER_ERR                126
#define IDS_CERT_EXP                    127
#define IDS_CERT_INVALID                128
#define IDS_USR_SETTINGS_ERR            129
#define IDS_USR_SETTINGS_ERR2           130
#define IDS_CREATE_REQ                  131
#define IDS_SIGN_REQ                    132
#define IDS_SEND_REQ                    133
#define IDS_VERIFY_RESP                 134
#define IDS_NZ_COMPLETE2                135
#define IDS_NZ_GENERAL_ERR              136
#define IDS_SIG_VERIFY_ERR              137
#define IDS_NOT_TRUSTED                 138
#define IDS_CERT_REVOKED                139
#define IDS_INVALID_ALG                 140
#define IDS_MEM_ERR                     141
#define IDS_RANDOM_GEN_ERR              142
#define IDS_HASH_ERR                    143
#define IDS_BADATAFORMAT                144
#define IDS_SIGN_ERR                    145
#define IDS_INVALID_NZ_SERVER_PATH      146
#define IDS_INET_SEND_ERR               147
#define IDS_INET_QUERY_ERR              148
#define IDS_NZ_BAD_STAT                 149
#define IDS_INET_READ_ERR               150
#define IDS_RECEIPT_TITLE               151
#define IDS_RECEIPT_DESC                152
#define IDS_RECEIPT_FOR                 153
#define IDS_RECEIPT_DOC                 154
#define IDS_RECEIPT_DATE                155
#define IDS_RECEIPT_TIME                156
#define IDS_RECEIPT_DETAILS             157
#define IDS_RECEIPT_VERIFY_ERR          158
#define IDS_RECEIPT_INTEGRITY_ERR       159
#define IDS_DIGID                       160
#define IDS_GET_SETTINGS                161
#define IDS_PARSE_RESP_ERR              162
#define IDS_INVALID_VER                 163
#define IDS_INVALID_NONCE               164
#define IDS_VERF_GENERAL_ERR            165
#define IDS_INVALID_RECORD_SIZE         166
#define IDS_INVALID_RECORD_FORMAT       167
#define IDS_DOC_NOACCESS                168
#define IDS_DOC_EXISTS                  169
#define IDS_DOC_SHARE_ERR               170
#define IDS_CDP_GET_ERR                 171
#define IDS_SELID_ERR                   172
#define IDS_PROFILE_CORRUPT             173
#define IDS_VS_NZ                       174
#define IDS_ERROR                       175
#define IDS_NZ_COMPLETE                 176
#define IDS_CLOSE                       177
#define IDS_SELID_TITLE                 178
#define IDS_OPENPROF_TITLE              179
#define IDS_LGNDLG_TITLE                180
#define IDS_SIGNDLG_TITLE               181
#define IDS_INVALID_POLICY              182
#define IDS_BADALGID                    183
#define IDS_TIMENOTAVAIL                184
#define IDS_ERRPOLICY                   185
#define IDS_ERREXTENSION                186
#define IDS_ERRINFO                     187
#define IDS_SYSFAIL                     188
#define IDS_CDP_ABSENT                  189
#define IDS_SELFILE_ERR                 190
#define IDS_PROMPT_FOR_DOC              191
#define IDS_LOCATE_DOC                  192
#define IDS_DNZ_ERROR                   193
#define IDS_NZ_RCPT                     194
#define IDS_SELIDCHKBOX_TEXT            195
#define IDS_SELF_SIGNED                 196
#define IDS_RCPTFILE_ERR                197
#define IDS_CLIENT_AUTH_ERR             198
#define IDS_SEC_CERT_ERR                199
#define IDS_SELFILE_ERR2                200
#define IDD_DNZUI                       201
#define IDBTN2                          201
#define IDS_SCRIPT                      201
#define IDC_PROGRESS1                   202
#define IDS_NAVIGATOR                   202
#define IDC_LABEL2                      203
#define IDS_UAGENT                      203
#define IDC_RBS                         204
#define IDS_USR_SETTINGS_ERR3           204
#define IDC_DIGRCPT                     205
#define IDS_NZERR_ALG                   205
#define IDC_LABEL3                      206
#define IDS_NZERR_WRONG_FORMAT          206
#define IDB_RBS                         207
#define IDC_LABEL4                      207
#define IDS_NZERR_TIME_UNAVAIL          207
#define IDC_LABEL5                      208
#define IDS_NZERR_SIG_FAIL              208
#define IDC_LABEL6                      209
#define IDS_NZERR_CERT_REVOKED          209
#define IDC_ERROR                       210
#define IDB_ERROR                       210
#define IDS_NZERR_CERT_EXPIRED          210
#define IDC_LABEL7                      211
#define IDS_NZERR_CERT_INVALID          211
#define IDC_TOP_SEPARATOR               212
#define IDS_NZERR_CERT_ABSENT           212
#define IDC_BOTTOM_SEPARATOR            213
#define IDS_NZERR_NO_ACCT               213
#define IDB_VSLARGE                     214
#define IDC_LABEL2_1                    214
#define IDS_NZERR_ACCT_INVALID          214
#define IDC_HEADER_LOGO                 215
#define IDB_DIGRCPT                     215
#define IDS_NZERR_LIMIT                 215
#define IDC_HEADER_TITLE                216
#define IDB_INVALID_DIGRCPT             216
#define IDC_UI_TITLE                    217
#define IDS_RECEIPT_SAVE                217
#define IDC_UI_TEXT                     218
#define IDS_RECEIPT_VIEW                218
#define IDC_LABEL1                      219
#define IDB_VALID                       219
#define IDS_SAVE_DOC                    219
#define IDC_EDIT1                       220
#define IDS_DOCSAVED_MESG               220
#define IDB_VALIDRBS                    221
#define IDS_RCPTSAVED_MESG              221
#define IDB_INVALIDRBS                  222
#define IDS_SAVEDMESG_TITLE             222
#define IDC_LABEL4_1                    223
#define IDC_LABEL3_3                    224
#define IDB_INVALID                     224
#define IDS_VIEWDOC_WEB_ERR             224
#define IDC_EDIT_RDONLY                 225
#define IDS_VIEWDOC_ERR_TITLE           225
#define IDC_LABEL5_1                    226
#define IDI_ICON1                       226
#define IDS_VIEWDOC_APP_ERR             226
#define IDC_VALIDBMP                    228
#define IDC_VALIDRBS                    229
#define IDC_VRSN_LOGO                   230
#define IDC_INVALIDRBS                  231
#define IDC_INVALIDBMP                  232
#define IDC_LABEL8                      233
#define IDC_LABEL9                      234
#define IDC_LABEL3_4                    235

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        231
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         236
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
