/**
*  Generic Wrapper Global Constants
**/

#define VS_LOG_FAILURE "error"
#define VS_LOG_SECURITY "security"
#define VS_LOG_WARN "warning"
#define VS_LOG_INFO "info"
#define VS_LOG_ACCESS "access"
#define VS_LOG_DEBUG "debug"

/**
*  For setting certificate extensions to env
**/
#define EMAIL_ADDRESS "EMAIL_ADDRESS"
#define COMMON_NAME "COMMON_NAME"
#define TITLE "TITLE"
#define UNIQUE_ID "UNIQUE_ID"
#define ADDRESS "ADDRESS"
#define ORGANIZATION "ORGANIZATION"
#define ORG_UNIT_COUNT "ORG_UNIT_COUNT"
#define ORGANIZATION_UNITS "ORGANIZATION_UNITS"
#define ISSUER_ORGANIZATION "ISSUER_ORGANIZATION"
#define ISSUER_LOCALITY "ISSUER_LOCALITY"
#define ISSUER_COUNTRY "ISUER_COUNTRY"
#define ISSUER_COMMON_NAME "ISSUER_COMMON_NAME"
#define ISSUER_ORG_UNIT_COUNT "ISSUER_ORG_UNIT_COUNT"
#define ISSUER_ORGANIZATION_UNITS "ISSUER_ORGANIZATION_UNITS"
#define NOT_BEFORE "NOT_BEFORE"
#define NOT_AFTER "NO_AFTER"

