#	GNUmakefile 
#       Developed by Abhay Ranade
#	$Id: GNUmakefile,v 1.2.710.2 2006/11/18 09:39:07 schenna Exp $
#

ECAS_HOME = ../../../../../../..

include $(ECAS_CUSTOM_CFG)
include $(ECAS_COMMON_DIR)/directory.cfg

SUBDIRS = tutorial


include $(ECAS_RULES_DIR)/directory.cfg

