/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Header for class java/util/Date */

#ifndef _java_util_Date_H_
#define _java_util_Date_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct java_lang_String;
struct java_util_Date;
struct java_lang_Object;
struct java_lang_Class;

/*******************************************************************************
 * Class java/util/Date
 ******************************************************************************/

typedef struct java_util_Date java_util_Date;

#define classname_java_util_Date	"java/util/Date"

#define class_java_util_Date(env) \
	((struct java_lang_Class*)JRI_FindClass(env, classname_java_util_Date))

/*******************************************************************************
 * Public Methods
 ******************************************************************************/

#ifdef DEBUG

/*** public <init> ()V ***/
extern JRI_PUBLIC_API(struct java_util_Date*)
java_util_Date_new(JRIEnv* env, struct java_lang_Class* clazz);

/*** public <init> (J)V ***/
extern JRI_PUBLIC_API(struct java_util_Date*)
java_util_Date_new_1(JRIEnv* env, struct java_lang_Class* clazz, jlong a);

/*** public <init> (III)V ***/
extern JRI_PUBLIC_API(struct java_util_Date*)
java_util_Date_new_2(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c);

/*** public <init> (IIIII)V ***/
extern JRI_PUBLIC_API(struct java_util_Date*)
java_util_Date_new_3(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c, jint d, jint e);

/*** public <init> (IIIIII)V ***/
extern JRI_PUBLIC_API(struct java_util_Date*)
java_util_Date_new_4(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c, jint d, jint e, jint f);

/*** public <init> (Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(struct java_util_Date*)
java_util_Date_new_5(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a);

/*** public static UTC (IIIIII)J ***/
extern JRI_PUBLIC_API(jlong)
java_util_Date_UTC(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c, jint d, jint e, jint f);

/*** public static parse (Ljava/lang/String;)J ***/
extern JRI_PUBLIC_API(jlong)
java_util_Date_parse(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a);

/*** public getYear ()I ***/
extern JRI_PUBLIC_API(jint)
java_util_Date_getYear(JRIEnv* env, struct java_util_Date* self);

/*** public setYear (I)V ***/
extern JRI_PUBLIC_API(void)
java_util_Date_setYear(JRIEnv* env, struct java_util_Date* self, jint a);

/*** public getMonth ()I ***/
extern JRI_PUBLIC_API(jint)
java_util_Date_getMonth(JRIEnv* env, struct java_util_Date* self);

/*** public setMonth (I)V ***/
extern JRI_PUBLIC_API(void)
java_util_Date_setMonth(JRIEnv* env, struct java_util_Date* self, jint a);

/*** public getDate ()I ***/
extern JRI_PUBLIC_API(jint)
java_util_Date_getDate(JRIEnv* env, struct java_util_Date* self);

/*** public setDate (I)V ***/
extern JRI_PUBLIC_API(void)
java_util_Date_setDate(JRIEnv* env, struct java_util_Date* self, jint a);

/*** public getDay ()I ***/
extern JRI_PUBLIC_API(jint)
java_util_Date_getDay(JRIEnv* env, struct java_util_Date* self);

/*** public getHours ()I ***/
extern JRI_PUBLIC_API(jint)
java_util_Date_getHours(JRIEnv* env, struct java_util_Date* self);

/*** public setHours (I)V ***/
extern JRI_PUBLIC_API(void)
java_util_Date_setHours(JRIEnv* env, struct java_util_Date* self, jint a);

/*** public getMinutes ()I ***/
extern JRI_PUBLIC_API(jint)
java_util_Date_getMinutes(JRIEnv* env, struct java_util_Date* self);

/*** public setMinutes (I)V ***/
extern JRI_PUBLIC_API(void)
java_util_Date_setMinutes(JRIEnv* env, struct java_util_Date* self, jint a);

/*** public getSeconds ()I ***/
extern JRI_PUBLIC_API(jint)
java_util_Date_getSeconds(JRIEnv* env, struct java_util_Date* self);

/*** public setSeconds (I)V ***/
extern JRI_PUBLIC_API(void)
java_util_Date_setSeconds(JRIEnv* env, struct java_util_Date* self, jint a);

/*** public getTime ()J ***/
extern JRI_PUBLIC_API(jlong)
java_util_Date_getTime(JRIEnv* env, struct java_util_Date* self);

/*** public setTime (J)V ***/
extern JRI_PUBLIC_API(void)
java_util_Date_setTime(JRIEnv* env, struct java_util_Date* self, jlong a);

/*** public before (Ljava/util/Date;)Z ***/
extern JRI_PUBLIC_API(jbool)
java_util_Date_before(JRIEnv* env, struct java_util_Date* self, struct java_util_Date *a);

/*** public after (Ljava/util/Date;)Z ***/
extern JRI_PUBLIC_API(jbool)
java_util_Date_after(JRIEnv* env, struct java_util_Date* self, struct java_util_Date *a);

/*** public equals (Ljava/lang/Object;)Z ***/
extern JRI_PUBLIC_API(jbool)
java_util_Date_equals(JRIEnv* env, struct java_util_Date* self, struct java_lang_Object *a);

/*** public hashCode ()I ***/
extern JRI_PUBLIC_API(jint)
java_util_Date_hashCode(JRIEnv* env, struct java_util_Date* self);

/*** public native toString ()Ljava/lang/String; ***/
extern JRI_PUBLIC_API(struct java_lang_String *)
java_util_Date_toString(JRIEnv* env, struct java_util_Date* self);

/*** public native toLocaleString ()Ljava/lang/String; ***/
extern JRI_PUBLIC_API(struct java_lang_String *)
java_util_Date_toLocaleString(JRIEnv* env, struct java_util_Date* self);

/*** public native toGMTString ()Ljava/lang/String; ***/
extern JRI_PUBLIC_API(struct java_lang_String *)
java_util_Date_toGMTString(JRIEnv* env, struct java_util_Date* self);

/*** public getTimezoneOffset ()I ***/
extern JRI_PUBLIC_API(jint)
java_util_Date_getTimezoneOffset(JRIEnv* env, struct java_util_Date* self);

#else /* !DEBUG */

/*** public <init> ()V ***/
#define java_util_Date_new(env, clazz)	\
	((struct java_util_Date*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_util_Date_new))

/*** public <init> (J)V ***/
#define java_util_Date_new_1(env, clazz, a)	\
	((struct java_util_Date*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_util_Date_new_1, a))

/*** public <init> (III)V ***/
#define java_util_Date_new_2(env, clazz, a, b, c)	\
	((struct java_util_Date*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_util_Date_new_2, a, b, c))

/*** public <init> (IIIII)V ***/
#define java_util_Date_new_3(env, clazz, a, b, c, d, e)	\
	((struct java_util_Date*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_util_Date_new_3, a, b, c, d, e))

/*** public <init> (IIIIII)V ***/
#define java_util_Date_new_4(env, clazz, a, b, c, d, e, f)	\
	((struct java_util_Date*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_util_Date_new_4, a, b, c, d, e, f))

/*** public <init> (Ljava/lang/String;)V ***/
#define java_util_Date_new_5(env, clazz, a)	\
	((struct java_util_Date*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_util_Date_new_5, a))

/*** public static UTC (IIIIII)J ***/
#define java_util_Date_UTC(env, clazz, a, b, c, d, e, f) \
	((jlong)JRI_CallStaticMethodLong(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_util_Date_UTC, a, b, c, d, e, f))

/*** public static parse (Ljava/lang/String;)J ***/
#define java_util_Date_parse(env, clazz, a) \
	((jlong)JRI_CallStaticMethodLong(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_util_Date_parse, a))

/*** public getYear ()I ***/
#define java_util_Date_getYear(env, obj) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_getYear))

/*** public setYear (I)V ***/
#define java_util_Date_setYear(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_setYear, a))

/*** public getMonth ()I ***/
#define java_util_Date_getMonth(env, obj) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_getMonth))

/*** public setMonth (I)V ***/
#define java_util_Date_setMonth(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_setMonth, a))

/*** public getDate ()I ***/
#define java_util_Date_getDate(env, obj) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_getDate))

/*** public setDate (I)V ***/
#define java_util_Date_setDate(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_setDate, a))

/*** public getDay ()I ***/
#define java_util_Date_getDay(env, obj) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_getDay))

/*** public getHours ()I ***/
#define java_util_Date_getHours(env, obj) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_getHours))

/*** public setHours (I)V ***/
#define java_util_Date_setHours(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_setHours, a))

/*** public getMinutes ()I ***/
#define java_util_Date_getMinutes(env, obj) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_getMinutes))

/*** public setMinutes (I)V ***/
#define java_util_Date_setMinutes(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_setMinutes, a))

/*** public getSeconds ()I ***/
#define java_util_Date_getSeconds(env, obj) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_getSeconds))

/*** public setSeconds (I)V ***/
#define java_util_Date_setSeconds(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_setSeconds, a))

/*** public getTime ()J ***/
#define java_util_Date_getTime(env, obj) \
	((jlong)JRI_CallMethodLong(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_getTime))

/*** public setTime (J)V ***/
#define java_util_Date_setTime(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_setTime, a))

/*** public before (Ljava/util/Date;)Z ***/
#define java_util_Date_before(env, obj, a) \
	((jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_before, a))

/*** public after (Ljava/util/Date;)Z ***/
#define java_util_Date_after(env, obj, a) \
	((jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_after, a))

/*** public equals (Ljava/lang/Object;)Z ***/
#define java_util_Date_equals(env, obj, a) \
	((jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_equals, a))

/*** public hashCode ()I ***/
#define java_util_Date_hashCode(env, obj) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_hashCode))

/*** public native toString ()Ljava/lang/String; ***/
#define java_util_Date_toString(env, obj) \
	((struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_toString))

/*** public native toLocaleString ()Ljava/lang/String; ***/
#define java_util_Date_toLocaleString(env, obj) \
	((struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_toLocaleString))

/*** public native toGMTString ()Ljava/lang/String; ***/
#define java_util_Date_toGMTString(env, obj) \
	((struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_toGMTString))

/*** public getTimezoneOffset ()I ***/
#define java_util_Date_getTimezoneOffset(env, obj) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_getTimezoneOffset))

#endif /* !DEBUG*/

/*** public <init> ()V ***/
extern JRIMethodID FAR methodID_java_util_Date_new;
#define name_java_util_Date_new	"<init>"
#define sig_java_util_Date_new 	"()V"
#define use_java_util_Date_new(env, clazz)	\
	(methodID_java_util_Date_new =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_new,	\
			sig_java_util_Date_new))
#define unuse_java_util_Date_new(env, clazz)	\
	(methodID_java_util_Date_new = JRIUninitialized)

/*** public <init> (J)V ***/
extern JRIMethodID FAR methodID_java_util_Date_new_1;
#define name_java_util_Date_new_1	"<init>"
#define sig_java_util_Date_new_1 	"(J)V"
#define use_java_util_Date_new_1(env, clazz)	\
	(methodID_java_util_Date_new_1 =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_new_1,	\
			sig_java_util_Date_new_1))
#define unuse_java_util_Date_new_1(env, clazz)	\
	(methodID_java_util_Date_new_1 = JRIUninitialized)

/*** public <init> (III)V ***/
extern JRIMethodID FAR methodID_java_util_Date_new_2;
#define name_java_util_Date_new_2	"<init>"
#define sig_java_util_Date_new_2 	"(III)V"
#define use_java_util_Date_new_2(env, clazz)	\
	(methodID_java_util_Date_new_2 =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_new_2,	\
			sig_java_util_Date_new_2))
#define unuse_java_util_Date_new_2(env, clazz)	\
	(methodID_java_util_Date_new_2 = JRIUninitialized)

/*** public <init> (IIIII)V ***/
extern JRIMethodID FAR methodID_java_util_Date_new_3;
#define name_java_util_Date_new_3	"<init>"
#define sig_java_util_Date_new_3 	"(IIIII)V"
#define use_java_util_Date_new_3(env, clazz)	\
	(methodID_java_util_Date_new_3 =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_new_3,	\
			sig_java_util_Date_new_3))
#define unuse_java_util_Date_new_3(env, clazz)	\
	(methodID_java_util_Date_new_3 = JRIUninitialized)

/*** public <init> (IIIIII)V ***/
extern JRIMethodID FAR methodID_java_util_Date_new_4;
#define name_java_util_Date_new_4	"<init>"
#define sig_java_util_Date_new_4 	"(IIIIII)V"
#define use_java_util_Date_new_4(env, clazz)	\
	(methodID_java_util_Date_new_4 =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_new_4,	\
			sig_java_util_Date_new_4))
#define unuse_java_util_Date_new_4(env, clazz)	\
	(methodID_java_util_Date_new_4 = JRIUninitialized)

/*** public <init> (Ljava/lang/String;)V ***/
extern JRIMethodID FAR methodID_java_util_Date_new_5;
#define name_java_util_Date_new_5	"<init>"
#define sig_java_util_Date_new_5 	"(Ljava/lang/String;)V"
#define use_java_util_Date_new_5(env, clazz)	\
	(methodID_java_util_Date_new_5 =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_new_5,	\
			sig_java_util_Date_new_5))
#define unuse_java_util_Date_new_5(env, clazz)	\
	(methodID_java_util_Date_new_5 = JRIUninitialized)

/*** public static UTC (IIIIII)J ***/
extern JRIMethodID FAR methodID_java_util_Date_UTC;
#define name_java_util_Date_UTC	"UTC"
#define sig_java_util_Date_UTC 	"(IIIIII)J"
#define use_java_util_Date_UTC(env, clazz)	\
	(methodID_java_util_Date_UTC =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_util_Date_UTC,	\
			sig_java_util_Date_UTC))
#define unuse_java_util_Date_UTC(env, clazz)	\
	(methodID_java_util_Date_UTC = JRIUninitialized)

/*** public static parse (Ljava/lang/String;)J ***/
extern JRIMethodID FAR methodID_java_util_Date_parse;
#define name_java_util_Date_parse	"parse"
#define sig_java_util_Date_parse 	"(Ljava/lang/String;)J"
#define use_java_util_Date_parse(env, clazz)	\
	(methodID_java_util_Date_parse =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_util_Date_parse,	\
			sig_java_util_Date_parse))
#define unuse_java_util_Date_parse(env, clazz)	\
	(methodID_java_util_Date_parse = JRIUninitialized)

/*** public getYear ()I ***/
extern JRIMethodID FAR methodID_java_util_Date_getYear;
#define name_java_util_Date_getYear	"getYear"
#define sig_java_util_Date_getYear 	"()I"
#define use_java_util_Date_getYear(env, clazz)	\
	(methodID_java_util_Date_getYear =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_getYear,	\
			sig_java_util_Date_getYear))
#define unuse_java_util_Date_getYear(env, clazz)	\
	(methodID_java_util_Date_getYear = JRIUninitialized)

/*** public setYear (I)V ***/
extern JRIMethodID FAR methodID_java_util_Date_setYear;
#define name_java_util_Date_setYear	"setYear"
#define sig_java_util_Date_setYear 	"(I)V"
#define use_java_util_Date_setYear(env, clazz)	\
	(methodID_java_util_Date_setYear =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_setYear,	\
			sig_java_util_Date_setYear))
#define unuse_java_util_Date_setYear(env, clazz)	\
	(methodID_java_util_Date_setYear = JRIUninitialized)

/*** public getMonth ()I ***/
extern JRIMethodID FAR methodID_java_util_Date_getMonth;
#define name_java_util_Date_getMonth	"getMonth"
#define sig_java_util_Date_getMonth 	"()I"
#define use_java_util_Date_getMonth(env, clazz)	\
	(methodID_java_util_Date_getMonth =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_getMonth,	\
			sig_java_util_Date_getMonth))
#define unuse_java_util_Date_getMonth(env, clazz)	\
	(methodID_java_util_Date_getMonth = JRIUninitialized)

/*** public setMonth (I)V ***/
extern JRIMethodID FAR methodID_java_util_Date_setMonth;
#define name_java_util_Date_setMonth	"setMonth"
#define sig_java_util_Date_setMonth 	"(I)V"
#define use_java_util_Date_setMonth(env, clazz)	\
	(methodID_java_util_Date_setMonth =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_setMonth,	\
			sig_java_util_Date_setMonth))
#define unuse_java_util_Date_setMonth(env, clazz)	\
	(methodID_java_util_Date_setMonth = JRIUninitialized)

/*** public getDate ()I ***/
extern JRIMethodID FAR methodID_java_util_Date_getDate;
#define name_java_util_Date_getDate	"getDate"
#define sig_java_util_Date_getDate 	"()I"
#define use_java_util_Date_getDate(env, clazz)	\
	(methodID_java_util_Date_getDate =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_getDate,	\
			sig_java_util_Date_getDate))
#define unuse_java_util_Date_getDate(env, clazz)	\
	(methodID_java_util_Date_getDate = JRIUninitialized)

/*** public setDate (I)V ***/
extern JRIMethodID FAR methodID_java_util_Date_setDate;
#define name_java_util_Date_setDate	"setDate"
#define sig_java_util_Date_setDate 	"(I)V"
#define use_java_util_Date_setDate(env, clazz)	\
	(methodID_java_util_Date_setDate =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_setDate,	\
			sig_java_util_Date_setDate))
#define unuse_java_util_Date_setDate(env, clazz)	\
	(methodID_java_util_Date_setDate = JRIUninitialized)

/*** public getDay ()I ***/
extern JRIMethodID FAR methodID_java_util_Date_getDay;
#define name_java_util_Date_getDay	"getDay"
#define sig_java_util_Date_getDay 	"()I"
#define use_java_util_Date_getDay(env, clazz)	\
	(methodID_java_util_Date_getDay =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_getDay,	\
			sig_java_util_Date_getDay))
#define unuse_java_util_Date_getDay(env, clazz)	\
	(methodID_java_util_Date_getDay = JRIUninitialized)

/*** public getHours ()I ***/
extern JRIMethodID FAR methodID_java_util_Date_getHours;
#define name_java_util_Date_getHours	"getHours"
#define sig_java_util_Date_getHours 	"()I"
#define use_java_util_Date_getHours(env, clazz)	\
	(methodID_java_util_Date_getHours =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_getHours,	\
			sig_java_util_Date_getHours))
#define unuse_java_util_Date_getHours(env, clazz)	\
	(methodID_java_util_Date_getHours = JRIUninitialized)

/*** public setHours (I)V ***/
extern JRIMethodID FAR methodID_java_util_Date_setHours;
#define name_java_util_Date_setHours	"setHours"
#define sig_java_util_Date_setHours 	"(I)V"
#define use_java_util_Date_setHours(env, clazz)	\
	(methodID_java_util_Date_setHours =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_setHours,	\
			sig_java_util_Date_setHours))
#define unuse_java_util_Date_setHours(env, clazz)	\
	(methodID_java_util_Date_setHours = JRIUninitialized)

/*** public getMinutes ()I ***/
extern JRIMethodID FAR methodID_java_util_Date_getMinutes;
#define name_java_util_Date_getMinutes	"getMinutes"
#define sig_java_util_Date_getMinutes 	"()I"
#define use_java_util_Date_getMinutes(env, clazz)	\
	(methodID_java_util_Date_getMinutes =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_getMinutes,	\
			sig_java_util_Date_getMinutes))
#define unuse_java_util_Date_getMinutes(env, clazz)	\
	(methodID_java_util_Date_getMinutes = JRIUninitialized)

/*** public setMinutes (I)V ***/
extern JRIMethodID FAR methodID_java_util_Date_setMinutes;
#define name_java_util_Date_setMinutes	"setMinutes"
#define sig_java_util_Date_setMinutes 	"(I)V"
#define use_java_util_Date_setMinutes(env, clazz)	\
	(methodID_java_util_Date_setMinutes =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_setMinutes,	\
			sig_java_util_Date_setMinutes))
#define unuse_java_util_Date_setMinutes(env, clazz)	\
	(methodID_java_util_Date_setMinutes = JRIUninitialized)

/*** public getSeconds ()I ***/
extern JRIMethodID FAR methodID_java_util_Date_getSeconds;
#define name_java_util_Date_getSeconds	"getSeconds"
#define sig_java_util_Date_getSeconds 	"()I"
#define use_java_util_Date_getSeconds(env, clazz)	\
	(methodID_java_util_Date_getSeconds =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_getSeconds,	\
			sig_java_util_Date_getSeconds))
#define unuse_java_util_Date_getSeconds(env, clazz)	\
	(methodID_java_util_Date_getSeconds = JRIUninitialized)

/*** public setSeconds (I)V ***/
extern JRIMethodID FAR methodID_java_util_Date_setSeconds;
#define name_java_util_Date_setSeconds	"setSeconds"
#define sig_java_util_Date_setSeconds 	"(I)V"
#define use_java_util_Date_setSeconds(env, clazz)	\
	(methodID_java_util_Date_setSeconds =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_setSeconds,	\
			sig_java_util_Date_setSeconds))
#define unuse_java_util_Date_setSeconds(env, clazz)	\
	(methodID_java_util_Date_setSeconds = JRIUninitialized)

/*** public getTime ()J ***/
extern JRIMethodID FAR methodID_java_util_Date_getTime;
#define name_java_util_Date_getTime	"getTime"
#define sig_java_util_Date_getTime 	"()J"
#define use_java_util_Date_getTime(env, clazz)	\
	(methodID_java_util_Date_getTime =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_getTime,	\
			sig_java_util_Date_getTime))
#define unuse_java_util_Date_getTime(env, clazz)	\
	(methodID_java_util_Date_getTime = JRIUninitialized)

/*** public setTime (J)V ***/
extern JRIMethodID FAR methodID_java_util_Date_setTime;
#define name_java_util_Date_setTime	"setTime"
#define sig_java_util_Date_setTime 	"(J)V"
#define use_java_util_Date_setTime(env, clazz)	\
	(methodID_java_util_Date_setTime =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_setTime,	\
			sig_java_util_Date_setTime))
#define unuse_java_util_Date_setTime(env, clazz)	\
	(methodID_java_util_Date_setTime = JRIUninitialized)

/*** public before (Ljava/util/Date;)Z ***/
extern JRIMethodID FAR methodID_java_util_Date_before;
#define name_java_util_Date_before	"before"
#define sig_java_util_Date_before 	"(Ljava/util/Date;)Z"
#define use_java_util_Date_before(env, clazz)	\
	(methodID_java_util_Date_before =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_before,	\
			sig_java_util_Date_before))
#define unuse_java_util_Date_before(env, clazz)	\
	(methodID_java_util_Date_before = JRIUninitialized)

/*** public after (Ljava/util/Date;)Z ***/
extern JRIMethodID FAR methodID_java_util_Date_after;
#define name_java_util_Date_after	"after"
#define sig_java_util_Date_after 	"(Ljava/util/Date;)Z"
#define use_java_util_Date_after(env, clazz)	\
	(methodID_java_util_Date_after =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_after,	\
			sig_java_util_Date_after))
#define unuse_java_util_Date_after(env, clazz)	\
	(methodID_java_util_Date_after = JRIUninitialized)

/*** public equals (Ljava/lang/Object;)Z ***/
extern JRIMethodID FAR methodID_java_util_Date_equals;
#define name_java_util_Date_equals	"equals"
#define sig_java_util_Date_equals 	"(Ljava/lang/Object;)Z"
#define use_java_util_Date_equals(env, clazz)	\
	(methodID_java_util_Date_equals =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_equals,	\
			sig_java_util_Date_equals))
#define unuse_java_util_Date_equals(env, clazz)	\
	(methodID_java_util_Date_equals = JRIUninitialized)

/*** public hashCode ()I ***/
extern JRIMethodID FAR methodID_java_util_Date_hashCode;
#define name_java_util_Date_hashCode	"hashCode"
#define sig_java_util_Date_hashCode 	"()I"
#define use_java_util_Date_hashCode(env, clazz)	\
	(methodID_java_util_Date_hashCode =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_hashCode,	\
			sig_java_util_Date_hashCode))
#define unuse_java_util_Date_hashCode(env, clazz)	\
	(methodID_java_util_Date_hashCode = JRIUninitialized)

/*** public native toString ()Ljava/lang/String; ***/
extern JRIMethodID FAR methodID_java_util_Date_toString;
#define name_java_util_Date_toString	"toString"
#define sig_java_util_Date_toString 	"()Ljava/lang/String;"
#define use_java_util_Date_toString(env, clazz)	\
	(methodID_java_util_Date_toString =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_toString,	\
			sig_java_util_Date_toString))
#define unuse_java_util_Date_toString(env, clazz)	\
	(methodID_java_util_Date_toString = JRIUninitialized)

/*** public native toLocaleString ()Ljava/lang/String; ***/
extern JRIMethodID FAR methodID_java_util_Date_toLocaleString;
#define name_java_util_Date_toLocaleString	"toLocaleString"
#define sig_java_util_Date_toLocaleString 	"()Ljava/lang/String;"
#define use_java_util_Date_toLocaleString(env, clazz)	\
	(methodID_java_util_Date_toLocaleString =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_toLocaleString,	\
			sig_java_util_Date_toLocaleString))
#define unuse_java_util_Date_toLocaleString(env, clazz)	\
	(methodID_java_util_Date_toLocaleString = JRIUninitialized)

/*** public native toGMTString ()Ljava/lang/String; ***/
extern JRIMethodID FAR methodID_java_util_Date_toGMTString;
#define name_java_util_Date_toGMTString	"toGMTString"
#define sig_java_util_Date_toGMTString 	"()Ljava/lang/String;"
#define use_java_util_Date_toGMTString(env, clazz)	\
	(methodID_java_util_Date_toGMTString =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_toGMTString,	\
			sig_java_util_Date_toGMTString))
#define unuse_java_util_Date_toGMTString(env, clazz)	\
	(methodID_java_util_Date_toGMTString = JRIUninitialized)

/*** public getTimezoneOffset ()I ***/
extern JRIMethodID FAR methodID_java_util_Date_getTimezoneOffset;
#define name_java_util_Date_getTimezoneOffset	"getTimezoneOffset"
#define sig_java_util_Date_getTimezoneOffset 	"()I"
#define use_java_util_Date_getTimezoneOffset(env, clazz)	\
	(methodID_java_util_Date_getTimezoneOffset =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_getTimezoneOffset,	\
			sig_java_util_Date_getTimezoneOffset))
#define unuse_java_util_Date_getTimezoneOffset(env, clazz)	\
	(methodID_java_util_Date_getTimezoneOffset = JRIUninitialized)

/*******************************************************************************
 * IMPLEMENTATION SECTION: 
 * Define the IMPLEMENT_java_util_Date symbol 
 * if you intend to implement the native methods of this class. This 
 * symbol makes the private and protected methods available. You should 
 * also call the register_java_util_Date routine 
 * to make your native methods available.
 ******************************************************************************/

extern JRI_PUBLIC_API(struct java_lang_Class*)
use_java_util_Date(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unuse_java_util_Date(JRIEnv* env);

extern JRI_PUBLIC_API(struct java_lang_Class*)
register_java_util_Date(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unregister_java_util_Date(JRIEnv* env);

#ifdef IMPLEMENT_java_util_Date

/*******************************************************************************
 * Native Methods: 
 * These are the signatures of the native methods which you must implement.
 ******************************************************************************/

/*** public native toString ()Ljava/lang/String; ***/
extern JRI_PUBLIC_API(struct java_lang_String *)
native_java_util_Date_toString(JRIEnv* env, struct java_util_Date* self);

/*** public native toLocaleString ()Ljava/lang/String; ***/
extern JRI_PUBLIC_API(struct java_lang_String *)
native_java_util_Date_toLocaleString(JRIEnv* env, struct java_util_Date* self);

/*** public native toGMTString ()Ljava/lang/String; ***/
extern JRI_PUBLIC_API(struct java_lang_String *)
native_java_util_Date_toGMTString(JRIEnv* env, struct java_util_Date* self);

/*** private native expand ()V ***/
extern JRI_PUBLIC_API(void)
native_java_util_Date_expand(JRIEnv* env, struct java_util_Date* self);

/*** private native computeValue ()V ***/
extern JRI_PUBLIC_API(void)
native_java_util_Date_computeValue(JRIEnv* env, struct java_util_Date* self);

/*******************************************************************************
 * Implementation Field Accessors: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** private value J ***/
extern JRI_PUBLIC_API(jlong)
get_java_util_Date_value(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_value(JRIEnv* env, java_util_Date* obj, jlong v);

/*** private valueValid Z ***/
extern JRI_PUBLIC_API(jbool)
get_java_util_Date_valueValid(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_valueValid(JRIEnv* env, java_util_Date* obj, jbool v);

/*** private expanded Z ***/
extern JRI_PUBLIC_API(jbool)
get_java_util_Date_expanded(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_expanded(JRIEnv* env, java_util_Date* obj, jbool v);

/*** private tm_millis S ***/
extern JRI_PUBLIC_API(jshort)
get_java_util_Date_tm_millis(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_tm_millis(JRIEnv* env, java_util_Date* obj, jshort v);

/*** private tm_sec B ***/
extern JRI_PUBLIC_API(jbyte)
get_java_util_Date_tm_sec(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_tm_sec(JRIEnv* env, java_util_Date* obj, jbyte v);

/*** private tm_min B ***/
extern JRI_PUBLIC_API(jbyte)
get_java_util_Date_tm_min(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_tm_min(JRIEnv* env, java_util_Date* obj, jbyte v);

/*** private tm_hour B ***/
extern JRI_PUBLIC_API(jbyte)
get_java_util_Date_tm_hour(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_tm_hour(JRIEnv* env, java_util_Date* obj, jbyte v);

/*** private tm_mday B ***/
extern JRI_PUBLIC_API(jbyte)
get_java_util_Date_tm_mday(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_tm_mday(JRIEnv* env, java_util_Date* obj, jbyte v);

/*** private tm_mon B ***/
extern JRI_PUBLIC_API(jbyte)
get_java_util_Date_tm_mon(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_tm_mon(JRIEnv* env, java_util_Date* obj, jbyte v);

/*** private tm_wday B ***/
extern JRI_PUBLIC_API(jbyte)
get_java_util_Date_tm_wday(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_tm_wday(JRIEnv* env, java_util_Date* obj, jbyte v);

/*** private tm_yday S ***/
extern JRI_PUBLIC_API(jshort)
get_java_util_Date_tm_yday(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_tm_yday(JRIEnv* env, java_util_Date* obj, jshort v);

/*** private tm_year I ***/
extern JRI_PUBLIC_API(jint)
get_java_util_Date_tm_year(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_tm_year(JRIEnv* env, java_util_Date* obj, jint v);

/*** private tm_isdst I ***/
extern JRI_PUBLIC_API(jint)
get_java_util_Date_tm_isdst(JRIEnv* env, java_util_Date* obj);
extern JRI_PUBLIC_API(void)
set_java_util_Date_tm_isdst(JRIEnv* env, java_util_Date* obj, jint v);

/*** private static monthOffset [S ***/
extern JRI_PUBLIC_API(jref)
get_java_util_Date_monthOffset(JRIEnv* env, struct java_lang_Class* clazz);
extern JRI_PUBLIC_API(void)
set_java_util_Date_monthOffset(JRIEnv* env, struct java_lang_Class* clazz, jref v);

/*** private static final wtb [Ljava/lang/String; ***/
extern JRI_PUBLIC_API(jref)
get_java_util_Date_wtb(JRIEnv* env, struct java_lang_Class* clazz);
extern JRI_PUBLIC_API(void)
set_java_util_Date_wtb(JRIEnv* env, struct java_lang_Class* clazz, jref v);

/*** private static final ttb [I ***/
extern JRI_PUBLIC_API(jref)
get_java_util_Date_ttb(JRIEnv* env, struct java_lang_Class* clazz);
extern JRI_PUBLIC_API(void)
set_java_util_Date_ttb(JRIEnv* env, struct java_lang_Class* clazz, jref v);

#else /* !DEBUG */

/*** private value J ***/
#define get_java_util_Date_value(env, obj) \
	(JRI_GetFieldLong(env, obj, fieldID_java_util_Date_value))
#define set_java_util_Date_value(env, obj, v) \
	JRI_SetFieldLong(env, obj, fieldID_java_util_Date_value, v)

/*** private valueValid Z ***/
#define get_java_util_Date_valueValid(env, obj) \
	(JRI_GetFieldBoolean(env, obj, fieldID_java_util_Date_valueValid))
#define set_java_util_Date_valueValid(env, obj, v) \
	JRI_SetFieldBoolean(env, obj, fieldID_java_util_Date_valueValid, v)

/*** private expanded Z ***/
#define get_java_util_Date_expanded(env, obj) \
	(JRI_GetFieldBoolean(env, obj, fieldID_java_util_Date_expanded))
#define set_java_util_Date_expanded(env, obj, v) \
	JRI_SetFieldBoolean(env, obj, fieldID_java_util_Date_expanded, v)

/*** private tm_millis S ***/
#define get_java_util_Date_tm_millis(env, obj) \
	(JRI_GetFieldShort(env, obj, fieldID_java_util_Date_tm_millis))
#define set_java_util_Date_tm_millis(env, obj, v) \
	JRI_SetFieldShort(env, obj, fieldID_java_util_Date_tm_millis, v)

/*** private tm_sec B ***/
#define get_java_util_Date_tm_sec(env, obj) \
	(JRI_GetFieldByte(env, obj, fieldID_java_util_Date_tm_sec))
#define set_java_util_Date_tm_sec(env, obj, v) \
	JRI_SetFieldByte(env, obj, fieldID_java_util_Date_tm_sec, v)

/*** private tm_min B ***/
#define get_java_util_Date_tm_min(env, obj) \
	(JRI_GetFieldByte(env, obj, fieldID_java_util_Date_tm_min))
#define set_java_util_Date_tm_min(env, obj, v) \
	JRI_SetFieldByte(env, obj, fieldID_java_util_Date_tm_min, v)

/*** private tm_hour B ***/
#define get_java_util_Date_tm_hour(env, obj) \
	(JRI_GetFieldByte(env, obj, fieldID_java_util_Date_tm_hour))
#define set_java_util_Date_tm_hour(env, obj, v) \
	JRI_SetFieldByte(env, obj, fieldID_java_util_Date_tm_hour, v)

/*** private tm_mday B ***/
#define get_java_util_Date_tm_mday(env, obj) \
	(JRI_GetFieldByte(env, obj, fieldID_java_util_Date_tm_mday))
#define set_java_util_Date_tm_mday(env, obj, v) \
	JRI_SetFieldByte(env, obj, fieldID_java_util_Date_tm_mday, v)

/*** private tm_mon B ***/
#define get_java_util_Date_tm_mon(env, obj) \
	(JRI_GetFieldByte(env, obj, fieldID_java_util_Date_tm_mon))
#define set_java_util_Date_tm_mon(env, obj, v) \
	JRI_SetFieldByte(env, obj, fieldID_java_util_Date_tm_mon, v)

/*** private tm_wday B ***/
#define get_java_util_Date_tm_wday(env, obj) \
	(JRI_GetFieldByte(env, obj, fieldID_java_util_Date_tm_wday))
#define set_java_util_Date_tm_wday(env, obj, v) \
	JRI_SetFieldByte(env, obj, fieldID_java_util_Date_tm_wday, v)

/*** private tm_yday S ***/
#define get_java_util_Date_tm_yday(env, obj) \
	(JRI_GetFieldShort(env, obj, fieldID_java_util_Date_tm_yday))
#define set_java_util_Date_tm_yday(env, obj, v) \
	JRI_SetFieldShort(env, obj, fieldID_java_util_Date_tm_yday, v)

/*** private tm_year I ***/
#define get_java_util_Date_tm_year(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_java_util_Date_tm_year))
#define set_java_util_Date_tm_year(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_java_util_Date_tm_year, v)

/*** private tm_isdst I ***/
#define get_java_util_Date_tm_isdst(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_java_util_Date_tm_isdst))
#define set_java_util_Date_tm_isdst(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_java_util_Date_tm_isdst, v)

/*** private static monthOffset [S ***/
#define get_java_util_Date_monthOffset(env, clazz) \
	((jref)JRI_GetStaticField(env, clazz, fieldID_java_util_Date_monthOffset))
#define set_java_util_Date_monthOffset(env, clazz, v) \
	JRI_SetStaticField(env, clazz, fieldID_java_util_Date_monthOffset, v)

/*** private static final wtb [Ljava/lang/String; ***/
#define get_java_util_Date_wtb(env, clazz) \
	((jref)JRI_GetStaticField(env, clazz, fieldID_java_util_Date_wtb))
#define set_java_util_Date_wtb(env, clazz, v) \
	JRI_SetStaticField(env, clazz, fieldID_java_util_Date_wtb, v)

/*** private static final ttb [I ***/
#define get_java_util_Date_ttb(env, clazz) \
	((jref)JRI_GetStaticField(env, clazz, fieldID_java_util_Date_ttb))
#define set_java_util_Date_ttb(env, clazz, v) \
	JRI_SetStaticField(env, clazz, fieldID_java_util_Date_ttb, v)

#endif /* !DEBUG*/

extern JRIFieldID FAR fieldID_java_util_Date_value;
#define name_java_util_Date_value	"value"
#define sig_java_util_Date_value 	"J"
#define use_java_util_Date_value(env, clazz)	\
	(fieldID_java_util_Date_value =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_value,	\
			sig_java_util_Date_value))
#define unuse_java_util_Date_value(env, clazz)	\
		(fieldID_java_util_Date_value = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_valueValid;
#define name_java_util_Date_valueValid	"valueValid"
#define sig_java_util_Date_valueValid 	"Z"
#define use_java_util_Date_valueValid(env, clazz)	\
	(fieldID_java_util_Date_valueValid =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_valueValid,	\
			sig_java_util_Date_valueValid))
#define unuse_java_util_Date_valueValid(env, clazz)	\
		(fieldID_java_util_Date_valueValid = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_expanded;
#define name_java_util_Date_expanded	"expanded"
#define sig_java_util_Date_expanded 	"Z"
#define use_java_util_Date_expanded(env, clazz)	\
	(fieldID_java_util_Date_expanded =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_expanded,	\
			sig_java_util_Date_expanded))
#define unuse_java_util_Date_expanded(env, clazz)	\
		(fieldID_java_util_Date_expanded = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_tm_millis;
#define name_java_util_Date_tm_millis	"tm_millis"
#define sig_java_util_Date_tm_millis 	"S"
#define use_java_util_Date_tm_millis(env, clazz)	\
	(fieldID_java_util_Date_tm_millis =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_tm_millis,	\
			sig_java_util_Date_tm_millis))
#define unuse_java_util_Date_tm_millis(env, clazz)	\
		(fieldID_java_util_Date_tm_millis = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_tm_sec;
#define name_java_util_Date_tm_sec	"tm_sec"
#define sig_java_util_Date_tm_sec 	"B"
#define use_java_util_Date_tm_sec(env, clazz)	\
	(fieldID_java_util_Date_tm_sec =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_tm_sec,	\
			sig_java_util_Date_tm_sec))
#define unuse_java_util_Date_tm_sec(env, clazz)	\
		(fieldID_java_util_Date_tm_sec = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_tm_min;
#define name_java_util_Date_tm_min	"tm_min"
#define sig_java_util_Date_tm_min 	"B"
#define use_java_util_Date_tm_min(env, clazz)	\
	(fieldID_java_util_Date_tm_min =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_tm_min,	\
			sig_java_util_Date_tm_min))
#define unuse_java_util_Date_tm_min(env, clazz)	\
		(fieldID_java_util_Date_tm_min = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_tm_hour;
#define name_java_util_Date_tm_hour	"tm_hour"
#define sig_java_util_Date_tm_hour 	"B"
#define use_java_util_Date_tm_hour(env, clazz)	\
	(fieldID_java_util_Date_tm_hour =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_tm_hour,	\
			sig_java_util_Date_tm_hour))
#define unuse_java_util_Date_tm_hour(env, clazz)	\
		(fieldID_java_util_Date_tm_hour = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_tm_mday;
#define name_java_util_Date_tm_mday	"tm_mday"
#define sig_java_util_Date_tm_mday 	"B"
#define use_java_util_Date_tm_mday(env, clazz)	\
	(fieldID_java_util_Date_tm_mday =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_tm_mday,	\
			sig_java_util_Date_tm_mday))
#define unuse_java_util_Date_tm_mday(env, clazz)	\
		(fieldID_java_util_Date_tm_mday = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_tm_mon;
#define name_java_util_Date_tm_mon	"tm_mon"
#define sig_java_util_Date_tm_mon 	"B"
#define use_java_util_Date_tm_mon(env, clazz)	\
	(fieldID_java_util_Date_tm_mon =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_tm_mon,	\
			sig_java_util_Date_tm_mon))
#define unuse_java_util_Date_tm_mon(env, clazz)	\
		(fieldID_java_util_Date_tm_mon = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_tm_wday;
#define name_java_util_Date_tm_wday	"tm_wday"
#define sig_java_util_Date_tm_wday 	"B"
#define use_java_util_Date_tm_wday(env, clazz)	\
	(fieldID_java_util_Date_tm_wday =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_tm_wday,	\
			sig_java_util_Date_tm_wday))
#define unuse_java_util_Date_tm_wday(env, clazz)	\
		(fieldID_java_util_Date_tm_wday = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_tm_yday;
#define name_java_util_Date_tm_yday	"tm_yday"
#define sig_java_util_Date_tm_yday 	"S"
#define use_java_util_Date_tm_yday(env, clazz)	\
	(fieldID_java_util_Date_tm_yday =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_tm_yday,	\
			sig_java_util_Date_tm_yday))
#define unuse_java_util_Date_tm_yday(env, clazz)	\
		(fieldID_java_util_Date_tm_yday = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_tm_year;
#define name_java_util_Date_tm_year	"tm_year"
#define sig_java_util_Date_tm_year 	"I"
#define use_java_util_Date_tm_year(env, clazz)	\
	(fieldID_java_util_Date_tm_year =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_tm_year,	\
			sig_java_util_Date_tm_year))
#define unuse_java_util_Date_tm_year(env, clazz)	\
		(fieldID_java_util_Date_tm_year = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_tm_isdst;
#define name_java_util_Date_tm_isdst	"tm_isdst"
#define sig_java_util_Date_tm_isdst 	"I"
#define use_java_util_Date_tm_isdst(env, clazz)	\
	(fieldID_java_util_Date_tm_isdst =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_util_Date_tm_isdst,	\
			sig_java_util_Date_tm_isdst))
#define unuse_java_util_Date_tm_isdst(env, clazz)	\
		(fieldID_java_util_Date_tm_isdst = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_monthOffset;
#define name_java_util_Date_monthOffset	"monthOffset"
#define sig_java_util_Date_monthOffset 	"[S"
#define use_java_util_Date_monthOffset(env, clazz)	\
	(fieldID_java_util_Date_monthOffset =	\
		JRI_GetStaticFieldID(env, clazz,	\
			name_java_util_Date_monthOffset,	\
			sig_java_util_Date_monthOffset))
#define unuse_java_util_Date_monthOffset(env, clazz)	\
		(fieldID_java_util_Date_monthOffset = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_wtb;
#define name_java_util_Date_wtb	"wtb"
#define sig_java_util_Date_wtb 	"[Ljava/lang/String;"
#define use_java_util_Date_wtb(env, clazz)	\
	(fieldID_java_util_Date_wtb =	\
		JRI_GetStaticFieldID(env, clazz,	\
			name_java_util_Date_wtb,	\
			sig_java_util_Date_wtb))
#define unuse_java_util_Date_wtb(env, clazz)	\
		(fieldID_java_util_Date_wtb = JRIUninitialized)

extern JRIFieldID FAR fieldID_java_util_Date_ttb;
#define name_java_util_Date_ttb	"ttb"
#define sig_java_util_Date_ttb 	"[I"
#define use_java_util_Date_ttb(env, clazz)	\
	(fieldID_java_util_Date_ttb =	\
		JRI_GetStaticFieldID(env, clazz,	\
			name_java_util_Date_ttb,	\
			sig_java_util_Date_ttb))
#define unuse_java_util_Date_ttb(env, clazz)	\
		(fieldID_java_util_Date_ttb = JRIUninitialized)

/*******************************************************************************
 * Implementation Methods: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** private native expand ()V ***/
extern JRI_PUBLIC_API(void)
java_util_Date_expand(JRIEnv* env, struct java_util_Date* self);

/*** private native computeValue ()V ***/
extern JRI_PUBLIC_API(void)
java_util_Date_computeValue(JRIEnv* env, struct java_util_Date* self);

/*** static <clinit> ()V ***/
extern JRI_PUBLIC_API(void)
java_util_Date__0003cclinit_0003e(JRIEnv* env, struct java_lang_Class* clazz);

#else /* !DEBUG */

/*** private native expand ()V ***/
#define java_util_Date_expand(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_expand))

/*** private native computeValue ()V ***/
#define java_util_Date_computeValue(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_util_Date_computeValue))

/*** static <clinit> ()V ***/
#define java_util_Date__0003cclinit_0003e(env, clazz) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_util_Date__0003cclinit_0003e))

#endif /* !DEBUG*/

/*** private native expand ()V ***/
extern JRIMethodID FAR methodID_java_util_Date_expand;
#define name_java_util_Date_expand	"expand"
#define sig_java_util_Date_expand 	"()V"
#define use_java_util_Date_expand(env, clazz)	\
	(methodID_java_util_Date_expand =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_expand,	\
			sig_java_util_Date_expand))
#define unuse_java_util_Date_expand(env, clazz)	\
	(methodID_java_util_Date_expand = JRIUninitialized)

/*** private native computeValue ()V ***/
extern JRIMethodID FAR methodID_java_util_Date_computeValue;
#define name_java_util_Date_computeValue	"computeValue"
#define sig_java_util_Date_computeValue 	"()V"
#define use_java_util_Date_computeValue(env, clazz)	\
	(methodID_java_util_Date_computeValue =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_util_Date_computeValue,	\
			sig_java_util_Date_computeValue))
#define unuse_java_util_Date_computeValue(env, clazz)	\
	(methodID_java_util_Date_computeValue = JRIUninitialized)

/*** static <clinit> ()V ***/
extern JRIMethodID FAR methodID_java_util_Date__0003cclinit_0003e;
#define name_java_util_Date__0003cclinit_0003e	"<clinit>"
#define sig_java_util_Date__0003cclinit_0003e 	"()V"
#define use_java_util_Date__0003cclinit_0003e(env, clazz)	\
	(methodID_java_util_Date__0003cclinit_0003e =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_java_util_Date__0003cclinit_0003e,	\
			sig_java_util_Date__0003cclinit_0003e))
#define unuse_java_util_Date__0003cclinit_0003e(env, clazz)	\
	(methodID_java_util_Date__0003cclinit_0003e = JRIUninitialized)

#endif /* IMPLEMENT_java_util_Date */

#ifdef __cplusplus
} /* extern "C" */

/*******************************************************************************
 * C++ Definitions
 ******************************************************************************/

#include "java_lang_Object.h"

struct java_util_Date : virtual public java_lang_Object {

	static struct java_lang_Class* _use(JRIEnv* env) {
		return use_java_util_Date(env);
	}

	static void _unuse(JRIEnv* env) {
		unuse_java_util_Date(env);
	}

	static struct java_lang_Class* _register(JRIEnv* env) {
		return register_java_util_Date(env);
	}

	static void _unregister(JRIEnv* env) {
		unregister_java_util_Date(env);
	}

	static struct java_lang_Class* _class(JRIEnv* env) {
		return class_java_util_Date(env);
	}

	/* Public Methods */
	/*** public <init> ()V ***/
	static java_util_Date* _new(JRIEnv* env, struct java_lang_Class* clazz) {
		return java_util_Date_new(env, clazz);
	}

	/*** public <init> (J)V ***/
	static java_util_Date* _new(JRIEnv* env, struct java_lang_Class* clazz, jlong a) {
		return java_util_Date_new_1(env, clazz, a);
	}

	/*** public <init> (III)V ***/
	static java_util_Date* _new(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c) {
		return java_util_Date_new_2(env, clazz, a, b, c);
	}

	/*** public <init> (IIIII)V ***/
	static java_util_Date* _new(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c, jint d, jint e) {
		return java_util_Date_new_3(env, clazz, a, b, c, d, e);
	}

	/*** public <init> (IIIIII)V ***/
	static java_util_Date* _new(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c, jint d, jint e, jint f) {
		return java_util_Date_new_4(env, clazz, a, b, c, d, e, f);
	}

	/*** public <init> (Ljava/lang/String;)V ***/
	static java_util_Date* _new(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a) {
		return java_util_Date_new_5(env, clazz, a);
	}

	/*** public static UTC (IIIIII)J ***/
	static jlong UTC(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c, jint d, jint e, jint f) {
		return java_util_Date_UTC(env, clazz, a, b, c, d, e, f);
	}

	/*** public static parse (Ljava/lang/String;)J ***/
	static jlong parse(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a) {
		return java_util_Date_parse(env, clazz, a);
	}

	/*** public getYear ()I ***/
	jint getYear(JRIEnv* env) {
		return java_util_Date_getYear(env, this);
	}

	/*** public setYear (I)V ***/
	void setYear(JRIEnv* env, jint a) {
		java_util_Date_setYear(env, this, a);
	}

	/*** public getMonth ()I ***/
	jint getMonth(JRIEnv* env) {
		return java_util_Date_getMonth(env, this);
	}

	/*** public setMonth (I)V ***/
	void setMonth(JRIEnv* env, jint a) {
		java_util_Date_setMonth(env, this, a);
	}

	/*** public getDate ()I ***/
	jint getDate(JRIEnv* env) {
		return java_util_Date_getDate(env, this);
	}

	/*** public setDate (I)V ***/
	void setDate(JRIEnv* env, jint a) {
		java_util_Date_setDate(env, this, a);
	}

	/*** public getDay ()I ***/
	jint getDay(JRIEnv* env) {
		return java_util_Date_getDay(env, this);
	}

	/*** public getHours ()I ***/
	jint getHours(JRIEnv* env) {
		return java_util_Date_getHours(env, this);
	}

	/*** public setHours (I)V ***/
	void setHours(JRIEnv* env, jint a) {
		java_util_Date_setHours(env, this, a);
	}

	/*** public getMinutes ()I ***/
	jint getMinutes(JRIEnv* env) {
		return java_util_Date_getMinutes(env, this);
	}

	/*** public setMinutes (I)V ***/
	void setMinutes(JRIEnv* env, jint a) {
		java_util_Date_setMinutes(env, this, a);
	}

	/*** public getSeconds ()I ***/
	jint getSeconds(JRIEnv* env) {
		return java_util_Date_getSeconds(env, this);
	}

	/*** public setSeconds (I)V ***/
	void setSeconds(JRIEnv* env, jint a) {
		java_util_Date_setSeconds(env, this, a);
	}

	/*** public getTime ()J ***/
	jlong getTime(JRIEnv* env) {
		return java_util_Date_getTime(env, this);
	}

	/*** public setTime (J)V ***/
	void setTime(JRIEnv* env, jlong a) {
		java_util_Date_setTime(env, this, a);
	}

	/*** public before (Ljava/util/Date;)Z ***/
	jbool before(JRIEnv* env, struct java_util_Date *a) {
		return java_util_Date_before(env, this, a);
	}

	/*** public after (Ljava/util/Date;)Z ***/
	jbool after(JRIEnv* env, struct java_util_Date *a) {
		return java_util_Date_after(env, this, a);
	}

	/*** public equals (Ljava/lang/Object;)Z ***/
	jbool equals(JRIEnv* env, struct java_lang_Object *a) {
		return java_util_Date_equals(env, this, a);
	}

	/*** public hashCode ()I ***/
	jint hashCode(JRIEnv* env) {
		return java_util_Date_hashCode(env, this);
	}

	/*** public native toString ()Ljava/lang/String; ***/
	struct java_lang_String * toString(JRIEnv* env) {
		return java_util_Date_toString(env, this);
	}

	/*** public native toLocaleString ()Ljava/lang/String; ***/
	struct java_lang_String * toLocaleString(JRIEnv* env) {
		return java_util_Date_toLocaleString(env, this);
	}

	/*** public native toGMTString ()Ljava/lang/String; ***/
	struct java_lang_String * toGMTString(JRIEnv* env) {
		return java_util_Date_toGMTString(env, this);
	}

	/*** public getTimezoneOffset ()I ***/
	jint getTimezoneOffset(JRIEnv* env) {
		return java_util_Date_getTimezoneOffset(env, this);
	}

#ifdef IMPLEMENT_java_util_Date

	/* Private Field Accessors */
	/*** private value J ***/
	jlong value(JRIEnv* env) {
		return get_java_util_Date_value(env, this);
	}
	void value(JRIEnv* env, jlong v) {
		set_java_util_Date_value(env, this, v);
	}

	/*** private valueValid Z ***/
	jbool valueValid(JRIEnv* env) {
		return get_java_util_Date_valueValid(env, this);
	}
	void valueValid(JRIEnv* env, jbool v) {
		set_java_util_Date_valueValid(env, this, v);
	}

	/*** private expanded Z ***/
	jbool expanded(JRIEnv* env) {
		return get_java_util_Date_expanded(env, this);
	}
	void expanded(JRIEnv* env, jbool v) {
		set_java_util_Date_expanded(env, this, v);
	}

	/*** private tm_millis S ***/
	jshort tm_millis(JRIEnv* env) {
		return get_java_util_Date_tm_millis(env, this);
	}
	void tm_millis(JRIEnv* env, jshort v) {
		set_java_util_Date_tm_millis(env, this, v);
	}

	/*** private tm_sec B ***/
	jbyte tm_sec(JRIEnv* env) {
		return get_java_util_Date_tm_sec(env, this);
	}
	void tm_sec(JRIEnv* env, jbyte v) {
		set_java_util_Date_tm_sec(env, this, v);
	}

	/*** private tm_min B ***/
	jbyte tm_min(JRIEnv* env) {
		return get_java_util_Date_tm_min(env, this);
	}
	void tm_min(JRIEnv* env, jbyte v) {
		set_java_util_Date_tm_min(env, this, v);
	}

	/*** private tm_hour B ***/
	jbyte tm_hour(JRIEnv* env) {
		return get_java_util_Date_tm_hour(env, this);
	}
	void tm_hour(JRIEnv* env, jbyte v) {
		set_java_util_Date_tm_hour(env, this, v);
	}

	/*** private tm_mday B ***/
	jbyte tm_mday(JRIEnv* env) {
		return get_java_util_Date_tm_mday(env, this);
	}
	void tm_mday(JRIEnv* env, jbyte v) {
		set_java_util_Date_tm_mday(env, this, v);
	}

	/*** private tm_mon B ***/
	jbyte tm_mon(JRIEnv* env) {
		return get_java_util_Date_tm_mon(env, this);
	}
	void tm_mon(JRIEnv* env, jbyte v) {
		set_java_util_Date_tm_mon(env, this, v);
	}

	/*** private tm_wday B ***/
	jbyte tm_wday(JRIEnv* env) {
		return get_java_util_Date_tm_wday(env, this);
	}
	void tm_wday(JRIEnv* env, jbyte v) {
		set_java_util_Date_tm_wday(env, this, v);
	}

	/*** private tm_yday S ***/
	jshort tm_yday(JRIEnv* env) {
		return get_java_util_Date_tm_yday(env, this);
	}
	void tm_yday(JRIEnv* env, jshort v) {
		set_java_util_Date_tm_yday(env, this, v);
	}

	/*** private tm_year I ***/
	jint tm_year(JRIEnv* env) {
		return get_java_util_Date_tm_year(env, this);
	}
	void tm_year(JRIEnv* env, jint v) {
		set_java_util_Date_tm_year(env, this, v);
	}

	/*** private tm_isdst I ***/
	jint tm_isdst(JRIEnv* env) {
		return get_java_util_Date_tm_isdst(env, this);
	}
	void tm_isdst(JRIEnv* env, jint v) {
		set_java_util_Date_tm_isdst(env, this, v);
	}

	/* Private Methods */
	/*** private native expand ()V ***/
	void expand(JRIEnv* env) {
		java_util_Date_expand(env, this);
	}

	/*** private native computeValue ()V ***/
	void computeValue(JRIEnv* env) {
		java_util_Date_computeValue(env, this);
	}

#endif /* IMPLEMENT_java_util_Date */
};

#endif /* __cplusplus */

#endif /* Class java/util/Date */
